### ISSUE TITLE
Error: Failed to unwrap shared reference of `NativeNoteEncrypted` type from napi value

### ISSUE THREAD

**Issue by urfinjs** [iron-fish/ironfish#1032]
### What happened?

Same as https://github.com/iron-fish/ironfish/issues/1022 but for the 0.1.23 version.

Environment: ubuntu 20.04 minimal,  Ryzen 5 3600, 64GB RAM, installed from source.

systemctl stop ironfishd ironfishd-miner
cargo install --force wasm-pack && yarn
systemctl restart ironfishd ironfishd-miner

and then a bit trimmed log:

### Version

0.1.23

### Relevant log output

```shell
WebSocket server started at :::9033
Connected to the Iron Fish network
Peer xwywJsw (1ce) sent orphan 00000...fff4d (117090), syncing orphan chain.
Starting sync from xwywJsw (1ce). work: +137921256403776, ours: 117084, theirs: 117089
Finding ancestor using linear search on last 3 blocks starting at 00000...bdc70 (117084) from peer xwywJsw (1ce) at 117089
Found peer xwywJsw (1ce) ancestor 00000...bdc70, syncing from 117084 -> 117090 (6) after 1 requests
Requesting 20 blocks starting at 00000...bdc70 (117084) from xwywJsw (1ce)
Finished syncing 6 blocks from xwywJsw (1ce)
Added block seq: 117100, hash: 00000...8b663, txs: 1, progress: 100.00%, time: 25.2ms
/root/ironfish/ironfish/build/src/primitives/noteEncrypted.js:33
        const note = this.takeReference().decryptNoteForOwner(ownerHexKey);
                                              ^
Error: Failed to unwrap shared reference of `NativeNoteEncrypted` type from napi value
    at NoteEncrypted.decryptNoteForOwner (/root/ironfish/ironfish/build/src/primitives/noteEncrypted.js:33:43)
    at Accounts.decryptNotes (/root/ironfish/ironfish/build/src/account/accounts.js:227:43)
    at /root/ironfish/ironfish/build/src/account/accounts.js:272:32
    at Transaction.withReference (/root/ironfish/ironfish/build/src/primitives/transaction.js:45:24)
    at Accounts.syncTransaction (/root/ironfish/ironfish/build/src/account/accounts.js:271:27)
    at /root/ironfish/ironfish/build/src/account/accounts.js:45:28
    at async Promise.all (index 0)
    at async Event.emitAsync (/root/ironfish/ironfish/build/src/event.js:64:9)
    at async ChainProcessor.add (/root/ironfish/ironfish/build/src/chainProcessor.js:37:9)
    at async ChainProcessor.update (/root/ironfish/ironfish/build/src/chainProcessor.js:80:13) {
  code: 'InvalidArg'
}
error Command failed with exit code 1.
```

**Comment by dguenther** [comment]
I'm going to close this in favor of #1022 just to keep discussion in one place, but thanks for reporting that this is still an issue on 0.1.23! I'll tag you in #1022 as well so you can follow along on progress.
