### ISSUE TITLE
[issue name] Failed to unwrap shared reference of `NativeNoteEncrypted` type from napi value

### ISSUE THREAD

**Issue by 1613557499** [iron-fish/ironfish#1054]
### What happened?

The program stops running automatically, and the new container reports an error

### Version

v0.1.24

### Relevant log output

```shell
WebSocket server started at :::9033
Connected to the Iron Fish network
Starting sync from 63jk/WB (labelchain). work: +864923418873308, ours: 123036, theirs: 123064
Finding ancestor using linear search on last 3 blocks starting at 00000...d19f2 (123036) from peer 63jk/WB (labelchain) at 123064
Found peer 63jk/WB (labelchain) ancestor 00000...d19f2, syncing from 123036 -> 123064 (28) after 1 requests
Requesting 20 blocks starting at 00000...d19f2 (123036) from 63jk/WB (labelchain)
Added block seq: 123040, hash: 00000...9d10a, txs: 1, progress: 99.99%, time: 32.2ms
Requesting 20 blocks starting at 00000...74c15 (123056) from 63jk/WB (labelchain)
Added block seq: 123060, hash: 00000...6b00a, txs: 1, progress: 100.00%, time: 35.7ms
Finished syncing 28 blocks from 63jk/WB (labelchain)
/usr/src/app/node_modules/ironfish/build/src/primitives/noteEncrypted.js:33
        const note = this.takeReference().decryptNoteForOwner(ownerHexKey);
                                          ^

Error: Failed to unwrap shared reference of `NativeNoteEncrypted` type from napi value
    at NoteEncrypted.decryptNoteForOwner (/usr/src/app/node_modules/ironfish/build/src/primitives/noteEncrypted.js:33:43)
    at Accounts.decryptNotes (/usr/src/app/node_modules/ironfish/build/src/account/accounts.js:227:43)
    at /usr/src/app/node_modules/ironfish/build/src/account/accounts.js:272:32
    at Transaction.withReference (/usr/src/app/node_modules/ironfish/build/src/primitives/transaction.js:45:24)
    at Accounts.syncTransaction (/usr/src/app/node_modules/ironfish/build/src/account/accounts.js:271:27)
    at /usr/src/app/node_modules/ironfish/build/src/account/accounts.js:45:28
    at async Promise.all (index 0)
    at async Event.emitAsync (/usr/src/app/node_modules/ironfish/build/src/event.js:64:9)
    at async ChainProcessor.add (/usr/src/app/node_modules/ironfish/build/src/chainProcessor.js:37:9)
    at async ChainProcessor.update (/usr/src/app/node_modules/ironfish/build/src/chainProcessor.js:80:13) {
  code: 'InvalidArg'
}
```

**Comment by mat-if** [comment]
As mentioned above, we have an issue related to this. Going to close this as it's easier for us if we have one place to track it. Thank you for submitting this issue! The more info we have the better.
