### ISSUE TITLE
Failed to unwrap shared reference of `NativeNoteEncrypted` type

### ISSUE THREAD

**Issue by QustomQure** [iron-fish/ironfish#1085]
### What happened?

Node stopped randomly with this error

### Version

0.1.25

### Debug output

```shell
PS C:\Users\fr0ze\ironfish-master\ironfish-cli> yarn start:once debug
yarn run v1.22.15
$ yarn build && yarn start:js debug
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run debug

Iron Fish version       0.1.25 @ src
Iron Fish library       0.0.1 @ src
Operating system        Windows_NT x64
CPU model(s)            AMD Ryzen 9 5950X 16-Core Processor
CPU threads             32
RAM total               63.92 GiB
Node version            v16.13.2
Telemetry enabled       true
Accounts head hash      0000000000013afb9513d6fef584ea393406af0c48ab6c7270d70f480eb0f544
Accounts head in chain  true
Accounts head sequence  131958
```

### Relevant log output

```shell
Added block seq: 131940, hash: 00000...6da7c, txs: 1, progress: 99.95%, time: 26.6ms
Requesting 20 blocks starting at 00000...56e3b (131953) from 0OtY0Xh (antip-1)
Added block seq: 131960, hash: 00000...4f245, txs: 1, progress: 99.96%, time: 15.0ms
Requesting 20 blocks starting at 00000...ed322 (131973) from 0OtY0Xh (antip-1)
C:\Users\fr0ze\ironfish-master\ironfish\build\src\primitives\noteEncrypted.js:33
        const note = this.takeReference().decryptNoteForOwner(ownerHexKey);
                                          ^

Error: Failed to unwrap shared reference of `NativeNoteEncrypted` type from napi value
    at NoteEncrypted.decryptNoteForOwner (C:\Users\fr0ze\ironfish-master\ironfish\build\src\primitives\noteEncrypted.js:33:43)
    at Accounts.decryptNotes (C:\Users\fr0ze\ironfish-master\ironfish\build\src\account\accounts.js:227:43)
    at C:\Users\fr0ze\ironfish-master\ironfish\build\src\account\accounts.js:272:32
    at Transaction.withReference (C:\Users\fr0ze\ironfish-master\ironfish\build\src\primitives\transaction.js:45:24)
    at Accounts.syncTransaction (C:\Users\fr0ze\ironfish-master\ironfish\build\src\account\accounts.js:271:27)
    at C:\Users\fr0ze\ironfish-master\ironfish\build\src\account\accounts.js:45:28
    at async Promise.all (index 0)
    at async Event.emitAsync (C:\Users\fr0ze\ironfish-master\ironfish\build\src\event.js:64:9)
    at async ChainProcessor.add (C:\Users\fr0ze\ironfish-master\ironfish\build\src\chainProcessor.js:37:9)
    at async ChainProcessor.update (C:\Users\fr0ze\ironfish-master\ironfish\build\src\chainProcessor.js:80:13) {
  code: 'InvalidArg'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by dguenther** [comment]
Could you try running `yarn install` from the root directory (looks like it'll be `ironfish-master` for you) to make sure the Rust code rebuilds? I think that should fix it, but if it doesn't, could you share the output of `git rev-parse HEAD`?

**Comment by deekerno** [comment]
Closing due to inactivity. If you are still encountering this problem after updating to the newest version, feel free to re-open this issue.
