### ISSUE TITLE
npm install ironfish failed

### ISSUE THREAD

**Issue by QustomQure** [iron-fish/ironfish#1136]
### What happened?

Trying to install through: npm install -g ironfish

full log
https://drive.google.com/file/d/13M6rj3Abb3-VyI4AzTw89dp644LK4AGm/view?usp=sharing

### Version

v0.1.26

### Relevant log output

```shell
npm install -g ironfish
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated cli-ux@4.9.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! code 1
npm ERR! path C:\Users\fr0ze\AppData\Roaming\npm\node_modules\ironfish\node_modules\segfault-handler
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.13.2 | win32 | x64
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Program Files\Python38\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                       ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:397:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\fr0ze\\AppData\\Roaming\\npm\\node_modules\\ironfish\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\fr0ze\AppData\Roaming\npm\node_modules\ironfish\node_modules\segfault-handler
npm ERR! gyp ERR! node -v v16.13.2
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fr0ze\AppData\Local\npm-cache\_logs\2022-03-15T23_24_27_262Z-debug-0.log
```

### Graffiti

Qualia

**Comment by Kupuyc** [comment]
In python 3 `print` is function, not statement. But it was fixed in `node-gyp` years ago.

I guess core of problem is version of `node-gyp` which looks sooo obsolete:

> npm ERR! gyp info using node-gyp@3.8.0

Seems like some version race: 8.4.1 in `package.json` but track of 3.8.0 in `yarn.lock`.

**Comment by QustomQure** [comment]
How i can see build cache?

**Comment by Kupuyc** [comment]
In no way, I think. In fact, it's just a guess.

**Comment by mat-if** [comment]
Can you try running `npm config set python python2.7` and trying again? Huge thanks to pshri#7271 on Discord for suggesting this

**Comment by QustomQure** [comment]
Yeh i try it but still same error:

**Comment by QustomQure** [comment]
PS C:\Users\fr0ze> npm config set python python2.7
PS C:\Users\fr0ze> npm install -g ironfish
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated cli-ux@4.9.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! code 1
npm ERR! path C:\Users\fr0ze\AppData\Roaming\npm\node_modules\ironfish\node_modules\segfault-handler
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.13.2 | win32 | x64
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Can't find Python executable "python2.7", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\fr0ze\AppData\Roaming\npm\node_modules\ironfish\node_modules\node-gyp\lib\configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\fr0ze\AppData\Roaming\npm\node_modules\ironfish\node_modules\node-gyp\lib\configure.js:509:16)
npm ERR! gyp ERR! stack     at callback (C:\Users\fr0ze\AppData\Roaming\npm\node_modules\ironfish\node_modules\graceful-fs\polyfills.js:299:20)
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\fr0ze\\AppData\\Roaming\\npm\\node_modules\\ironfish\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\fr0ze\AppData\Roaming\npm\node_modules\ironfish\node_modules\segfault-handler
npm ERR! gyp ERR! node -v v16.13.2
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fr0ze\AppData\Local\npm-cache\_logs\2022-03-16T18_29_02_401Z-debug-0.log

**Comment by Kupuyc** [comment]
python 2 must be installed and be in $PATH env variable.

**Comment by mat-if** [comment]
Ok one more, can you try `npm install -g ironfish --no-optional`? The python2 dependency looks like it _should_ be optional, so I'm hoping that this might work.

**Comment by QustomQure** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/43998465/158697330-85949a7a-248a-4c5d-98e1-cf6d3a53b346.png)

**Comment by QustomQure** [comment]
sadly, it is same

**Comment by QustomQure** [comment]
After totally removing python2.7 and reinstalling getting another error with node-gyp
[2022-03-16T22_01_44_540Z-debug-0.log](https://github.com/iron-fish/ironfish/files/8274753/2022-03-16T22_01_44_540Z-debug-0.log)
![Screenshot (4)](https://user-images.githubusercontent.com/43998465/158699481-b252eb78-f4e9-40e2-a324-104b0f4baadc.png)

**Comment by QustomQure** [comment]
i have latest node-gyp@9.0.0
npm version
{
  npm: '8.5.4',
  node: '16.13.2',
  v8: '9.4.146.24-node.14',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1l+quic',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}

**Comment by mat-if** [comment]
Ok, soon we're going to bump the version of sqlite3 to remove the Python2 dependency and use a more modern version of node-gyp, hopefully that will help move this forward for you. https://github.com/iron-fish/ironfish/pull/1142

**Comment by deekerno** [comment]
Does this issue still persist after the latest update?

**Comment by deekerno** [comment]
Closing due to inactivity. If you are still encountering this problem after updating to the newest version, feel free to re-open this issue.
