### ISSUE TITLE
[issue name]

### ISSUE THREAD

**Issue by Fcl69** [iron-fish/ironfish#1161]
### What happened?

it crashed

### Version

v1.22.17

### Debug output

```shell
$ yarn build && yarn start:js debug
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run debug

Iron Fish version       0.1.21 @ src
Iron Fish library       0.0.1 @ src
Operating system        Linux x64
CPU model               AMD Ryzen 9 3900 12-Core Processor
CPU threads             24
RAM total               125.71 GiB
Node version            v16.13.2
Telemetry enabled       false
Accounts head hash      000000000005e30a6682131c336115680b84682b6cb4e909c2b8b5494c066bd6
Accounts head in chain  true
Accounts head sequence  159372

Done in 0.95s.
```

### Relevant log output

```shell
Reorganizing chain from 00000...b172c (158341) for 00000...9b541 (158341) on prev 00000...c0d92 (158340)
Reorganized chain. blocks: 1, old: 00000...b172c (158341), new: 00000...c0d92 (158340), fork: 00000...c0d92 (158340)
Added block seq: 158360, hash: 00000...d628c, txs: 6, progress: 100.00%, time: 895.2ms
Added block seq: 158380, hash: 00000...a81f0, txs: 2, progress: 100.00%, time: 814.4ms
Reorganizing chain from 00000...3f409 (158383) for 00000...35e59 (158383) on prev 00000...029c9 (158382)
Reorganized chain. blocks: 1, old: 00000...3f409 (158383), new: 00000...029c9 (158382), fork: 00000...029c9 (158382)
/home/fcl/ironfish/ironfish/build/src/blockchain/blockchain.js:595
                    throw new Error(verification.reason);
                          ^

Error: Transaction expired
    at /home/fcl/ironfish/ironfish/build/src/blockchain/blockchain.js:595:27
    at async LevelupDatabase.withTransaction (/home/fcl/ironfish/ironfish/build/src/storage/database/database.js:39:28)
    at async Blockchain.newBlock (/home/fcl/ironfish/ironfish/build/src/blockchain/blockchain.js:545:16)
    at async MiningDirector.constructAndMineBlock (/home/fcl/ironfish/ironfish/build/src/mining/director.js:261:26)
    at async MiningDirector.constructAndMineBlockWithRetry (/home/fcl/ironfish/ironfish/build/src/mining/director.js:200:26)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Graffiti

Fcl

**Comment by QustomQure** [comment]
You should just update. Present version is 0.1.27 and yours 0.1.21

**Comment by deekerno** [comment]
Does this issue still persist after the latest update?

**Comment by Fcl69** [comment]
Hard to say. It’s updated, start working, but none blocks are mined yet as of now. So not sure.


V
