### ISSUE TITLE
Stratum error pool.ironfish.network

### ISSUE THREAD

**Issue by QustomQure** [iron-fish/ironfish#1166]
### What happened?

Miner suddenly gets errors. Then proceed work. It is working on pool pool.ironfish.network

### Version

v0.1.27

### Debug output

```shell
ironfish debug
Iron Fish version            0.1.27 @ f40f586
Iron Fish library            0.0.5 @ f40f586
Operating system             Windows_NT x64
CPU model(s)                 AMD Ryzen 9 5950X 16-Core Processor
CPU threads                  32
RAM total                    63.92 GiB
Node version                 v16.13.2
ironfish in PATH             true
Telemetry enabled            true
Accounts head hash           00000000001d5055cf20a8ee0e5bd045b8eed085dc9d3f059de189a62f943a4a
Accounts head in chain       true
Accounts head sequence       161480
```

### Relevant log output

```shell
SyntaxError: Unexpected token m in JSON at position 4
    at JSON.parse (<anonymous>)
    at StratumClient.onData (C:\Users\fr0ze\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:111:34)
    at Socket.<anonymous> (C:\Users\fr0ze\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:41:52)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23) (repeated 77 times)
Server sent mining.notify message
new work 00000000494cff9a3f4f473f91d116af7382c45e653facfeef85b8f43d9d6b64 9756 125.24 MH/s
Server sent mining.notify message
new work 00000000494cff9a3f4f473f91d116af7382c45e653facfeef85b8f43d9d6b64 9757 125.24 MH/s
Stratum Error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at StratumClient.onData (C:\Users\fr0ze\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:111:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Stratum Error SyntaxError: Unexpected number in JSON at position 1
    at JSON.parse (<anonymous>)
    at StratumClient.onData (C:\Users\fr0ze\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:111:34)
    at Socket.<anonymous> (C:\Users\fr0ze\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:41:52)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
Stratum Error SyntaxError: Unexpected token f in JSON at position 1
    at JSON.parse (<anonymous>)
    at StratumClient.onData (C:\Users\fr0ze\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:111:34)
    at Socket.<anonymous> (C:\Users\fr0ze\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:41:52)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
Stratum Error SyntaxError: Unexpected token c in JSON at position 3
    at JSON.parse (<anonymous>)
    at StratumClient.onData (C:\Users\fr0ze\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:111:34)
    at Socket.<anonymous> (C:\Users\fr0ze\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:41:52)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
Stratum Error SyntaxError: Unexpected token c in JSON at position 3
    at JSON.parse (<anonymous>)
    at StratumClient.onData (C:\Users\fr0ze\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:111:34)
    at Socket.<anonymous> (C:\Users\fr0ze\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:41:52)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23) (repeated 79 times)
Server sent mining.notify message
new work 00000000494cff9a3f4f473f91d116af7382c45e653facfeef85b8f43d9d6b64 9986 125.24 MH/s
Server sent mining.notify message
new work 00000000494cff9a3f4f473f91d116af7382c45e653facfeef85b8f43d9d6b64 9987 125.24 MH/s
Stratum Error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at StratumClient.onData (C:\Users\fr0ze\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:111:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Stratum Error SyntaxError: Unexpected token e in JSON at position 0
    at JSON.parse (<anonymous>)
    at StratumClient.onData (C:\Users\fr0ze\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:111:34)
    at Socket.<anonymous> (C:\Users\fr0ze\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:41:52)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
Stratum Error SyntaxError: Unexpected token f in JSON at position 1
    at JSON.parse (<anonymous>)
    at StratumClient.onData (C:\Users\fr0ze\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:111:34)
    at Socket.<anonymous> (C:\Users\fr0ze\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:41:52)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
Stratum Error SyntaxError: Unexpected token f in JSON at position 1
    at JSON.parse (<anonymous>)
    at StratumClient.onData (C:\Users\fr0ze\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:111:34)
    at Socket.<anonymous> (C:\Users\fr0ze\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:41:52)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
Stratum Error SyntaxError: Unexpected token f in JSON at position 1
    at JSON.parse (<anonymous>)
    at StratumClient.onData (C:\Users\fr0ze\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:111:34)
    at Socket.<anonymous> (C:\Users\fr0ze\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:41:52)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23) (repeated 153 times)
Server sent mining.notify message
new work 00000000494cff9a3f4f473f91d116af7382c45e653facfeef85b8f43d9d6b64 10418 122.39 MH/s
Server sent mining.notify message
```

### Graffiti

Qualia

**Comment by mat-if** [comment]
@QustomQure has this happened again lately? I'm not sure what was causing it, but I'm hoping that we might've fixed it since then with other bug fixes

**Comment by deekerno** [comment]
Closing due to inactivity. If you are still encountering this problem after updating to the newest version, feel free to re-open this issue.
