### ISSUE TITLE
`miner/submitBlock` returns error

### ISSUE THREAD

**Issue by terrancewong** [iron-fish/ironfish#1177]
### What happened?

Customized miner miner/submitBlock returns error

```
Error: Malformed request rejected
    at IpcAdapter.handleMalformedRequest (path/ironfish-0.1.27/ironfish/build/src/rpc/adapters/ipcAdapter.js:237:40)
    at IpcAdapter.onMessage (path/ironfish-0.1.27/ironfish/build/src/rpc/adapters/ipcAdapter.js:177:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
```

### Version

0.1.27

### Debug output

```shell
$ ironfish debug -v                                                                                                               
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version       0.1.27 @ src
Iron Fish library       0.0.5 @ src
Operating system        Linux x64
CPU model(s)            Intel(R) Xeon(R) CPU E5-2651 v2 @ 1.80GHz
CPU threads             48
RAM total               7.73 GiB
Node version            v16.13.1
ironfish in PATH        false
Telemetry enabled       false
```

### Relevant log output

```shell
// miner submitting mined block
>> {"type":"message","data":{"id":2,"type":"miner/submitBlock","data":{"header":{"sequence":170307,"previousBlockHash":"000000000014b666e0b5ef99a8a83d97a8b9bada3edf57b01171e21a5000080b","noteCommitment":{"commitment":"2d5b6f92d2736450227eab76cb4a46c23f3e1c371c8dea407537d40802bf0d6b","size":251846},"nullifierCommitment":{"commitment":"293f4cd9b08a6b9badc02ea04650e73f36853632ac93691dce86d4c9c5572aca","size":71324},"target":"00000000002c147a33d0a0185a80900c9b7c596a3e9f74e6afe656985c9b72a0","randomness":4507465063450628,"timestamp":1648296097121,"minersFee":"0000000077359400","graffiti":"62683973716f4371495233724446737443434377316700000000000000000000"},"transactions":["00000000000000000100000000000000006cca88ffffffff0000000088ed5c73a6ce8c4c3d6e78f96a4097dc257a256333cd17dea03ecfdd043ba81d30c25fea30bc9d57bc5ae726f936f88ba1d40d72722f757de728c3a7aac6349aca059d23920b3af6dd5f736aff80fea2a3238a1a1d771593f6a999325fc273e902c3fc4dd3fdd279c12e7dd280fb1414056d534b86361cc3734c34a907bd840268b26031b319dd8fc4b6ec7982f9c041b1fa03bcc8bf2a4f7d0df5ea41f52dbb045af6cb10ca212122043dc5028e4a18b6719ecfc3438f94aa3d4a5205c82534fab4889a59bfe2943182180aebb6450cb913a51e6404d1d671f6022c36529c20ec7c9d8df23e3b3998361c69b91ff01bf0ffc17991cf59ca0f0902ba40913848ad0f2a822fb7e79779116db1e78f6f20074efecc43d4dd3b41c6f223c60170218968d3267e8a096d359e8aac0a92a32f0ed7bf8a4e5a029eab715041f34928d580a251f8d501f3e41a24766e4b22dfcf1d2c01e6e31c0006c3854b0137ca4f480dc700dc6a60e24f67ab8bc8aa9e4a05b85dd6ea5fdc150e7a5806e48f0f634be9e0ce4265616e7374616c6b206e6f746520656e6372797074696f6e206d696e6572206b65793030303030303030303030303030303030303030303030303030303030303030303030303030303030303030301854421a4e203595a9cee82b69f7b0a0a879f3f6edb1e9e93bbe74702d06ab4123f9658eb28af448dba563f514211d2f3fb658a3323c2ab0699e867d74c8ea0b"],"previousBlockInfo":{"target":"00000000002c2501e1a408b7c6183cb626f6898d0c2fc82eecfe67465f058f2e","timestamp":1648296080844}}}}
// Node returns a new block template
<< {"type":"stream","data":{"id":1,"data":{"header":{"sequence":170307,"previousBlockHash":"000000000014b666e0b5ef99a8a83d97a8b9bada3edf57b01171e21a5000080b","noteCommitment":{"commitment":"2d5b6f92d2736450227eab76cb4a46c23f3e1c371c8dea407537d40802bf0d6b","size":251846},"nullifierCommitment":{"commitment":"293f4cd9b08a6b9badc02ea04650e73f36853632ac93691dce86d4c9c5572aca","size":71324},"target":"00000000002c097bf42b76e57d6e83b813dbf83c372724f22ec3533800db378f","randomness":0,"timestamp":1648296091133,"minersFee":"0000000077359400","graffiti":"62683973716f4371495233724446737443434377316700000000000000000000"},"transactions":["00000000000000000100000000000000006cca88ffffffff0000000088ed5c73a6ce8c4c3d6e78f96a4097dc257a256333cd17dea03ecfdd043ba81d30c25fea30bc9d57bc5ae726f936f88ba1d40d72722f757de728c3a7aac6349aca059d23920b3af6dd5f736aff80fea2a3238a1a1d771593f6a999325fc273e902c3fc4dd3fdd279c12e7dd280fb1414056d534b86361cc3734c34a907bd840268b26031b319dd8fc4b6ec7982f9c041b1fa03bcc8bf2a4f7d0df5ea41f52dbb045af6cb10ca212122043dc5028e4a18b6719ecfc3438f94aa3d4a5205c82534fab4889a59bfe2943182180aebb6450cb913a51e6404d1d671f6022c36529c20ec7c9d8df23e3b3998361c69b91ff01bf0ffc17991cf59ca0f0902ba40913848ad0f2a822fb7e79779116db1e78f6f20074efecc43d4dd3b41c6f223c60170218968d3267e8a096d359e8aac0a92a32f0ed7bf8a4e5a029eab715041f34928d580a251f8d501f3e41a24766e4b22dfcf1d2c01e6e31c0006c3854b0137ca4f480dc700dc6a60e24f67ab8bc8aa9e4a05b85dd6ea5fdc150e7a5806e48f0f634be9e0ce4265616e7374616c6b206e6f746520656e6372797074696f6e206d696e6572206b65793030303030303030303030303030303030303030303030303030303030303030303030303030303030303030301854421a4e203595a9cee82b69f7b0a0a879f3f6edb1e9e93bbe74702d06ab4123f9658eb28af448dba563f514211d2f3fb658a3323c2ab0699e867d74c8ea0b"],"previousBlockInfo":{"target":"00000000002c2501e1a408b7c6183cb626f6898d0c2fc82eecfe67465f058f2e","timestamp":1648296080844}}}}
// and an error message 
<< {"type":"message","data":{"id":2,"status":500,"data":{"code":"error","message":"Malformed request rejected","stack":"Error: Malformed request rejected\n    at IpcAdapter.handleMalformedRequest (path/ironfish-0.1.27/ironfish/build/src/rpc/adapters/ipcAdapter.js:237:40)\n    at IpcAdapter.onMessage (path/ironfish-0.1.27/ironfish/build/src/rpc/adapters/ipcAdapter.js:177:18)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}}}
```

### Graffiti

bh9sqoCqIR3rDFstCCCw1g

**Comment by terrancewong** [comment]
`0.1.28` also suffers
