### ISSUE TITLE
compilation does not work

### ISSUE THREAD

**Issue by VeCnAvEc** [iron-fish/ironfish#1212]
### What happened?

when starting the yarn installation, a compilation error occurs at the stage:
Compiling ironfish_rust v0.1.0 (/root/ironfish/ironfish-rust)
    Building [=======================> ] 170/172: ironfish_rust                                                                                                                                          

rustup version: 1.24.3,
rustc version: 1.58.1,
nodejs version: 16.14.2,
yarn version: 1.22.18

![Снимок экрана от 2022-04-12 12-57-04](https://user-images.githubusercontent.com/73776144/162910519-406c38c9-8b87-459d-867c-67e80843838a.png)
![Снимок экрана от 2022-04-12 12-57-02](https://user-images.githubusercontent.com/73776144/162910528-96081890-fcb5-432c-9614-68ab12574f7b.png)

### Debug output

```shell
error: could not compile `ironfish_rust`

Caused by:
  process didn't exit successfully: `rustc --crate-name ironfish_rust --edition=2018 /root/ironfish/ironfish-rust/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="default"' --cfg 'feature="native"' -C metadata=9d445b8afc0c5c2f -C extra-filename=-9d445b8afc0c5c2f --out-dir /root/ironfish/ironfish-rust-nodejs/target/release/deps -L dependency=/root/ironfish/ironfish-rust-nodejs/target/release/deps --extern bellman=/root/ironfish/ironfish-rust-nodejs/target/release/deps/libbellman-efa15fed484d3e25.rmeta --extern blake2b_simd=/root/ironfish/ironfish-rust-nodejs/target/release/deps/libblake2b_simd-fbdde115b15f01ec.rmeta --extern blake2s_simd=/root/ironfish/ironfish-rust-nodejs/target/release/deps/libblake2s_simd-b7e9fbf2ece5901d.rmeta --extern blake3=/root/ironfish/ironfish-rust-nodejs/target/release/deps/libblake3-19500af229e23af3.rmeta --extern byteorder=/root/ironfish/ironfish-rust-nodejs/target/release/deps/libbyteorder-7ae8727335a54567.rmeta --extern ff=/root/ironfish/ironfish-rust-nodejs/target/release/deps/libff-1d5f38a6a76f8769.rmeta --extern lazy_static=/root/ironfish/ironfish-rust-nodejs/target/release/deps/liblazy_static-5d57db6815621f76.rmeta --extern pairing=/root/ironfish/ironfish-rust-nodejs/target/release/deps/libpairing-9fc16772c1a3179f.rmeta --extern rand=/root/ironfish/ironfish-rust-nodejs/target/release/deps/librand-1a803b9720b01009.rmeta --extern crypto=/root/ironfish/ironfish-rust-nodejs/target/release/deps/libcrypto-9da53b491617d75a.rmeta --extern shrinkwraprs=/root/ironfish/ironfish-rust-nodejs/target/release/deps/libshrinkwraprs-3447476addbe6f26.so --extern bip39=/root/ironfish/ironfish-rust-nodejs/target/release/deps/libbip39-22e944a6d4f63580.rmeta --extern zcash_primitives=/root/ironfish/ironfish-rust-nodejs/target/release/deps/libzcash_primitives-e1bf2c166f10df9d.rmeta --extern zcash_proofs=/root/ironfish/ironfish-rust-nodejs/target/release/deps/libzcash_proofs-caad026493329871.rlib -L native=/root/ironfish/ironfish-rust-nodejs/target/release/build/blake3-13fa67d08a830a66/out -L native=/root/ironfish/ironfish-rust-nodejs/target/release/build/blake3-13fa67d08a830a66/out -L native=/root/ironfish/ironfish-rust-nodejs/target/release/build/rust-crypto-wasm-17212d7c4f565730/out` (signal: 9, SIGKILL: kill)
Internal Error: Command failed: cargo build --release
    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:902:15)
    at BuildCommand.<anonymous> (/root/ironfish/node_modules/@napi-rs/cli/scripts/index.js:12819:26)
    at Generator.next (<anonymous>)
    at /root/ironfish/node_modules/@napi-rs/cli/scripts/index.js:1678:71
    at new Promise (<anonymous>)
    at __awaiter$1 (/root/ironfish/node_modules/@napi-rs/cli/scripts/index.js:1674:12)
    at BuildCommand.execute (/root/ironfish/node_modules/@napi-rs/cli/scripts/index.js:12741:16)
    at BuildCommand.validateAndExecute (/root/ironfish/node_modules/@napi-rs/cli/scripts/index.js:204:37)
    at /root/ironfish/node_modules/@napi-rs/cli/scripts/index.js:1261:53
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### Graffiti

VECNAVEC

**Comment by jasonlarkin** [comment]
Getting same error at same spot, here are my specs:

~/ironfish$ lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	foca

rustup version: 
~/ironfish$ rustup --version
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.58.1 (db9d1b20b 2022-01-20)`

rustc version: 

~/ironfish$ rustc --version
rustc 1.58.1 (db9d1b20b 2022-01-20)

nodejs version: 

~/ironfish$ node --version
v16.15.0

yarn version: 

~/ironfish$ yarn --version
1.22.18

**Comment by wd021** [comment]
try `cargo clean`. is this still the case on latest version?

**Comment by jasonlarkin** [comment]
went into ironfish-rust, did cargo clean, pulled latest, still same issue with yarn install

```bash

git log
commit 4bc3765015cb4bcfbb9732def5ae36ff8dc9db23 (HEAD -> master, origin/master, origin/HEAD)
Merge: 49dd58e a2816b9
Author: Derek Guenther <derek@ironfish.network>
Date:   Wed May 18 15:29:47 2022 -0400

```

**Comment by lwisne** [comment]
Did this ever resolve for you?

**Comment by jasonlarkin** [comment]
No had the same issue with yarn as noted previously. Do you want me to pull the latest commit and try again? Something change that could have fixed?

**Comment by hughy** [comment]
We've made many changes to our Rust code since this issue was posted. I'm going to close this issue, but please open a new issue if you run into similar problems with the latest changes.
