### ISSUE TITLE
another node is using the database

### ISSUE THREAD

**Issue by weneve2** [iron-fish/ironfish#1334]
### What happened?

A bug happened!
when node crashed no reason and start again ,it threw a error
```
another node is using the database.........
```
then went that 

```
/opt/ironfish/ironfish/build/src/account/accounts.js:351
                        throw new Error('nullifierToNote mappings must have a corresponding noteToNullifier map');
                              ^

Error: nullifierToNote mappings must have a corresponding noteToNullifier map
    at /opt/ironfish/ironfish/build/src/account/accounts.js:351:31
    at async LevelupDatabase.withTransaction (/opt/ironfish/ironfish/build/src/storage/database/database.js:39:28)
    at async Accounts.removeTransaction (/opt/ironfish/ironfish/build/src/account/accounts.js:333:9)
    at async Accounts.expireTransactions (/opt/ironfish/ironfish/build/src/account/accounts.js:576:17)
    at async Accounts.eventLoop (/opt/ironfish/ironfish/build/src/account/accounts.js:156:9)
```

### Version

0.1.32 @ src

### Debug output

```shell
Iron Fish version            0.1.32 @ src
Iron Fish library            0.0.10 @ src
Operating system             Linux x64
CPU model(s)                 AMD EPYC 7282 16-Core Processor
CPU threads                  16
RAM total                    503.64 GiB
Node version                 v16.13.1
ironfish in PATH             true
Telemetry enabled            true
Accounts head hash           0000000000060e652e6016007b6e36b40aaaf7e4331c6dadbddcb2b1a5b5fe52
Accounts head in chain       true
Accounts head sequence       2089
```

### Relevant log output

```shell
/opt/ironfish/ironfish/build/src/account/accounts.js:351
                        throw new Error('nullifierToNote mappings must have a corresponding noteToNullifier map');
                              ^

Error: nullifierToNote mappings must have a corresponding noteToNullifier map
    at /opt/ironfish/ironfish/build/src/account/accounts.js:351:31
    at async LevelupDatabase.withTransaction (/opt/ironfish/ironfish/build/src/storage/database/database.js:39:28)
    at async Accounts.removeTransaction (/opt/ironfish/ironfish/build/src/account/accounts.js:333:9)
    at async Accounts.expireTransactions (/opt/ironfish/ironfish/build/src/account/accounts.js:576:17)
    at async Accounts.eventLoop (/opt/ironfish/ironfish/build/src/account/accounts.js:156:9)
```

### Graffiti

xiongmao1

**Comment by weneve2** [comment]
And reboot the server could not solve this error .....

**Comment by dguenther** [comment]
If you're not able to start up your node, you should be able to run `ironfish accounts:rescan --reset` to fix this, or `ironfish accounts:rescan --reset --local`. We're working to fix the bug that causes the error in the first place.

**Comment by weneve2** [comment]
> If you're not able to start up your node, you should be able to run `ironfish accounts:rescan --reset` to fix this, or `ironfish accounts:rescan --reset --local`. We're working to fix the bug that causes the error in the first place.

fine，solved。thx
