### ISSUE TITLE
Invalid WebSocket frame

### ISSUE THREAD

**Issue by weneve2** [iron-fish/ironfish#1336]
### What happened?

just appeared in the logs and crashed when it was running .

### Version

0.1.32 @ src

### Debug output

```shell
Iron Fish version            0.1.32 @ src
Iron Fish library            0.0.10 @ src
Operating system             Linux x64
CPU model(s)                 Intel(R) Xeon(R) CPU E5-2696 v3 @ 2.30GHz
CPU threads                  72
RAM total                    251.77 GiB
Node version                 v16.14.0
ironfish in PATH             true
Telemetry enabled            true
Accounts head hash           00000000000d14280872d51f9915fb257ad3bf72463e5bd3e4ebd311451df853
Accounts head in chain       true
Accounts head sequence       2411
```

### Relevant log output

```shell
node:events:498
      throw er; // Unhandled 'error' event
      ^

RangeError: Invalid WebSocket frame: RSV1 must be clear
    at Receiver.getInfo (/opt/ironfish/node_modules/ws/lib/receiver.js:184:14)
    at Receiver.startLoop (/opt/ironfish/node_modules/ws/lib/receiver.js:131:22)
    at Receiver._write (/opt/ironfish/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Receiver.Writable.write (node:internal/streams/writable:334:10)
    at Socket.socketOnData (/opt/ironfish/node_modules/ws/lib/websocket.js:920:35)
    at Socket.emit (node:events:520:28)
    at Socket.Readable.read (node:internal/streams/readable:527:10)
    at Socket.read (node:net:644:39)
Emitted 'error' event on WebSocket instance at:
    at Receiver.receiverOnError (/opt/ironfish/node_modules/ws/lib/websocket.js:826:13)
    at Receiver.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'WS_ERR_UNEXPECTED_RSV_1',
  [Symbol(status-code)]: 1002
}
```

### Graffiti

zack

**Comment by Shekelme** [comment]
The same in my logs:
```
Disconnecting inbound websocket connection because the node has max peers
node:events:505
      throw er; // Unhandled 'error' event
      ^

RangeError: Invalid WebSocket frame: RSV1 must be clear
    at Receiver.getInfo (/usr/lib/node_modules/ironfish/node_modules/ws/lib/receiver.js:184:14)
    at Receiver.startLoop (/usr/lib/node_modules/ironfish/node_modules/ws/lib/receiver.js:131:22)
    at Receiver._write (/usr/lib/node_modules/ironfish/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Receiver.Writable.write (node:internal/streams/writable:334:10)
    at Socket.socketOnData (/usr/lib/node_modules/ironfish/node_modules/ws/lib/websocket.js:920:35)
    at Socket.emit (node:events:527:28)
    at Socket.Readable.read (node:internal/streams/readable:527:10)
    at Socket.read (node:net:666:39)
Emitted 'error' event on WebSocket instance at:
    at Receiver.receiverOnError (/usr/lib/node_modules/ironfish/node_modules/ws/lib/websocket.js:826:13)
    at Receiver.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'WS_ERR_UNEXPECTED_RSV_1',
  [Symbol(status-code)]: 1002
}
```
A node can work for a day, or work for an hour, but it crashes from time to time.
I use NPM installation method, Node.js version v16.15.1

**Comment by holahula** [comment]
Closing due to staleness. If the issue persists in versions `1.0.0+` - please file a new issue
