### ISSUE TITLE
Transaction expired and can't check my balance

### ISSUE THREAD

**Issue by txuwdzu** [iron-fish/ironfish#1337]
### Description

#  sudo docker exec -it ironfish tail -n 1000 -f /root/.ironfish/log
Peer pFT1lt6 sent orphan 00000...08ce6 (2342), syncing orphan chain.
Peer HuBiQGw (yuivanoviwanov) sent orphan 00000...dbac2 (2343), syncing orphan chain.
Peer eR3rS8Q sent orphan 00000...eebe1 (2344), syncing orphan chain.
Peer pFT1lt6 sent orphan 00000...8539c (2345), syncing orphan chain.
Peer pFT1lt6 sent orphan 00000...75435 (2346), syncing orphan chain.
Peer Zk0fsd8 (SenseDigger) sent orphan 00000...3ea8c (2347), syncing orphan chain.
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652345942064,"reason":1,"sourceIdentity":"jUejEeGABeuKbcViwElru2JnJdMbEbrmoxCjPOWHzF8="}
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652346015995,"reason":1,"sourceIdentity":"ik5YUTLNHGiCP2NM3iGM5HD3awPd7nEyXlZ+HKQWHjU="}
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652346030297,"reason":1,"sourceIdentity":"uSttHuPzDsrVy+macPqJQYD1FNL8PtIblHnGp9AuymA="}
Peer pFT1lt6 sent orphan 00000...dfd03 (2348), syncing orphan chain.
Peer TItZJH6 sent orphan 00000...ad0ed (2349), syncing orphan chain.
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652346101968,"reason":1,"sourceIdentity":"OO/f4mD7Mt5jxSJrgbTOoX4RCk5Cilm88f+i6QAm/QY="}
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652346103953,"reason":1,"sourceIdentity":"6Snt9vDJQ10+xjnrM6N8Sm/dR1jyjVNvhZA8vp2qAVg="}
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652346121988,"reason":1,"sourceIdentity":"mggK2KHgvJCirDP48jhekBi2bFhgczLtDZaeHfCp9h8="}
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652346125447,"reason":1,"sourceIdentity":"u8tVMabhzkIq6Rsw++EMpHaFkxcWhDuMQevzHTSoEgk="}
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652346226912,"reason":1,"sourceIdentity":"WYtlG8K/hz3iyKk5V6P8ty0lwBla6a9dRyX2ghsFj2s="}
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652346238406,"reason":1,"sourceIdentity":"DnH6iVMqGt1D5ndlEUss7TPQrLiVoxf22ZTKWepvcHY="}
Peer xJ4d1j+ (kazannode) sent orphan 00000...cdaf5 (2350), syncing orphan chain.
Peer HuBiQGw (yuivanoviwanov) sent orphan 00000...ee4c3 (2350), syncing orphan chain.
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652346266912,"reason":1,"sourceIdentity":"mggK2KHgvJCirDP48jhekBi2bFhgczLtDZaeHfCp9h8="}
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652346292883,"reason":1,"sourceIdentity":"mggK2KHgvJCirDP48jhekBi2bFhgczLtDZaeHfCp9h8="}
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652346294121,"reason":1,"sourceIdentity":"hgC8Pw9rF5xAmkf9gEQefKT//hDUa4jI2cSpY9aLwFM="}
/usr/src/app/node_modules/@ironfish/sdk/build/src/blockchain/blockchain.js:605
                    throw new Error(verification.reason);
                          ^

Error: Transaction expired
    at /usr/src/app/node_modules/@ironfish/sdk/build/src/blockchain/blockchain.js:605:27
    at async LevelupDatabase.withTransaction (/usr/src/app/node_modules/@ironfish/sdk/build/src/storage/database/database.js:39:28)
    at async Blockchain.newBlock (/usr/src/app/node_modules/@ironfish/sdk/build/src/blockchain/blockchain.js:555:16)
    at async MiningManager.createNewBlockTemplate (/usr/src/app/node_modules/@ironfish/sdk/build/src/mining/manager.js:93:26)
    at async streamNewBlockTemplate (/usr/src/app/node_modules/@ironfish/sdk/build/src/rpc/routes/mining/blockTemplateStream.js:84:33)
###### 
# sudo docker exec -it ironfish ironfish accounts:balance
Error: No leaf found in tree n at index 0

**Comment by lwisne** [comment]
Do you still see this error?

**Comment by Itsmuv** [comment]
![1](https://github.com/iron-fish/ironfish/assets/152098791/dad6cdd9-c367-4788-93ac-916a7df2d931)

I have the same problem I don't know what to do?

**Comment by hughy** [comment]
Expired transactions can happen if your transaction wasn't broadcast to the network quickly enough. Coins from expired transactions are returned to your account, so you can try making the same transaction again.

Iron Fish transactions expire based on an "expiration sequence" specified when the transaction is created. That sequence is a block sequence in the chain. By default, your transactions will have an expiration sequence that is 15 blocks ahead of the head of the chain at the time that you create your transaction.
