### ISSUE TITLE
 throw new Error(verification.reason)

### ISSUE THREAD

**Issue by msa6867** [iron-fish/ironfish#1347]
### What happened?

Ironfish crashed on my processor while mining overnight.  Log sequence pasted below includes last normal log entry before error sequence:

Unfortunately I restarted ironfish before realizing I was suppose to run "debug", so I stopped and ran debug... I hope this did not cause a loss of relevant debug ouput

update: ironfish just crashed again with same error sequence... I am updating the head hash and head sequence to the debug output after the last crash

### Version

0.1.32

### Debug output

```shell
Iron Fish version            0.1.32 @ 1abccc9
Iron Fish library            0.0.10 @ 1abccc9
Operating system             Windows_NT x64
CPU model(s)                 AMD Ryzen 3 4300G with Radeon Graphics
CPU threads                  8
RAM total                    7.37 GiB
Node version                 v16.15.0
ironfish in PATH             true
Telemetry enabled            true
Accounts head hash           00000000000d715efee988c8c4b7a367465c461adc1cd262cdef1f85a7425b16
Accounts head in chain       true
Accounts head sequence       2811
```

### Relevant log output

```shell
Received non-buffer message {"type":0,"destinationIdentity":null,"disconnectUntil":1652328974994,"reason":1,"sourceIdentity":"xxcGmuQJnLFw5bfoc9a4RfHmxZdICPjA/kK7S3jGoQI="}
C:\Users\mark\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\blockchain\blockchain.js:605
                    throw new Error(verification.reason);
                          ^

Error: Transaction expired
    at C:\Users\mark\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\blockchain\blockchain.js:605:27
    at async LevelupDatabase.withTransaction (C:\Users\mark\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\storage\database\database.js:39:28)
    at async Blockchain.newBlock (C:\Users\mark\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\blockchain\blockchain.js:555:16)
    at async MiningManager.createNewBlockTemplate (C:\Users\mark\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\manager.js:93:26)
    at async streamNewBlockTemplate (C:\Users\mark\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\rpc\routes\mining\blockTemplateStream.js:84:33)
```

### Graffiti

msa6867

**Comment by lwisne** [comment]
We believe this is fixed now. Comment here if you're still experiencing this issue!
