### ISSUE TITLE
Error on transactions scan

### ISSUE THREAD

**Issue by devzorg** [iron-fish/ironfish#1363]
### What happened?

After update it shows this error (see relevant log)
We can fix it removing account folder from ironfish homedir and make accounts:rescan but after some time node shows this error again

### Version

0.1.33

### Relevant log output

```shell
Scanning for transactions for rad1k (ab56fd7)
WebSocket server started at :::9033
/usr/src/app/node_modules/@ironfish/sdk/build/src/account/accounts.js:351
                        throw new Error('nullifierToNote mappings must have a corresponding noteToNullifier map');
                              ^

Error: nullifierToNote mappings must have a corresponding noteToNullifier map
    at /usr/src/app/node_modules/@ironfish/sdk/build/src/account/accounts.js:351:31
    at async LevelupDatabase.withTransaction (/usr/src/app/node_modules/@ironfish/sdk/build/src/storage/database/database.js:39:28)
    at async Accounts.removeTransaction (/usr/src/app/node_modules/@ironfish/sdk/build/src/account/accounts.js:333:9)
    at async Accounts.expireTransactions (/usr/src/app/node_modules/@ironfish/sdk/build/src/account/accounts.js:576:17)
    at async Accounts.eventLoop (/usr/src/app/node_modules/@ironfish/sdk/build/src/account/accounts.js:156:9)
```

### Graffiti

rad1k

**Comment by Nitrooo** [comment]
I've had the same error on v0.1.32, so apparently it's not been introduced in v0.1.33.

**Comment by lwisne** [comment]
We believe this is resolved now. Let us know if you're still having issues!
