### ISSUE TITLE
Transaction expired cause my node stopped

### ISSUE THREAD

**Issue by hungpq12** [iron-fish/ironfish#1365]
### What happened?

I got an error while running a node and my node has stopped. My node can not start again. 

### Version

0.1.32

### Debug output

```shell
Iron Fish version            0.1.32 @ 1abccc9
Iron Fish library            0.0.10 @ 1abccc9
Operating system             Linux x64
CPU model(s)                 AMD Ryzen 9 5950X 16-Core Processor
CPU threads                  32
RAM total                    31.25 GiB
Node version                 v16.15.0
ironfish in PATH             true
Telemetry enabled            true
Accounts head hash           0000000000121e187b2883b06bbbb9293f2c8f18527856fc9df3a3368ff5eaad
Accounts head in chain       true
Accounts head sequence       3170
```

### Relevant log output

```shell
/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/blockchain/blockchain.js:605
                    throw new Error(verification.reason);
                          ^

Error: Transaction expired
    at /usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/blockchain/blockchain.js:605:27
    at async LevelupDatabase.withTransaction (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/storage/database/database.js:39:28)
    at async Blockchain.newBlock (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/blockchain/blockchain.js:555:16)
    at async MiningManager.createNewBlockTemplate (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/mining/manager.js:93:26)
    at async streamNewBlockTemplate (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/rpc/routes/mining/blockTemplateStream.js:84:33)
```

### Graffiti

hungpq0702

**Comment by i542873057** [comment]
the same issue with me ..

```
/git/ironfish/ironfish/build/src/blockchain/blockchain.js:605
                    throw new Error(verification.reason);
                          ^

Error: Transaction expired
    at /git/ironfish/ironfish/build/src/blockchain/blockchain.js:605:27
    at async LevelupDatabase.withTransaction (/git/ironfish/ironfish/build/src/storage/database/database.js:39:28)
    at async Blockchain.newBlock (/git/ironfish/ironfish/build/src/blockchain/blockchain.js:555:16)
    at async MiningManager.createNewBlockTemplate (/git/ironfish/ironfish/build/src/mining/manager.js:93:26)
    at async streamNewBlockTemplate (/git/ironfish/ironfish/build/src/rpc/routes/mining/blockTemplateStream.js:84:33)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by lwisne** [comment]
We think this is resolved now. Let us know if you don't see this to be the case!
