### ISSUE TITLE
Stratum Error SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by msa6867** [iron-fish/ironfish#1391]
### What happened?

While running miner in mining pool, got three consecutive error sequences as shown below.  Does not appear to have affected the node; just the miner

### Version

v0.1.32

### Debug output

```shell
Iron Fish version       0.1.32 @ 1abccc9
Iron Fish library       0.0.10 @ 1abccc9
Operating system        Windows_NT x64
CPU model(s)            AMD Ryzen 3 4300G with Radeon Graphics
CPU threads             8
RAM total               7.37 GiB
Node version            v16.15.0
ironfish in PATH        true
Telemetry enabled       true
```

### Relevant log output

```shell
Found share: 00000002c0c50f09 10957 8.02 MH/s
Stratum Error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at StratumClient.onData (C:\Users\mark\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:111:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Stratum Error SyntaxError: Unexpected token c in JSON at position 0
    at JSON.parse (<anonymous>)
    at StratumClient.onData (C:\Users\mark\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:111:34)
    at Socket.<anonymous> (C:\Users\mark\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:41:52)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
Stratum Error SyntaxError: Unexpected number in JSON at position 1
    at JSON.parse (<anonymous>)
    at StratumClient.onData (C:\Users\mark\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:111:34)
    at Socket.<anonymous> (C:\Users\mark\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:41:52)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
Stratum Error SyntaxError: Unexpected token i in JSON at position 0
    at JSON.parse (<anonymous>)
    at StratumClient.onData (C:\Users\mark\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:111:34)
    at Socket.<anonymous> (C:\Users\mark\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:41:52)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
Stratum Error SyntaxError: Unexpected token b in JSON at position 1
    at JSON.parse (<anonymous>)
    at StratumClient.onData (C:\Users\mark\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:111:34)
    at Socket.<anonymous> (C:\Users\mark\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:41:52)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
Stratum Error SyntaxError: Unexpected token b in JSON at position 1
    at JSON.parse (<anonymous>)
    at StratumClient.onData (C:\Users\mark\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:111:34)
    at Socket.<anonymous> (C:\Users\mark\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:41:52)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) (repeated 2 times)
Hashrate... - 20.08 MH/s (20085952)
```

### Graffiti

msa6867

**Comment by hughy** [comment]
This should be resolved by #1569 and #1609
