### ISSUE TITLE
`miner/submitBlock` error `Tried to connect to unmounted adapter`

### ISSUE THREAD

**Issue by terrancewong** [iron-fish/ironfish#1403]
### What happened?

miner submits block, node returns:
```
{
  "type": "error",
  "data": {
    "code": "error",
    "message": "Tried to connect to unmounted adapter",
    "stack": "Error: Tried to connect to unmounted adapter\n    at TcpAdapter.constructUnmountedAdapter (/home/th/ironfish/ironfish/ironfish/build/src/rpc/adapters/tcpAdapter.js:209:23)\n    at TcpAdapter.onClientData (/home/th/ironfish/ironfish/ironfish/build/src/rpc/adapters/tcpAdapter.js:119:44)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
  }
}
```

### Version

0.1.34

### Debug output

```shell
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version       0.1.34 @ src
Iron Fish library       0.0.12 @ src
Operating system        Linux x64
CPU model(s)            Intel(R) Xeon(R) CPU E3-1245 v6 @ 3.70GHz
CPU threads             8
RAM total               30.78 GiB
Node version            v16.13.1
ironfish in PATH        false
Telemetry enabled       true
```
```


### Relevant log output

_No response_

### Graffiti

bh9sqoCqIR3rDFstCCCw1g

**Comment by lwisne** [comment]
Have you seen this behavior in recent versions?

**Comment by holahula** [comment]
Closing due to staleness. If the issue persists in versions `1.0.0+` - please file a new issue
