### ISSUE TITLE
Error adding new block when running a node

### ISSUE THREAD

**Issue by garlicdevs** [iron-fish/ironfish#1413]
### What happened?

The following error occurs when starting a node

### Version

0.1.34

### Debug output

```shell
Version       0.1.34 @ src
Peer Agent    ironfish/0.1.34/src
Peer Port     9033
Bootstrap     test.bn1.ironfish.network
 
WebSocket server started at :::9033
Connected to the Iron Fish network
Peer O4QoQXU sent orphan 00000...88eb6 (7440), syncing orphan chain.
Error when adding new block 7440 from O4QoQXU: Error: Expected value not to be null
    at Function.isNotNull (/home/garlicdevs/ironfish/ironfish-0.1.34/ironfish/build/src/assert.js:23:19)
    at Syncer.startSync (/home/garlicdevs/ironfish/ironfish-0.1.34/ironfish/build/src/syncer.js:105:25)
    at Syncer.addBlock (/home/garlicdevs/ironfish/ironfish-0.1.34/ironfish/build/src/syncer.js:285:22)
    at async Syncer.addNewBlock (/home/garlicdevs/ironfish/ironfish-0.1.34/ironfish/build/src/syncer.js:311:34)
    at async PeerNetwork.onNewBlock (/home/garlicdevs/ironfish/ironfish-0.1.34/ironfish/build/src/network/peerNetwork.js:458:20)
    at async PeerNetwork.handleGossipMessage (/home/garlicdevs/ironfish/ironfish-0.1.34/ironfish/build/src/network/peerNetwork.js:296:22)
    at async PeerNetwork.handleMessage (/home/garlicdevs/ironfish/ironfish-0.1.34/ironfish/build/src/network/peerNetwork.js:280:13)
    at async Promise.all (index 0)
    at async Event.emitAsync (/home/garlicdevs/ironfish/ironfish-0.1.34/ironfish/build/src/event.js:64:9)
```

### Graffiti

garlicdevs

**Comment by lwisne** [comment]
Do you still see this bug?
