### ISSUE TITLE
pool stratum error

### ISSUE THREAD

**Issue by QustomQure** [iron-fish/ironfish#1438]
### What happened?

Stratum data somehow had null
![Screenshot (33)](https://user-images.githubusercontent.com/43998465/169024016-5238c5d1-8958-4c06-9ff8-598dd81e0a45.png)

### Version

0.1.34

### Debug output

```shell
PS C:\> ironfish debug
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version       0.1.34 @ e0f5e11
Iron Fish library       0.0.12 @ e0f5e11
Operating system        Windows_NT x64
CPU model(s)            AMD Ryzen 9 5950X 16-Core Processor
CPU threads             32
RAM total               63.92 GiB
Node version            v16.13.2
ironfish in PATH        true
Telemetry enabled       true
```

### Relevant log output

```shell
PS C:\Windows\System32> ironfish miners:start -p pool.ironfish.network -a 1e3c2ca8bba2e56e1a14b578f43abb08b6d28d8ac97a413a0c118efd2e39f1172d142568bc12f915414f16 -t 24
Starting to mine with public address: 1e3c2ca8bba2e56e1a14b578f43abb08b6d28d8ac97a413a0c118efd2e39f1172d142568bc12f915414f16 at pool 54.90.34.95:9034
Connecting to pool...
Successfully connected to pool
Listening to pool for new work
Waiting for graffiti from pool...
Stratum Error Error: Expected value not to be null
    at Function.isNotNull (C:\Users\fr0ze\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\assert.js:23:19)
    at MiningPoolMiner.newWork (C:\Users\fr0ze\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\poolMiner.js:71:25)
    at StratumClient.onData (C:\Users\fr0ze\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:144:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Waiting for graffiti from pool...
Found share: 0000000019788b67 6196 90.09 MH/s
```

### Graffiti

Qualia

**Comment by lwisne** [comment]
This was happening when we were having issues with the pool. Should be fixed now.
