### ISSUE TITLE
Stratum Error Error: Expected value not to be null

### ISSUE THREAD

**Issue by CooperNic** [iron-fish/ironfish#1447]
### What happened?

When I started _ironfish miners:start_ command the error message occurred:
Stratum Error Error: Expected value not to be null
    at Function.isNotNull (/usr/src/app/node_modules/@ironfish/sdk/build/src/assert.js:23:19)
    at MiningPoolMiner.newWork (/usr/src/app/node_modules/@ironfish/sdk/build/src/mining/poolMiner.js:71:25)
    at StratumClient.onData (/usr/src/app/node_modules/@ironfish/sdk/build/src/mining/stratum/stratumClient.js:144:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Waiting for graffiti from pool...

### Version

O.1.35

### Debug output

```shell
Iron Fish version       0.1.35 @ 4bc3765
Iron Fish library       0.0.13 @ 4bc3765
Operating system        Linux x64
CPU model(s)            AMD Ryzen 5 3600 6-Core Processor
CPU threads             12
RAM total               62.78 GiB
Node version            v16.13.0
ironfish in PATH        true
Telemetry enabled       true
```

### Relevant log output

```shell
~$ docker run --rm --tty --interactive --name iron_fish_miner --network host --volume $HOME/.ironfish:/root/.ironfish ghcr.io/iron-fish/ironfish:latest miners:start -p pool.ironfish.network -a ac1bf****
Starting to mine with public address: ac1bf**** at pool 54.90.34.95:9034
Connecting to pool...
Successfully connected to pool
Listening to pool for new work
Waiting for graffiti from pool...
Waiting for graffiti from pool...
Waiting for graffiti from pool...
Waiting for graffiti from pool...
Waiting for graffiti from pool...
Waiting for graffiti from pool...
Stratum Error Error: Expected value not to be null
    at Function.isNotNull (/usr/src/app/node_modules/@ironfish/sdk/build/src/assert.js:23:19)
    at MiningPoolMiner.newWork (/usr/src/app/node_modules/@ironfish/sdk/build/src/mining/poolMiner.js:71:25)
    at StratumClient.onData (/usr/src/app/node_modules/@ironfish/sdk/build/src/mining/stratum/stratumClient.js:144:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Waiting for graffiti from pool...
Hashrate... ⣽ 36.12 MH/s (36128152)
```

### Graffiti

Cooper

**Comment by lwisne** [comment]
This was a temporary error we were seeing during mining pool outages. Let us know if you're still seeing it!
