### ISSUE TITLE
[issue name] ming error

### ISSUE THREAD

**Issue by Zack995** [iron-fish/ironfish#1458]
### What happened?

i ming in pool info:

### Version

0.1.34

### Debug output

```shell
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version       0.1.34 @ e0f5e11
Iron Fish library       0.0.12 @ e0f5e11
Operating system        Linux x64
CPU model(s)            AMD Ryzen 7 3700X 8-Core Processor
CPU threads             12
RAM total               9.69 GiB
Node version            v16.13.0
ironfish in PATH        true
Telemetry enabled       true
```

### Relevant log output

```shell
Stratum Error SyntaxError: Unexpected token h in JSON at position 0
    at JSON.parse (&lt;anonymous&gt;)
    at StratumClient.onData (/usr/src/app/node_modules/@ironfish/sdk/build/src/mining/stratum/stratumClient.js:111:34)
    at Socket.&lt;anonymous&gt; (/usr/src/app/node_modules/@ironfish/sdk/build/src/mining/stratum/stratumClient.js:41:52)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
```

### Graffiti

bothshand

**Comment by lwisne** [comment]
this is likely a message that came from the pool availability issues. Should be fixed now.
