### ISSUE TITLE
"Expected value not to be null" when start node

### ISSUE THREAD

**Issue by ffteng46** [iron-fish/ironfish#1467]
### What happened?

when i execute ./ironfish start in the direction of ironfish/ironfish-cli/bin,the thread crashed immediately and give this error message.
The operating sequence is ./ironfish stop,then ./ironfish start. This crash happend after ./ironfish start.

### Version

0.1.35 

### Debug output

```shell
Iron Fish version            0.1.35 @ src
Iron Fish library            0.0.13 @ src
Operating system             Linux x64
CPU model(s)                 AMD EPYC 7542 32-Core Processor
CPU threads                  64
RAM total                    1003.90 GiB
Node version                 v16.15.0
ironfish in PATH             false
Telemetry enabled            false
Accounts head hash           69e263e931fa1a2a4b0437a8eff79ffb7a353b6384a7aeac9f90ac12ae4811ef
Accounts head in chain       true
Accounts head sequence       1
```

### Relevant log output

```shell
WebSocket server started at :::9033
/home/cephd/ironfish/ironfish/build/src/assert.js:23
            throw new Error(message || `Expected value not to be null`);
                  ^

Error: Chain processor head not found in chain: 0000000000002e08d23c72d18535426ce32a95b545cebb4c7f33198db2445bbd
    at Function.isNotNull (/home/cephd/ironfish/ironfish/build/src/assert.js:23:19)
    at ChainProcessor.update (/home/cephd/ironfish/ironfish/build/src/chainProcessor.js:54:25)
    at async MinedBlocksIndexer.updateHead (/home/cephd/ironfish/ironfish/build/src/indexers/minedBlocksIndexer.js:174:33)
    at async MinedBlocksIndexer.eventLoop (/home/cephd/ironfish/ironfish/build/src/indexers/minedBlocksIndexer.js:168:9)
```

### Graffiti

luol-tech-node9

**Comment by deekerno** [comment]
Does this issue still persist for you?
