### ISSUE TITLE
No peer found with identity ${identity}[

### ISSUE THREAD

**Issue by hbhdhxl** [iron-fish/ironfish#1471]
### What happened?

The node automatically stops running and becomes faulty.

### Version

ironfish/0.1.35 linux-x64 node-v16.14.0

### Relevant log output

```shell
Added block to fork seq: 14385, head-seq: 14385, hash: 00000...96794, head-hash: 00000...21ad0, work: 221205868102199179, head-work: 221205878578534446, work-diff: 10476335267
/disk/ironfish/ironfish/node_modules/@ironfish/sdk/build/src/network/peers/peerManager.js:461
        throw new Error(`No peer found with identity ${identity}`);
              ^

Error: No peer found with identity UDLL6kWsyqsfcxVYzCB9zzoo+1sJvX1VdDpBNPdYgzw=
    at PeerManager.getPeerOrThrow (/disk/ironfish/ironfish/node_modules/@ironfish/sdk/build/src/network/peers/peerManager.js:461:15)
    at PeerNetwork.onNewTransaction (/disk/ironfish/ironfish/node_modules/@ironfish/sdk/build/src/network/peerNetwork.js:494:50)
    at async PeerNetwork.handleGossipMessage (/disk/ironfish/ironfish/node_modules/@ironfish/sdk/build/src/network/peerNetwork.js:299:22)
    at async PeerNetwork.handleMessage (/disk/ironfish/ironfish/node_modules/@ironfish/sdk/build/src/network/peerNetwork.js:280:13)
    at async Promise.all (index 0)
    at async Event.emitAsync (/disk/ironfish/ironfish/node_modules/@ironfish/sdk/build/src/event.js:64:9)
```

### Graffiti

xjfk

**Comment by holahula** [comment]
Closing due to staleness. If the issue persists in versions `1.0.0+` - please file a new issue
