### ISSUE TITLE
[Crash] Crash when syncing

### ISSUE THREAD

**Issue by hairtail** [iron-fish/ironfish#1475]
### What happened?

Crash when syncing

### Version

0.1.35 @ src

### Debug output

```shell
Iron Fish version            0.1.35 @ src
Iron Fish library            0.0.13 @ src
Operating system             Linux x64
CPU model(s)                 AMD Ryzen Threadripper 3960X 24-Core Processor
CPU threads                  48
RAM total                    251.63 GiB
Node version                 v16.15.0
ironfish in PATH             false
Telemetry enabled            false
Accounts head hash
Accounts head in chain       false
Accounts head sequence       null
```

### Relevant log output

```shell
WebSocket server started at :::9033
/home/ps/iron/ironfish/ironfish/build/src/primitives/transaction.js:59
            this.transactionPosted = new rust_nodejs_1.TransactionPosted(this.transactionPostedSerialized);
                                     ^

Error: ProvingError
    at Transaction.takeReference (/home/ps/iron/ironfish/ironfish/build/src/primitives/transaction.js:59:38)
    at Transaction.withReference (/home/ps/iron/ironfish/ironfish/build/src/primitives/transaction.js:77:34)
    at Accounts.syncTransaction (/home/ps/iron/ironfish/ironfish/build/src/account/accounts.js:276:27)
    at /home/ps/iron/ironfish/ironfish/build/src/account/accounts.js:47:28
    at async Promise.all (index 0)
    at async Event.emitAsync (/home/ps/iron/ironfish/ironfish/build/src/event.js:64:9)
    at async ChainProcessor.add (/home/ps/iron/ironfish/ironfish/build/src/chainProcessor.js:37:9)
    at async ChainProcessor.update (/home/ps/iron/ironfish/ironfish/build/src/chainProcessor.js:80:13)
    at async Accounts.updateHead (/home/ps/iron/ironfish/ironfish/build/src/account/accounts.js:68:37)
    at async Accounts.eventLoop (/home/ps/iron/ironfish/ironfish/build/src/account/accounts.js:157:9) {
  code: 'GenericFailure'
}
```

### Graffiti

miningKing

**Comment by holahula** [comment]
Closing due to staleness. If the issue persists - please file a new issue
