### ISSUE TITLE
3 pool miner error types: 1) Stratum Error Error: read ECONNRESET, 2): Stratum Error SyntaxError: Unexpected end of JSON input, 3) Stratum Error SyntaxError: Unexpected number in JSON at position 1

### ISSUE THREAD

**Issue by crProductGuy** [iron-fish/ironfish#1489]
On Windows 11, ironfish v0.1.35  installed by npm method, 

3 different error messages below:  Sometime early morning PDT on Monday 23may

First error:  (only one of this type)

**Found share: 00000000061645ff 19820 52.27 MH/s
Stratum Error Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'**
}
Disconnected from pool unexpectedly. Reconnecting.
Failed to connect to pool at 54.90.34.95:9034, retrying...
Successfully connected to pool
Listening to pool for new work
Found share: 0000000005f178f5 19898 51.61 MH/s

---
second error message type:   (many of these and 3rd type below interspersed between successful mining shares)

Many of these errors below suddenly on a pool miner window that had been very stable for several days returning shares on official pool.
No changes on PC before these errors started.

Example error output: started overnight early AM hours of Monday 23 May.
Noticed many of these at 08:25 PDT on my 2nd Ryzen miner.

Still mining and finding shares now.

Stratum Error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at StratumClient.onData (C:\Users\Marktest2\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:111:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Stratum Error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at StratumClient.onData (C:\Users\Marktest2\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:111:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) (repeated 2 times)
Found share: 000000000292d1f3 22677 52.07 MH/s

---

Third error type:

Stratum Error SyntaxError: Unexpected number in JSON at position 1
    at JSON.parse (<anonymous>)
    at StratumClient.onData (C:\Users\Marktest2\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:111:34)
    at Socket.<anonymous> (C:\Users\Marktest2\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:41:52)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

**Comment by lwisne** [comment]
These were errors users were getting in one of our outage blips with the pool. Apologies.
