### ISSUE TITLE
Improper test teardown in \ironfish coverage testing

### ISSUE THREAD

**Issue by AmberKiso** [iron-fish/ironfish#1493]
### What happened?

Ran `yarn test:coverage:html` in \ironfish\ironfish after a clean boot, no node running.
WIndows 11 command prompt.

Everything passed (see output) but I get a new error/warning:

> A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks.

### Version

0.1.35

### Relevant log output

```shell
\ironfish\ironfish>yarn test:coverage:html -w 3
yarn run v1.22.18
$ tsc -b tsconfig.test.json && jest  --coverage --coverage-reporters html --testPathIgnorePatterns -w 3
 PASS   @ironfish/sdk  src/blockchain/blockchain.test.ts (41.304 s)
 PASS   @ironfish/sdk  src/strategy.test.slow.ts (25.616 s)
 PASS   @ironfish/sdk  src/account/accounts.test.slow.ts (68.414 s)
 PASS   @ironfish/sdk  src/primitives/transaction.test.slow.ts (13.059 s)
 PASS   @ironfish/sdk  src/mining/manager.test.slow.ts (16.438 s)
 PASS   @ironfish/sdk  src/genesis/genesis.test.slow.ts (13.235 s)
 PASS   @ironfish/sdk  src/sdk.test.ts (14.718 s)
 PASS   @ironfish/sdk  src/workerPool/tasks/createTransaction.test.slow.ts (9.23 s)
 PASS   @ironfish/sdk  src/rpc/routes/mining/blockTemplateStream.test.slow.ts (7.999 s)
 PASS   @ironfish/sdk  src/primitives/block.test.ts
 PASS   @ironfish/sdk  src/consensus/verifier.test.ts (8.706 s)
 PASS   @ironfish/sdk  src/workerPool/job.test.slow.ts (6.706 s)
 PASS   @ironfish/sdk  src/memPool/memPool.test.ts (6.131 s)
 PASS   @ironfish/sdk  src/rpc/routes/faucet/getFunds.test.ts
 PASS   @ironfish/sdk  src/indexers/minedBlocksIndexer.test.ts (5.685 s)
 PASS   @ironfish/sdk  src/rpc/routes/transactions/sendTransaction.test.ts
 PASS   @ironfish/sdk  src/workerPool/pool.test.ts
 PASS   @ironfish/sdk  src/workerPool/tasks/verifyTransaction.test.ts
 PASS   @ironfish/sdk  src/rpc/routes/node/getLogStream.test.ts
 PASS   @ironfish/sdk  src/rpc/routes/accounts/rescanAccount.test.ts
 PASS   @ironfish/sdk  src/syncer.test.ts
 PASS   @ironfish/sdk  src/account/accounts.test.ts
 PASS   @ironfish/sdk  src/rpc/routes/accounts/create.test.slow.ts
 PASS   @ironfish/sdk  src/rpc/adapters/ipcAdapter.test.ts
 PASS   @ironfish/sdk  src/storage/database.test.ts
 PASS   @ironfish/sdk  src/rpc/routes/config/setConfig.test.ts
 PASS   @ironfish/sdk  src/workerPool/tasks/getUnspentNotes.test.ts
 PASS   @ironfish/sdk  src/rpc/routes/chain/getChainInfo.test.ts
 PASS   @ironfish/sdk  src/workerPool/tasks/createMinersFee.test.ts
 PASS   @ironfish/sdk  src/rpc/routes/chain/getBlock.test.ts (7.053 s)
 PASS   @ironfish/sdk  src/rpc/routes/config/getConfig.test.ts (6.346 s)
 PASS   @ironfish/sdk  src/merkletree/merkletree.test.ts
 PASS   @ironfish/sdk  src/chainProcessor.test.ts
 PASS   @ironfish/sdk  src/primitives/blockheader.test.ts
 PASS   @ironfish/sdk  src/rpc/routes/node/getStatus.test.ts
 PASS   @ironfish/sdk  src/network/peers/peerManager.test.ts
 PASS   @ironfish/sdk  src/network/peers/peer.test.ts
 PASS   @ironfish/sdk  src/rpc/routes/accounts/getPublicKey.test.ts
 PASS   @ironfish/sdk  src/rpc/routes/workers/getStatus.test.ts
 PASS   @ironfish/sdk  src/utils/blockutil.test.ts
 PASS   @ironfish/sdk  src/network/peerNetwork.test.ts
 PASS   @ironfish/sdk  src/telemetry/telemetry.test.ts
 PASS   @ironfish/sdk  src/rpc/routes/node/stopNode.test.ts
 PASS   @ironfish/sdk  src/network/peers/localPeer.test.ts
 PASS   @ironfish/sdk  src/network/peers/peerConnectionManager.test.ts
 PASS   @ironfish/sdk  src/strategy.test.ts
 PASS   @ironfish/sdk  src/rpc/routes/accounts/utils.test.ts (5.637 s)
 PASS   @ironfish/sdk  src/account/database/accounts.test.ts
 PASS   @ironfish/sdk  src/mining/manager.test.ts
 PASS   @ironfish/sdk  src/workerPool/tasks/unboxMessage.test.ts
 PASS   @ironfish/sdk  src/network/peers/connections/webRtcConnection.test.ts
 PASS   @ironfish/sdk  src/workerPool/tasks/sleep.test.ts
 PASS   @ironfish/sdk  src/merkletree/database/leaves.test.ts
 PASS   @ironfish/sdk  src/network/messages/disconnecting.test.ts
 PASS   @ironfish/sdk  src/network/peers/connections/webSocketConnection.test.ts
 PASS   @ironfish/sdk  src/merkletree/database/nodes.test.ts
 PASS   @ironfish/sdk  src/account/database/noteToNullifiers.test.ts
 PASS   @ironfish/sdk  src/logger/reporters/console.test.ts
 PASS   @ironfish/sdk  src/network/peers/addressManager.test.ts
 PASS   @ironfish/sdk  src/workerPool/tasks/boxMessage.test.ts
 PASS   @ironfish/sdk  src/network/testUtilities/mockIdentity.test.ts
 PASS   @ironfish/sdk  src/indexers/database/accountsToRemove.test.ts
 PASS   @ironfish/sdk  src/index.test.ts
 PASS   @ironfish/sdk  src/network/messages/getBlockHashes.test.ts
 PASS   @ironfish/sdk  src/network/messages/newBlock.test.ts
 PASS   @ironfish/sdk  src/network/messages/getBlocks.test.ts
 PASS   @ironfish/sdk  src/primitives/nullifier.test.ts
 PASS   @ironfish/sdk  src/network/messages/peerListRequest.test.ts (5.074 s)
 PASS   @ironfish/sdk  src/utils/json.test.ts
 PASS   @ironfish/sdk  src/utils/file.test.ts
 PASS   @ironfish/sdk  src/workerPool/tasks/submitTelemetry.test.ts
 PASS   @ironfish/sdk  src/account/validator.test.ts
 PASS   @ironfish/sdk  src/utils/math.test.ts
 PASS   @ironfish/sdk  src/primitives/target.test.ts
 PASS   @ironfish/sdk  src/network/messages/signal.test.ts
 PASS   @ironfish/sdk  src/account/database/meta.test.ts
 PASS   @ironfish/sdk  src/network/messages/newTransaction.test.ts
 PASS   @ironfish/sdk  src/network/messages/identify.test.ts
 PASS   @ironfish/sdk  src/network/utils/parseUrl.test.ts
 PASS   @ironfish/sdk  src/network/messageRegistry.test.ts
 PASS   @ironfish/sdk  src/account/database/transactions.test.ts
 PASS   @ironfish/sdk  src/utils/bigint.test.ts
 PASS   @ironfish/sdk  src/indexers/database/sequenceToHashes.test.ts
 PASS   @ironfish/sdk  src/utils/currency.test.ts
 PASS   @ironfish/sdk  src/serde/iJson.test.ts
 PASS   @ironfish/sdk  src/serde/Uint8ArraySerde.test.ts
 PASS   @ironfish/sdk  src/indexers/database/meta.test.ts
 PASS   @ironfish/sdk  src/testUtilities/utils.test.ts
 PASS   @ironfish/sdk  src/metrics/rollingAverage.test.ts
 PASS   @ironfish/sdk  src/logger/logLevelParser.test.ts
 PASS   @ironfish/sdk  src/event.test.ts
 PASS   @ironfish/sdk  src/network/messages/signalRequest.test.ts
 PASS   @ironfish/sdk  src/network/messages/cannotSatisfyRequest.test.ts
 PASS   @ironfish/sdk  src/network/messages/peerList.test.ts
 PASS   @ironfish/sdk  src/indexers/database/minedBlock.test.ts (5.006 s)
 PASS   @ironfish/sdk  src/blockchain/blockchain.test.perf.ts (266.422 s)
  ● Console

    console.log
      Creating Blocks 0

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 1

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 2

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 3

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 4

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 5

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 6

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 7

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 8

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 9

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 10

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 11

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 12

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 13

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 14

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 15

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 16

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 17

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 18

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 19

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 20

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 21

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 22

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 23

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 24

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 25

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 26

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 27

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 28

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 29

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 30

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 31

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 32

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 33

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 34

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 35

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 36

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 37

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 38

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 39

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 40

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 41

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 42

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 43

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 44

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 45

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 46

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 47

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 48

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 49

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 50

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 51

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 52

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 53

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 54

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 55

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 56

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 57

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 58

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 59

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 60

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 61

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 62

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 63

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 64

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 65

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 66

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 67

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 68

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 69

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 70

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 71

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 72

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 73

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 74

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 75

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 76

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 77

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 78

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 79

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 80

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 81

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 82

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 83

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 84

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 85

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 86

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 87

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 88

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 89

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 90

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 91

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 92

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 93

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 94

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 95

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 96

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 97

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 98

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Creating Blocks 99

      at Object.<anonymous> (src/blockchain/blockchain.test.perf.ts:32:15)

    console.log
      Running Test 0

      at runTest (src/blockchain/blockchain.test.perf.ts:87:17)

    console.log
      Running Test 1

      at runTest (src/blockchain/blockchain.test.perf.ts:87:17)

    console.log
      Running Test 2

      at runTest (src/blockchain/blockchain.test.perf.ts:87:17)

    console.log
      Running Test 3

      at runTest (src/blockchain/blockchain.test.perf.ts:87:17)

    console.log
      Running Test 4

      at runTest (src/blockchain/blockchain.test.perf.ts:87:17)

    console.log
      [TEST RESULTS: Times Ran: 5, Fork Length: 1]
      Total Test Average: 48.40ms
      Insert 0 blocks linear: 0.00ms
      Insert 0 blocks on fork: 0.00ms
      Add head rewind fork blocks: 48.40ms

      at printResults (src/blockchain/blockchain.test.perf.ts:139:15)

    console.log
      Running Test 0

      at runTest (src/blockchain/blockchain.test.perf.ts:87:17)

    console.log
      Running Test 1

      at runTest (src/blockchain/blockchain.test.perf.ts:87:17)

    console.log
      Running Test 2

      at runTest (src/blockchain/blockchain.test.perf.ts:87:17)

    console.log
      Running Test 3

      at runTest (src/blockchain/blockchain.test.perf.ts:87:17)

    console.log
      Running Test 4

      at runTest (src/blockchain/blockchain.test.perf.ts:87:17)

    console.log
      [TEST RESULTS: Times Ran: 5, Fork Length: 3]
      Total Test Average: 548.20ms
      Insert 2 blocks linear: 114.20ms
      Insert 2 blocks on fork: 66.80ms
      Add head rewind fork blocks: 186.20ms

      at printResults (src/blockchain/blockchain.test.perf.ts:139:15)

    console.log
      Running Test 0

      at runTest (src/blockchain/blockchain.test.perf.ts:87:17)

    console.log
      Running Test 1

      at runTest (src/blockchain/blockchain.test.perf.ts:87:17)

    console.log
      Running Test 2

      at runTest (src/blockchain/blockchain.test.perf.ts:87:17)

    console.log
      Running Test 3

      at runTest (src/blockchain/blockchain.test.perf.ts:87:17)

    console.log
      Running Test 4

      at runTest (src/blockchain/blockchain.test.perf.ts:87:17)

    console.log
      [TEST RESULTS: Times Ran: 5, Fork Length: 5]
      Total Test Average: 1092.00ms
      Insert 4 blocks linear: 89.95ms
      Insert 4 blocks on fork: 68.50ms
      Add head rewind fork blocks: 458.20ms

      at printResults (src/blockchain/blockchain.test.perf.ts:139:15)

    console.log
      Running Test 0

      at runTest (src/blockchain/blockchain.test.perf.ts:87:17)

    console.log
      Running Test 1

      at runTest (src/blockchain/blockchain.test.perf.ts:87:17)

    console.log
      Running Test 2

      at runTest (src/blockchain/blockchain.test.perf.ts:87:17)

    console.log
      Running Test 3

      at runTest (src/blockchain/blockchain.test.perf.ts:87:17)

    console.log
      Running Test 4

      at runTest (src/blockchain/blockchain.test.perf.ts:87:17)

    console.log
      [TEST RESULTS: Times Ran: 5, Fork Length: 10]
      Total Test Average: 3739.20ms
      Insert 9 blocks linear: 199.02ms
      Insert 9 blocks on fork: 109.73ms
      Add head rewind fork blocks: 958.40ms

      at printResults (src/blockchain/blockchain.test.perf.ts:139:15)

    console.log
      Running Test 0

      at runTest (src/blockchain/blockchain.test.perf.ts:87:17)

    console.log
      Running Test 1

      at runTest (src/blockchain/blockchain.test.perf.ts:87:17)

    console.log
      Running Test 2

      at runTest (src/blockchain/blockchain.test.perf.ts:87:17)

    console.log
      Running Test 3

      at runTest (src/blockchain/blockchain.test.perf.ts:87:17)

    console.log
      Running Test 4

      at runTest (src/blockchain/blockchain.test.perf.ts:87:17)

    console.log
      [TEST RESULTS: Times Ran: 5, Fork Length: 50]
      Total Test Average: 12471.40ms
      Insert 49 blocks linear: 133.64ms
      Insert 49 blocks on fork: 69.69ms
      Add head rewind fork blocks: 2508.00ms

      at printResults (src/blockchain/blockchain.test.perf.ts:139:15)

    console.log
      Running Test 0

      at runTest (src/blockchain/blockchain.test.perf.ts:87:17)

    console.log
      Running Test 1

      at runTest (src/blockchain/blockchain.test.perf.ts:87:17)

    console.log
      Running Test 2

      at runTest (src/blockchain/blockchain.test.perf.ts:87:17)

    console.log
      Running Test 3

      at runTest (src/blockchain/blockchain.test.perf.ts:87:17)

    console.log
      Running Test 4

      at runTest (src/blockchain/blockchain.test.perf.ts:87:17)

    console.log
      [TEST RESULTS: Times Ran: 5, Fork Length: 100]
      Total Test Average: 20985.20ms
      Insert 99 blocks linear: 100.06ms
      Insert 99 blocks on fork: 63.64ms
      Add head rewind fork blocks: 4779.00ms

      at printResults (src/blockchain/blockchain.test.perf.ts:139:15)

A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks.

Test Suites: 96 passed, 96 total
Tests:       545 passed, 545 total
Snapshots:   23 passed, 23 total
Time:        269.936 s
Ran all test suites.
Done in 276.73s.
```

### Graffiti

Here fishie fishie fishie!!!

**Comment by lwisne** [comment]
This appears to be working now. Let us know if you still see the issue.
