### ISSUE TITLE
I use docker to install pool and report errors during operation. I hope I can get help

### ISSUE THREAD

**Issue by ytQiao** [iron-fish/ironfish#1512]
### Description

I use docker to install pool, connect node through RPC, and then report an error during operation

Here are my steps
1. Start node
```
docker run -itd --name node -p 8001:8001 --volume /root/.ironfish:/root/.ironfish ghcr.io/iron-fish/ironfish:latest start --rpc.tcp --rpc.tcp.host=0.0.0.0 --rpc.tcp.port=8001
```
2. Start pool
```
docker run -itd --name pool -p 9034:9034  ghcr.io/iron-fish/ironfish:latest miners:pools:start --rpc.tcp --rpc.tcp.host=172.8.1.15 --rpc.tcp.port=8001 -d 'https://discord.com/api/webhooks/979310813179432960/CfqmMa03s3UcejgRgy5hmeY5fEoljddha-Xjo0Ta6Gk3g2tOuBj1HoY7hTcaFiCsahd8'
```

Error content
```
Setting work for request: 96 0000000000000000665900000000000000000000000521bffc...
Setting work for request: 97 0000000000000000675900000000000000000000000b4f9bbb...
/usr/src/app/node_modules/@ironfish/sdk/build/src/rpc/clients/ipcClient.js:98
                    pending.reject(new errors_1.RequestError(pending.response, errorBody.code, errorBody.message, errorBody.stack));
                                   ^

<ref *1> RequestError: Request failed (404) route-not-found: No route found account/getBalance in namespace account for method getBalance
    at IronfishIpcClient.handleEnd (/usr/src/app/node_modules/@ironfish/sdk/build/src/rpc/clients/ipcClient.js:98:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  response: Response {
    status: 404,
    content: null,
    promise: Promise { <rejected> [Circular *1] },
    stream: Stream { buffer: [], waiting: [], closed: true },
    timeout: null
  },
  status: 404,
  code: 'route-not-found',
  codeMessage: 'No route found account/getBalance in namespace account for method getBalance',
  codeStack: 'Error: No route found account/getBalance in namespace account for method getBalance\n' +
    '    at Router.route (/usr/src/app/node_modules/@ironfish/sdk/build/src/rpc/routes/router.js:61:19)\n' +
    '    at IpcAdapter.onMessage (/usr/src/app/node_modules/@ironfish/sdk/build/src/rpc/adapters/ipcAdapter.js:194:26)\n' +
    '    at runMicrotasks (<anonymous>)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
}
```

How can I deal with this problem?

**Comment by lwisne** [comment]
The `account` commands are not available via RPC by default. To enable, use `ironfish config:set rpcTcpSecure true`
