### ISSUE TITLE
[issue name]Stratum Error SyntaxError: Unexpected end of JSON input at JSON.parse (<anonymous>)

### ISSUE THREAD

**Issue by crProductGuy** [iron-fish/ironfish#1524]
### What happened?

Env: Win11 Home, IF 0.1.35 installed via npm.   

Was connected to main IF pool and pool-mining OK for a few days, earning shares.
 Had a disconnections which self-repaired on Thurs 5/26 and pool mining & finding shares continued.

Sometime overnight or early morning on Friday 27 may, saw a bunch of these errors:

First:
```Stratum Error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at StratumClient.onData (C:\Users\Marktest2\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:111:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)```


a few of those, then found some shares again - 4x

Then more errors, including "Unexpected token d " or similar:


```Stratum Error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at StratumClient.onData (C:\Users\Marktest2\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:111:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Stratum Error SyntaxError: Unexpected token d in JSON at position 5
    at JSON.parse (<anonymous>)
    at StratumClient.onData (C:\Users\Marktest2\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:111:34)
    at Socket.<anonymous> (C:\Users\Marktest2\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\mining\stratum\stratumClient.js:41:52)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)```

Then it continued:

Found share: 0000000002a54586 232 54.12 MH/s

later it disconnected from the pool and would not reconnect properly; got 0 Hashrate:

```Found share: 000000001920ddd8 284 53.02 MH/s
Disconnected from pool unexpectedly. Reconnecting.
Failed to connect to pool at 54.90.34.95:9034, retrying...
Successfully connected to pool
Listening to pool for new work
Hashrate... / 0 H/s (0) ```


### Version

0.1.35

### Debug output

```shell
c:\users\marktest2\source\repos\ironfish\ironfish-cli>ironfish debug
Iron Fish version            0.1.35 @ 4bc3765
Iron Fish library            0.0.13 @ 4bc3765
Operating system             Windows_NT x64
CPU model(s)                 AMD Ryzen 7 5700G with Radeon Graphics
CPU threads                  16
RAM total                    31.34 GiB
Node version                 v16.15.0
ironfish in PATH             true
Telemetry enabled            true
Accounts head hash
Accounts head in chain       false
Accounts head sequence       null
```

### Relevant log output

```shell
See above
```

### Graffiti

ProductGuy

**Comment by chenzongxiong** [comment]
any updates about this issue?
or any other version for working around?
