### ISSUE TITLE
After Server Reboot !

### ISSUE THREAD

**Issue by Masternode24** [iron-fish/ironfish#1528]
### What happened?

```
May 28 01:29:35 Ubuntu-2004-focal-64-minimal-hwe yarn[3597]: $ yarn build && yarn start:js start
May 28 01:29:35 Ubuntu-2004-focal-64-minimal-hwe yarn[3609]: $ tsc -b
May 28 01:29:35 Ubuntu-2004-focal-64-minimal-hwe yarn[3628]: $ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run start
May 28 01:29:35 Ubuntu-2004-focal-64-minimal-hwe yarn[3647]:                                            
May 28 01:29:35 Ubuntu-2004-focal-64-minimal-hwe yarn[3647]: ::::::::::          :::::::::::::::::
May 28 01:29:35 Ubuntu-2004-focal-64-minimal-hwe yarn[3647]: ::::::::::::       :::::::::::::::::::
May 28 01:29:35 Ubuntu-2004-focal-64-minimal-hwe yarn[3647]: :::::::::::::     :::::::::::::::::::::
May 28 01:29:35 Ubuntu-2004-focal-64-minimal-hwe yarn[3647]: ::::::::::::::   ::::::::::::::::::::::::
May 28 01:29:35 Ubuntu-2004-focal-64-minimal-hwe yarn[3647]:  ::::::::::::: ::::::::::        :::::::::
May 28 01:29:35 Ubuntu-2004-focal-64-minimal-hwe yarn[3647]:    :::::::::::::::::::::          ::::::::::
May 28 01:29:35 Ubuntu-2004-focal-64-minimal-hwe yarn[3647]:    :::::::::::::::::::::          :::::::::
May 28 01:29:35 Ubuntu-2004-focal-64-minimal-hwe yarn[3647]:  ::::::::::::: ::::::::::        :::::::::
May 28 01:29:35 Ubuntu-2004-focal-64-minimal-hwe yarn[3647]: ::::::::::::::   ::::::::::::::::::::::::
May 28 01:29:35 Ubuntu-2004-focal-64-minimal-hwe yarn[3647]: :::::::::::::     :::::::::::::::::::::
May 28 01:29:35 Ubuntu-2004-focal-64-minimal-hwe yarn[3647]: ::::::::::::       :::::::::::::::::::
May 28 01:29:35 Ubuntu-2004-focal-64-minimal-hwe yarn[3647]: ::::::::::           ::::::::::::::::
May 28 01:29:35 Ubuntu-2004-focal-64-minimal-hwe yarn[3647]: Version       0.1.35 @ src
May 28 01:29:35 Ubuntu-2004-focal-64-minimal-hwe yarn[3647]: Node Name     Masternode24.de
May 28 01:29:35 Ubuntu-2004-focal-64-minimal-hwe yarn[3647]: Graffiti      Masternode24.de
May 28 01:29:35 Ubuntu-2004-focal-64-minimal-hwe yarn[3647]: Peer Identity YfP7GF9b+zUDLIQg48MoiAl+7oZ2tSvm5frMNQCNjWw=
May 28 01:29:35 Ubuntu-2004-focal-64-minimal-hwe yarn[3647]: Peer Agent    ironfish/0.1.35/src
May 28 01:29:35 Ubuntu-2004-focal-64-minimal-hwe yarn[3647]: Peer Port     9033
May 28 01:29:35 Ubuntu-2004-focal-64-minimal-hwe yarn[3647]: Bootstrap     test.bn1.ironfish.network
May 28 01:29:35 Ubuntu-2004-focal-64-minimal-hwe yarn[3647]:  
May 28 01:29:36 Ubuntu-2004-focal-64-minimal-hwe yarn[3647]: WebSocket server started at :::9033
May 28 01:29:36 Ubuntu-2004-focal-64-minimal-hwe yarn[3647]: /root/ironfish/ironfish/build/src/assert.js:23
May 28 01:29:36 Ubuntu-2004-focal-64-minimal-hwe yarn[3647]:             throw new Error(message || `Expected value not to be null`);
May 28 01:29:36 Ubuntu-2004-focal-64-minimal-hwe yarn[3647]:                   ^
May 28 01:29:36 Ubuntu-2004-focal-64-minimal-hwe yarn[3647]: Error: Chain processor head not found in chain: 00000000000ce91d0d69b3c42293710a7cd047c40a35eff280f949a39258bf65
May 28 01:29:36 Ubuntu-2004-focal-64-minimal-hwe yarn[3647]:     at Function.isNotNull (/root/ironfish/ironfish/build/src/assert.js:23:19)
May 28 01:29:36 Ubuntu-2004-focal-64-minimal-hwe yarn[3647]:     at ChainProcessor.update (/root/ironfish/ironfish/build/src/chainProcessor.js:54:25)
May 28 01:29:36 Ubuntu-2004-focal-64-minimal-hwe yarn[3647]:     at async MinedBlocksIndexer.updateHead (/root/ironfish/ironfish/build/src/indexers/minedBlocksIndexer.js:174:33)
May 28 01:29:36 Ubuntu-2004-focal-64-minimal-hwe yarn[3647]:     at async MinedBlocksIndexer.eventLoop (/root/ironfish/ironfish/build/src/indexers/minedBlocksIndexer.js:168:9)
May 28 01:29:36 Ubuntu-2004-focal-64-minimal-hwe yarn[3628]: error Command failed with exit code 1.
May 28 01:29:36 Ubuntu-2004-focal-64-minimal-hwe yarn[3628]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
May 28 01:29:36 Ubuntu-2004-focal-64-minimal-hwe yarn[3597]: error Command failed with exit code 1.
May 28 01:29:36 Ubuntu-2004-focal-64-minimal-hwe yarn[3597]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
May 28 01:29:36 Ubuntu-2004-focal-64-minimal-hwe systemd[1]: ironfishd.service: Main process exited, code=exited, status=1/FAILURE
May 28 01:29:36 Ubuntu-2004-focal-64-minimal-hwe systemd[1]: ironfishd.service: Failed with result 'exit-code'.
```

### Version

0.35

### Graffiti

Masternode24.de

**Comment by lwisne** [comment]
We believe this bug to be resolved now. Let us know if that's not the case on your end.
