### ISSUE TITLE
[issue name]

### ISSUE THREAD

**Issue by SunnyBoy00l** [iron-fish/ironfish#1611]
### What happened?

A bug happened!

### Relevant log output

```shell
There was an error with the transaction <ref *1> RequestError: Request failed (400) error: InvalidPaymentAddress
    at IronfishIpcClient.IronfishRpcClient.handleEnd (/usr/src/app/node_modules/@ironfish/sdk/build/src/rpc/clients/rpcClient.js:44:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  response: Response {
    status: 400,
    content: null,
    promise: Promise { <rejected> [Circular *1] },
    stream: Stream { buffer: [], waiting: [], closed: true },
    timeout: null
  },
  status: 400,
  code: 'error',
  codeMessage: 'InvalidPaymentAddress',
  codeStack: 'Error: InvalidPaymentAddress\n' +
    '    at CreateTransactionTask.execute (/usr/src/app/node_modules/@ironfish/sdk/build/src/workerPool/tasks/createTransaction.js:157:26)\n' +
    '    at Object.handleRequest (/usr/src/app/node_modules/@ironfish/sdk/build/src/workerPool/tasks/handlers.js:30:20)\n' +
    '    at Job.execute (/usr/src/app/node_modules/@ironfish/sdk/build/src/workerPool/job.js:58:25)\n' +
    '    at MessagePort.Worker.onMessageFromParent (/usr/src/app/node_modules/@ironfish/sdk/build/src/workerPool/worker.js:63:18)\n' +
    '    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:562:20)\n' +
    '    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)'
}
```

**Comment by SunnyBoy00l** [comment]
A similar error message appears when I configure a mineral pool node. Could you please help to explain the problem

**Comment by wd021** [comment]
can you share what functions you're calling and the input params?

**Comment by lwisne** [comment]
There's not enough info here - could it be that the message was just correct and the payment address is invalid?
