### ISSUE TITLE
Error: Invalid GetBlockHashesResponse: GetBlockHashesRequest

### ISSUE THREAD

**Issue by Soptq** [iron-fish/ironfish#1716]
### What happened?

```
Stopping sync from o058J6b (nvkz) due to Error: Invalid GetBlockHashesResponse: GetBlockHashesRequest (2)
    at PeerNetwork.getBlockHashes (/home/user/.nvm/versions/node/v16.15.0/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/network/peerNetwork.js:258:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Syncer.findAncestor (/home/user/.nvm/versions/node/v16.15.0/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/syncer.js:177:28)
    at async Syncer.syncFrom (/home/user/.nvm/versions/node/v16.15.0/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/syncer.js:137:50)

```

### Version

v0.1.37

### Debug output

```shell
Iron Fish version            0.1.37 @ 44a7990
Iron Fish library            0.0.15 @ 44a7990
Operating system             Linux x64
CPU model(s)                 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
CPU threads                  6
RAM total                    15.18 GiB
Node version                 v16.15.0
ironfish in PATH             true
Telemetry enabled            true
Accounts head hash           000000000002181ea71f6ccd633cd6047af237114d85ec29a0970e4831ec7e4d
Accounts head in chain       true
Accounts head sequence       69417
```

### Graffiti

Soptq

**Comment by dguenther** [comment]
Closing this for now -- we're no longer using GetBlockHashes, so we may have inadvertently fixed this issue.
