### ISSUE TITLE
v0.1.37, The node has crashed during execution of 'ironfish depositAll' command

### ISSUE THREAD

**Issue by Shekelme** [iron-fish/ironfish#1722]
### What happened?

A bug happened! The node has crashed during execution of `ironfish depositAll` command.
I use NPM installation method, Node.js v16.15.1, Ubuntu server 20.04.4 LTS, AMD Ryzen Threadripper PRO 3955WX 16-Cores, 512GB RAM.

### Version

v0.1.37

### Debug output

```shell
Iron Fish version            0.1.37 @ 44a7990
Iron Fish library            0.0.15 @ 44a7990
Operating system             Linux x64
CPU model(s)                 AMD Ryzen Threadripper PRO 3955WX 16-Cores
CPU threads                  32
RAM total                    503.60 GiB
Node version                 v16.15.1
ironfish in PATH             true
Telemetry enabled            true
Accounts head hash           000000000002ea4da711dcf56ce609055f44e246deb40e377c46c7c5e528c3da
Accounts head in chain       true
Accounts head sequence       74282
```

### Relevant log output

```shell
Accepted tx 4ce3277d85967dc895c76217a9e4a8f0457de786eee08695be71ab4f65aa6d83, poolsize 2162
RECV WebRtc WRpHk36: NewTransaction (8) (repeated 8 times)
SEND WebRtc WRpHk36: NewTransaction (8)
SEND WebSocket uaRdJsl: NewTransaction (8)
SEND WebRtc mLCQOTG: NewTransaction (8)
SEND WebRtc ius6GJT: NewTransaction (8)
SEND WebRtc cMgCMnU: NewTransaction (8)
SEND WebRtc Vh0bTUQ: NewTransaction (8)
RECV WebSocket uaRdJsl: NewTransaction (8)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.7.2/src/thread.rs:246:33
stack backtrace:
   0:     0x7f52ecc8567c - <unknown>
   1:     0x7f52ecca0bac - <unknown>
   2:     0x7f52ecc83065 - <unknown>
   3:     0x7f52ecc87250 - <unknown>
   4:     0x7f52ecc86e05 - <unknown>
   5:     0x7f52ecc87904 - <unknown>
   6:     0x7f52ecc873e0 - <unknown>
   7:     0x7f52ecc85b24 - <unknown>
   8:     0x7f52ecc87349 - <unknown>
   9:     0x7f52ecb7cc41 - <unknown>
  10:     0x7f52ecb7ccd3 - <unknown>
  11:     0x7f52ecbdfc86 - <unknown>
  12:     0x7f52ecbb6816 - <unknown>
  13:     0x7f52ecbe1683 - <unknown>
  14:     0x7f52ecbacfae - <unknown>
  15:     0x7f52ecbacc0c - <unknown>
  16:     0x7f52ecbf546c - <unknown>
  17:     0x7f52ecbfad58 - <unknown>
  18:     0x7f52ecbae699 - <unknown>
  19:     0x7f52ecbc87bd - <unknown>
  20:     0x7f52ecb8aeb7 - <unknown>
  21:     0x7f52ecb850f2 - <unknown>
RECV WebRtc mLCQOTG: NewTransaction (8)
SEND WebRtc Ro+mQir: NewTransaction (8) (repeated 13 times)
RECV WebRtc Ro+mQir: NewTransaction (8)
  22:           0xab45dd - _ZN6v8impl12_GLOBAL__N_123FunctionCallbackWrapper6InvokeERKN2v820FunctionCallbackInfoINS2_5ValueEEE
  23:           0xd5531e - _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
  24:           0xd5673f - _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
  25:          0x15f2199 - Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
RECV WebRtc Vh0bTUQ: NewTransaction (8)
RECV WebRtc Ro+mQir: NewTransaction (8)
fatal runtime error: failed to initiate panic, error 5
```

### Graffiti

saturnia

**Comment by Shekelme** [comment]
And some additional info from another node:
```
RECV WebRtc k0yIMeM: NewTransaction (8)
RECV WebRtc k0yIMeM: NewTransaction (8)
RECV WebRtc k0yIMeM: PeerListRequest (10)
RECV WebRtc k0yIMeM: NewTransaction (8)
RECV WebRtc k0yIMeM: NewTransaction (8)
RECV WebRtc k0yIMeM: NewTransaction (8)
SEND WebRtc /f4u87u: NewTransaction (8) (repeated 7 times)
RECV WebRtc /f4u87u: PeerListRequest (10)
Accounts: spending note 12091270 be61b3764850acee59a785037e9627d77da03cfdab841ffdafb41766b201184f 5479
Accounts: spending note 12779637 fa6579ee74641dadb1a0e215c852ec36f4e120d4706058edff7794e735d5e83e 46115
Accounts: spending note 13227788 5c466c2b6269f7ce809bdd142007f9d496d216221d23203ccdf62cad4f7bf80a 29427
Accounts: spending note 12250672 0797ae26d6ea49082022732660b329e96672cfd07b967845ea5b80119046bc1e 13044862
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.7.2/src/thread.rs:246:33
stack backtrace:
   0:     0x7fb874c8567c - <unknown>
   1:     0x7fb874ca0bac - <unknown>
   2:     0x7fb874c83065 - <unknown>
   3:     0x7fb874c87250 - <unknown>
   4:     0x7fb874c86e05 - <unknown>
   5:     0x7fb874c87904 - <unknown>
   6:     0x7fb874c873e0 - <unknown>
   7:     0x7fb874c85b24 - <unknown>
   8:     0x7fb874c87349 - <unknown>
   9:     0x7fb874b7cc41 - <unknown>
  10:     0x7fb874b7ccd3 - <unknown>
  11:     0x7fb874bdfc86 - <unknown>
  12:     0x7fb874bb6816 - <unknown>
  13:     0x7fb874be1683 - <unknown>
  14:     0x7fb874bacfae - <unknown>
  15:     0x7fb874bacc0c - <unknown>
  16:     0x7fb874bf546c - <unknown>
  17:     0x7fb874bfad58 - <unknown>
  18:     0x7fb874bae699 - <unknown>
  19:     0x7fb874bc87bd - <unknown>
  20:     0x7fb874b8aeb7 - <unknown>
  21:     0x7fb874b850f2 - <unknown>
  22:           0xab45dd - <unknown>
  23:           0xd552fe - <unknown>
  24:           0xd5671f - <unknown>
  25:          0x15f2179 - <unknown>
fatal runtime error: failed to initiate panic, error 5
```

**Comment by NullSoldier** [comment]
Does this keep happening? I think it's because we must be missing a lock around balance calculation.

**Comment by Shekelme** [comment]
So far, I don't see any repetitions of this problem.

**Comment by Shekelme** [comment]
```
RECV WebRtc TbORWYE: NewTransaction (8)
SEND WebRtc K4+RfnH: NewTransaction (8) (repeated 10 times)
RECV WebRtc K4+RfnH: NewTransaction (8)
RECV WebRtc K4+RfnH: NewTransaction (8)
RECV WebRtc K4+RfnH: NewTransaction (8)
RECV WebRtc 6g+t6wk: NewTransaction (8)
RECV WebRtc 6g+t6wk: NewTransaction (8)
RECV WebRtc K4+RfnH: NewTransaction (8)
RECV WebRtc K4+RfnH: NewTransaction (8)
RECV WebRtc nJqg0Bh: NewTransaction (8)
RECV WebRtc nJqg0Bh: NewTransaction (8)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.7.2/src/thread.rs:246:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
```

**Comment by hughy** [comment]
We've made significant changes to the wallet since this issue was created. Please create a new issue if you've run into this again on a more recent version. Thanks!
