### ISSUE TITLE
WS_ERR_INVALID_OPCODE

### ISSUE THREAD

**Issue by msa6867** [iron-fish/ironfish#2074]
### What happened?

After running ironfish accounts:rescan --reset a few days ago I started running stably for first time in long time.  However, starting to get unstable again w various errors.  Latest is  "INVALID_OPCODE" when node running.

### Version

v0.1.44

### Debug output

```shell
\\
Iron Fish version               0.1.44 @ a79d445
Iron Fish library               0.0.21 @ a79d445
Operating system                Windows_NT x64
CPU model(s)                    AMD Ryzen 9 5950X 16-Core Processor
CPU threads                     32
RAM total                       31.92 GiB
Heap total                      3.75 GiB
Node version                    v16.15.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       msa6867
Block graffiti                  msa6867
Accounts head hash              0000000000037f926dcbb0434dbdaf58037e2eef590439cc9c1f06559dbe8675
Accounts head in chain          true
Accounts head sequence          148201
\\
```

### Relevant log output

```shell
\\
94.130.8.62e�� L8U5^ � �ZU ��m�Q���3� 7% I#
?�x@��& � ���7Q��8���*;domeknsI#178.128.98.100)ʟ�����ĺe\�w�i %"GLp��m�E���5
65.108.75.148 �Y�;��� �L��j �
͔�e�1��i�%�
node:events:505
      throw er; // Unhandled 'error' event
      ^

RangeError: Invalid WebSocket frame: invalid opcode 12
    at Receiver.getInfo (C:\Users\Mark\AppData\Roaming\npm\node_modules\ironfish\node_modules\ws\lib\receiver.js:269:14)
    at Receiver.startLoop (C:\Users\Mark\AppData\Roaming\npm\node_modules\ironfish\node_modules\ws\lib\receiver.js:131:22)
    at Receiver._write (C:\Users\Mark\AppData\Roaming\npm\node_modules\ironfish\node_modules\ws\lib\receiver.js:78:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Receiver.Writable.write (node:internal/streams/writable:334:10)
    at Socket.socketOnData (C:\Users\Mark\AppData\Roaming\npm\node_modules\ironfish\node_modules\ws\lib\websocket.js:920:35)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
Emitted 'error' event on WebSocket instance at:
    at Receiver.receiverOnError (C:\Users\Mark\AppData\Roaming\npm\node_modules\ironfish\node_modules\ws\lib\websocket.js:826:13)
    at Receiver.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'WS_ERR_INVALID_OPCODE',
  [Symbol(status-code)]: 1002
}
\\
```

### Graffiti

msa6867

**Comment by holahula** [comment]
Closing due to staleness. If the issue persists - please file a new issue
