### ISSUE TITLE
ironfish unexpected node crash while synching

### ISSUE THREAD

**Issue by tatsoplo** [iron-fish/ironfish#2080]
### What happened?

I got the following error on a windows 10 computer while synching a node.
It is the first time I got such an error since about three weeks node synching.
Meanwhile, I have just restarted the node with command "ironfish start" and the sync seems in progress...

Error log:
Added block seq: 122920, hash: 00000...25fcc, txs: 2, progress: 81.92%, time: 75.4ms
Requesting 20 blocks starting at 00000...a453f (122936) from VXkeRx8 (123123123)
Added block seq: 122940, hash: 00000...9b170, txs: 9, progress: 81.94%, time: 244.2ms
Requesting 20 blocks starting at 00000...814a8 (122956) from VXkeRx8 (123123123)
Added block seq: 122960, hash: 00000...3b0af, txs: 61, progress: 81.95%, time: 20395.7ms
Requesting 20 blocks starting at 00000...3594e (122976) from VXkeRx8 (123123123)
Added block seq: 122980, hash: 00000...0d629, txs: 61, progress: 81.96%, time: 1262.1ms
Requesting 20 blocks starting at 00000...4710f (122996) from VXkeRx8 (123123123)
Added block seq: 123000, hash: 00000...313e4, txs: 1, progress: 81.97%, time: 71.5ms
Requesting 20 blocks starting at 00000...ef043 (123016) from VXkeRx8 (123123123)
Added block seq: 123020, hash: 00000...10b72, txs: 61, progress: 81.98%, time: 20623.7ms
Error submitting telemetry to API: getaddrinfo ENOTFOUND api.ironfish.network
C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\bufio\lib\encoding.js:61
  check((hi & 0xffe00000) === 0, off, 'Number exceeds 2^53-1');
  ^

EncodingError: Number exceeds 2^53-1 (offset=0).
    at Object.readU64 (C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\bufio\lib\encoding.js:61:3)
    at BufferReader.readU64 (C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\bufio\lib\reader.js:364:26)
    at new Transaction (C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\primitives\transaction.js:21:38)
    at PeerNetwork.onNewTransaction (C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\network\peerNetwork.js:694:22)
    at PeerNetwork.handleGossipMessage (C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\network\peerNetwork.js:403:24)
    at PeerNetwork.handleMessage (C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\network\peerNetwork.js:372:24)
    at C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\network\peerNetwork.js:97:63
    at Event.emitAsync (C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\event.js:61:39)
    at Event.emit (C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\event.js:52:19)
    at PeerManager.handleMessage (C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\network\peers\peerManager.js:638:28) {
  type: 'EncodingError',
  code: 'ERR_ENCODING'
}

### Version

ironfish 0.1.44

### Debug output

```shell
C:\Users\ben>ironfish debug
Iron Fish version               0.1.44 @ a79d445
Iron Fish library               0.0.21 @ a79d445
Operating system                Windows_NT x64
CPU model(s)                    Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz
CPU threads                     4
RAM total                       7.90 GiB
Heap total                      2.01 GiB
Node version                    v16.16.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       hkzork2972
Block graffiti                  hkzork2972
Accounts head hash              000000000002d4bdfe3c70f75c1bbd4bed93b6bad897477338ec2a516bbdf6c2
Accounts head in chain          true
Accounts head sequence          66582
```

### Relevant log output

```shell
Added block seq: 122920, hash: 00000...25fcc, txs: 2, progress: 81.92%, time: 75.4ms
Requesting 20 blocks starting at 00000...a453f (122936) from VXkeRx8 (123123123)
Added block seq: 122940, hash: 00000...9b170, txs: 9, progress: 81.94%, time: 244.2ms
Requesting 20 blocks starting at 00000...814a8 (122956) from VXkeRx8 (123123123)
Added block seq: 122960, hash: 00000...3b0af, txs: 61, progress: 81.95%, time: 20395.7ms
Requesting 20 blocks starting at 00000...3594e (122976) from VXkeRx8 (123123123)
Added block seq: 122980, hash: 00000...0d629, txs: 61, progress: 81.96%, time: 1262.1ms
Requesting 20 blocks starting at 00000...4710f (122996) from VXkeRx8 (123123123)
Added block seq: 123000, hash: 00000...313e4, txs: 1, progress: 81.97%, time: 71.5ms
Requesting 20 blocks starting at 00000...ef043 (123016) from VXkeRx8 (123123123)
Added block seq: 123020, hash: 00000...10b72, txs: 61, progress: 81.98%, time: 20623.7ms
Error submitting telemetry to API: getaddrinfo ENOTFOUND api.ironfish.network
C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\bufio\lib\encoding.js:61
  check((hi & 0xffe00000) === 0, off, 'Number exceeds 2^53-1');
  ^

EncodingError: Number exceeds 2^53-1 (offset=0).
    at Object.readU64 (C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\bufio\lib\encoding.js:61:3)
    at BufferReader.readU64 (C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\bufio\lib\reader.js:364:26)
    at new Transaction (C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\primitives\transaction.js:21:38)
    at PeerNetwork.onNewTransaction (C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\network\peerNetwork.js:694:22)
    at PeerNetwork.handleGossipMessage (C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\network\peerNetwork.js:403:24)
    at PeerNetwork.handleMessage (C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\network\peerNetwork.js:372:24)
    at C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\network\peerNetwork.js:97:63
    at Event.emitAsync (C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\event.js:61:39)
    at Event.emit (C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\event.js:52:19)
    at PeerManager.handleMessage (C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\network\peers\peerManager.js:638:28) {
  type: 'EncodingError',
  code: 'ERR_ENCODING'
}
```

### Graffiti

https://testnet.ironfish.network/users/212263

**Comment by Skakruk** [comment]
seems like the same as in https://github.com/iron-fish/ironfish/issues/2061
