### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by hairtail** [iron-fish/ironfish#2165]
### What happened?

RangeError: Maximum call stack size exceeded when `ironfish accounts:transactions`
```
RangeError: Maximum call stack size exceeded
    at Table.outputTable (/home/ps/ironfish/ironfish/node_modules/@oclif/core/lib/cli-ux/styled/table.js:175:33)
    at Table.display (/home/ps/ironfish/ironfish/node_modules/@oclif/core/lib/cli-ux/styled/table.js:105:22)
    at Object.table (/home/ps/ironfish/ironfish/node_modules/@oclif/core/lib/cli-ux/styled/table.js:279:39)
    at TransactionsCommand.getTransactions (/home/ps/ironfish/ironfish/ironfish-cli/build/src/commands/accounts/transactions.js:54:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async TransactionsCommand.start (/home/ps/ironfish/ironfish/ironfish-cli/build/src/commands/accounts/transactions.js:20:13)
    at async TransactionsCommand.run (/home/ps/ironfish/ironfish/ironfish-cli/build/src/command.js:24:13)
    at async TransactionsCommand._run (/home/ps/ironfish/ironfish/node_modules/@oclif/core/lib/command.js:67:22)
    at async Config.runCommand (/home/ps/ironfish/ironfish/node_modules/@oclif/core/lib/config/config.js:268:25)
    at async Object.run (/home/ps/ironfish/ironfish/node_modules/@oclif/core/lib/main.js:73:5)
```

### Version

0.1.45 @ src

### Debug output

```shell
Iron Fish version               0.1.45 @ src
Iron Fish library               0.0.22 @ src
Operating system                Linux x64
CPU model(s)                    AMD Ryzen Threadripper 3960X 24-Core Processor
CPU threads                     48
RAM total                       62.82 GiB
Heap total                      4.01 GiB
Node version                    v16.16.0
ironfish in PATH                false
Garbage Collector Exposed       false
Telemetry enabled               true
```

### Graffiti

miningKing

**Comment by NullSoldier** [comment]
This is a known bug in Oclif UX library because they spread the a map into Array.push()

We should fix the bug in their library, or upgrade the library if the bug is already fixed.
