### ISSUE TITLE
[ Error: nullifierToNote mappings must have a corresponding noteToNullifier map]

### ISSUE THREAD

**Issue by JuManjey** [iron-fish/ironfish#2170]
### What happened?

Hetzner: AX41-NVME
AMD Ryzen™ 5 3600 
RAM: | 64 GB DDR4
Disk: | 2 x 512 GB NVMe SSD (software-RAID 1)

Set max and target peers to 20 with minerBatchSize 200 000
5 of 6 servers is working fine that server is stopped

```
root@IF-LK-2 ~ # systemctl status ironfishd ironfishd-miner
● ironfishd.service - IronFish Node
     Loaded: loaded (/etc/systemd/system/ironfishd.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2022-09-12 17:56:03 UTC; 7s ago
    Process: 12926 ExecStart=/usr/bin/yarn --cwd /root/ironfish/ironfish-cli/ start start (code=exited, status=1/FAILURE)
   Main PID: 12926 (code=exited, status=1/FAILURE)
        CPU: 8.229s

● ironfishd-miner.service - IronFish Miner
     Loaded: loaded (/etc/systemd/system/ironfishd-miner.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2022-09-12 17:42:49 UTC; 13min ago
   Main PID: 5910 (node)
      Tasks: 54 (limit: 76945)
     Memory: 124.4M
        CPU: 1h 21min 21.065s
     CGroup: /system.slice/ironfishd-miner.service
             ├─5910 node /usr/bin/yarn --cwd /root/ironfish/ironfish-cli/ start miners:start -v -t -1 --no-richOutput
             ├─5934 /bin/sh -c "yarn build && yarn start:js miners:start -v -t -1 --no-richOutput"
             ├─5973 /usr/bin/node /usr/bin/yarn start:js miners:start -v -t -1 --no-richOutput
             ├─5996 /bin/sh -c "cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect --inspect-publish-uid=http --enable-source-maps bin/run miners:start >
             ├─5997 /usr/bin/node /root/ironfish/ironfish-cli/node_modules/.bin/cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect --inspect-publish-uid>
             └─6012 /usr/bin/node --expose-gc --inspect --inspect-publish-uid=http --enable-source-maps bin/run miners:start -v -t -1 --no-richOutput

Sep 12 17:55:53 IF-LK-2 yarn[6012]: new work 000000000000e7e8928044b25282d7c0c753b6b63ddc9d4927194a8b5fbfe81b, 79 165.71 KH/s
Sep 12 17:55:55 IF-LK-2 yarn[6012]: Connecting to /root/.ironfish/ironfish.ipc
Sep 12 17:56:00 IF-LK-2 yarn[6012]: Connecting to /root/.ironfish/ironfish.ipc
Sep 12 17:56:00 IF-LK-2 yarn[6012]: Successfully connected to node
Sep 12 17:56:00 IF-LK-2 yarn[6012]: Listening to node for new blocks
Sep 12 17:56:02 IF-LK-2 yarn[6012]: Disconnected from node unexpectedly. Reconnecting.
Sep 12 17:56:02 IF-LK-2 yarn[6012]: Connecting to /root/.ironfish/ironfish.ipc
Sep 12 17:56:02 IF-LK-2 yarn[6012]: Failed to connect to node on ipc, retrying...
Sep 12 17:56:03 IF-LK-2 yarn[6012]: new work 000000000000e805ca01975fbf0cf23af5117ca76f183a318b35b38c132ab807, 80 35.11 MH/s
Sep 12 17:56:07 IF-LK-2 yarn[6012]: Connecting to /root/.ironfish/ironfish.ipc
```

### Version

0.1.45 @ src

### Debug output

```shell
root@IF-LK-2 ~ # journalctl -u ironfishd -f
Sep 12 17:45:34 IF-LK-2 yarn[7672]: ::::::::::           ::::::::::::::::
Sep 12 17:45:34 IF-LK-2 yarn[7672]: Version       0.1.45 @ src
Sep 12 17:45:34 IF-LK-2 yarn[7672]: Node Name     luckynode.tech.LK2
Sep 12 17:45:34 IF-LK-2 yarn[7672]: Graffiti      luckynode.tech.LK2
Sep 12 17:45:34 IF-LK-2 yarn[7672]: Peer Identity hPc2BNVcxDUlna03v3GcAgw4GT3HO2tuL03FxqObrBs=
Sep 12 17:45:34 IF-LK-2 yarn[7672]: Peer Agent    ironfish/0.1.45/src
Sep 12 17:45:34 IF-LK-2 yarn[7672]: Peer Port     9033
Sep 12 17:45:34 IF-LK-2 yarn[7672]: Bootstrap     test.bn1.ironfish.network
Sep 12 17:45:34 IF-LK-2 yarn[7672]:  
Sep 12 17:45:35 IF-LK-2 yarn[7672]: WebSocket server started at :::9033
Sep 12 17:45:39 IF-LK-2 yarn[7672]: Connected to the Iron Fish network
Sep 12 17:45:39 IF-LK-2 yarn[7672]: Starting sync from tRHdVje (tetsugyo). work: +315475821665163, ours: 181167, theirs: 181168
Sep 12 17:45:39 IF-LK-2 yarn[7672]: Finding ancestor using linear search on last 3 blocks starting at 00000...785ca (181167) from peer tRHdVje (tetsugyo) at 181168
Sep 12 17:45:39 IF-LK-2 yarn[7672]: Found peer tRHdVje (tetsugyo) ancestor 00000...785ca, syncing from 181167 -> 181168 (1) after 1 requests
Sep 12 17:45:39 IF-LK-2 yarn[7672]: Requesting 20 blocks starting at 00000...785ca (181167) from tRHdVje (tetsugyo)
Sep 12 17:45:39 IF-LK-2 yarn[7672]: Finished syncing 1 blocks from tRHdVje (tetsugyo)
Sep 12 17:45:39 IF-LK-2 yarn[7672]: /root/ironfish/ironfish/src/account/accounts.ts:505
Sep 12 17:45:39 IF-LK-2 yarn[7672]:               throw new Error(
Sep 12 17:45:39 IF-LK-2 yarn[7672]:                     ^
Sep 12 17:45:39 IF-LK-2 yarn[7672]: Error: nullifierToNote mappings must have a corresponding noteToNullifier map
Sep 12 17:45:39 IF-LK-2 yarn[7672]:     at <anonymous> (/root/ironfish/ironfish/src/account/accounts.ts:505:21)
Sep 12 17:45:39 IF-LK-2 yarn[7672]:     at LevelupDatabase.withTransaction (/root/ironfish/ironfish/src/storage/database/database.ts:205:22)
Sep 12 17:45:40 IF-LK-2 yarn[7653]: error Command failed with exit code 1.
Sep 12 17:45:40 IF-LK-2 yarn[7653]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Sep 12 17:45:40 IF-LK-2 yarn[7618]: error Command failed with exit code 1.
Sep 12 17:45:40 IF-LK-2 yarn[7618]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Sep 12 17:45:40 IF-LK-2 systemd[1]: ironfishd.service: Main process exited, code=exited, status=1/FAILURE
Sep 12 17:45:40 IF-LK-2 systemd[1]: ironfishd.service: Failed with result 'exit-code'.
Sep 12 17:45:40 IF-LK-2 systemd[1]: ironfishd.service: Consumed 10.130s CPU time.
Sep 12 17:45:50 IF-LK-2 systemd[1]: ironfishd.service: Scheduled restart job, restart counter is at 27.
Sep 12 17:45:50 IF-LK-2 systemd[1]: Stopped IronFish Node.
Sep 12 17:45:50 IF-LK-2 systemd[1]: ironfishd.service: Consumed 10.130s CPU time.
Sep 12 17:45:50 IF-LK-2 systemd[1]: Started IronFish Node.
Sep 12 17:45:50 IF-LK-2 yarn[7753]: yarn run v1.22.19
Sep 12 17:45:50 IF-LK-2 yarn[7753]: $ yarn build && yarn start:js start
```

### Graffiti

luckynode.tech.LK2

**Comment by terrancewong** [comment]
0.1.47 still has this issue.

**Comment by hughy** [comment]
v0.1.48 included significant changes to the wallet. The `noteToNullifier` data storage has been removed from the wallet and resolved this error.
