### ISSUE TITLE
Unable to Restart

### ISSUE THREAD

**Issue by omiDBaghi** [iron-fish/ironfish#2203]
### What happened?

Attempting reboot commands had no effect

### Version

0.1.44

### Debug output

```shell
Iron Fish version               0.1.46 @ 46d759c
Iron Fish library               0.0.23 @ 46d759c
Operating system                Linux x64
CPU model(s)                    AMD EPYC Processor
CPU threads                     3
RAM total                       3.74 GiB
Heap total                      1.88 GiB
Node version                    v16.17.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               false
Node name                       omiD
Block graffiti                  omiD
```

### Relevant log output

```shell
Added block seq: 122920, hash: 00000...25fcc, txs: 2, progress: 81.92%, time: 75.4ms
Requesting 20 blocks starting at 00000...a453f (122936) from VXkeRx8 (123123123)
Added block seq: 122940, hash: 00000...9b170, txs: 9, progress: 81.94%, time: 244.2ms
Requesting 20 blocks starting at 00000...814a8 (122956) from VXkeRx8 (123123123)
Added block seq: 122960, hash: 00000...3b0af, txs: 61, progress: 81.95%, time: 20395.7ms
Requesting 20 blocks starting at 00000...3594e (122976) from VXkeRx8 (123123123)
Added block seq: 122980, hash: 00000...0d629, txs: 61, progress: 81.96%, time: 1262.1ms
Requesting 20 blocks starting at 00000...4710f (122996) from VXkeRx8 (123123123)
Added block seq: 123000, hash: 00000...313e4, txs: 1, progress: 81.97%, time: 71.5ms
Requesting 20 blocks starting at 00000...ef043 (123016) from VXkeRx8 (123123123)
Added block seq: 123020, hash: 00000...10b72, txs: 61, progress: 81.98%, time: 20623.7ms
Error submitting telemetry to API: getaddrinfo ENOTFOUND api.ironfish.network
C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\bufio\lib\encoding.js:61
  check((hi & 0xffe00000) === 0, off, 'Number exceeds 2^53-1');
  ^

EncodingError: Number exceeds 2^53-1 (offset=0).
    at Object.readU64 (C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\bufio\lib\encoding.js:61:3)
    at BufferReader.readU64 (C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\bufio\lib\reader.js:364:26)
    at new Transaction (C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\primitives\transaction.js:21:38)
    at PeerNetwork.onNewTransaction (C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\network\peerNetwork.js:694:22)
    at PeerNetwork.handleGossipMessage (C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\network\peerNetwork.js:403:24)
    at PeerNetwork.handleMessage (C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\network\peerNetwork.js:372:24)
    at C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\network\peerNetwork.js:97:63
    at Event.emitAsync (C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\event.js:61:39)
    at Event.emit (C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\event.js:52:19)
    at PeerManager.handleMessage (C:\Users\user1\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\network\peers\peerManager.js:638:28) {
  type: 'EncodingError',
  code: 'ERR_ENCODING'
}
```

**Comment by omiDBaghi** [comment]
Graffiti : omiD

**Comment by hughy** [comment]
Same issue as #2080 and #2061

**Comment by tuncatunc** [comment]
Can bigint used for large numbers?

**Comment by holahula** [comment]
Closing due to staleness. If the issue persists in versions `1.0.0+` - please file a new issue
