### ISSUE TITLE
node crash during synching

### ISSUE THREAD

**Issue by khgg67tGD** [iron-fish/ironfish#2286]
### What happened?

"Invalid WebSocket frame: invalid opcode 11A bug happened!" raised while synching, then node crash

### Version

0.1.47

### Debug output

```shell
Iron Fish version               0.1.47 @ 0efb836
Iron Fish library               0.0.24 @ 0efb836
Operating system                Windows_NT x64
CPU model(s)                    Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz
CPU threads                     4
RAM total                       7.90 GiB
Heap total                      2.01 GiB
Node version                    v16.16.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       hkzork2972
Block graffiti                  hkzork2972
```

### Relevant log output

```shell
Microsoft Windows [Version 10.0.19044.2006]
(c) Microsoft Corporation. All rights reserved.

C:\Users\ben>ironfish start


::::::::::          :::::::::::::::::
::::::::::::       :::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::::   ::::::::::::::::::::::::
 ::::::::::::: ::::::::::        :::::::::
   :::::::::::::::::::::          ::::::::::
   :::::::::::::::::::::          :::::::::
 ::::::::::::: ::::::::::        :::::::::
::::::::::::::   ::::::::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::       :::::::::::::::::::
::::::::::           ::::::::::::::::

Version       0.1.47 @ 0efb836
Node Name     hkzork2972
Graffiti      hkzork2972
Peer Identity V/5vBFyTaIKHsxcZ2VJJ9YUgQ81KlgSw2eQgSeQBoBo=
Peer Agent    ironfish/0.1.47/0efb836
Peer Port     9033
Bootstrap     test.bn1.ironfish.network

WebSocket server started at :::9033
Connected to the Iron Fish network
Starting sync from Voideki (tetsugyo). work: +413671068974624206, ours: 209900, theirs: 210357
Finding ancestor using linear search on last 3 blocks starting at 00000...9aef5 (209900) from peer Voideki (tetsugyo) at 210357
Found peer Voideki (tetsugyo) ancestor 00000...9aef5, syncing from 209900 -> 210357 (457) after 1 requests
Requesting 20 blocks starting at 00000...9aef5 (209900) from Voideki (tetsugyo)
Peer Voideki (tetsugyo) disconnected (DISCONNECTED) while syncing.
Starting sync from qBqWA2U (WWW.IRONFISH.HOST). work: +673594238269379433, ours: 209900, theirs: 210655
Finding ancestor using linear search on last 3 blocks starting at 00000...9aef5 (209900) from peer qBqWA2U (WWW.IRONFISH.HOST) at 210655
Found peer qBqWA2U (WWW.IRONFISH.HOST) ancestor 00000...9aef5, syncing from 209900 -> 210655 (755) after 1 requests
Requesting 20 blocks starting at 00000...9aef5 (209900) from qBqWA2U (WWW.IRONFISH.HOST)
Added block seq: 209920, hash: 00000...d1622, txs: 301, progress: 99.64%, time: 9379.6ms
Requesting 20 blocks starting at 00000...d1622 (209920) from qBqWA2U (WWW.IRONFISH.HOST)
Added block seq: 209940, hash: 00000...a143e, txs: 301, progress: 99.65%, time: 10584.8ms
Requesting 20 blocks starting at 00000...a143e (209940) from qBqWA2U (WWW.IRONFISH.HOST)
Added block seq: 209960, hash: 00000...b19b3, txs: 301, progress: 99.66%, time: 9045.0ms
Requesting 20 blocks starting at 00000...b19b3 (209960) from qBqWA2U (WWW.IRONFISH.HOST)
Added block seq: 209980, hash: 00000...cdee4, txs: 301, progress: 99.67%, time: 12537.1ms
Requesting 20 blocks starting at 00000...cdee4 (209980) from qBqWA2U (WWW.IRONFISH.HOST)
Added block seq: 210000, hash: 00000...367f3, txs: 4, progress: 99.68%, time: 259.5ms
Requesting 20 blocks starting at 00000...367f3 (210000) from qBqWA2U (WWW.IRONFISH.HOST)
Added block seq: 210020, hash: 00000...b0b1f, txs: 4, progress: 99.68%, time: 298.0ms
Requesting 20 blocks starting at 00000...b0b1f (210020) from qBqWA2U (WWW.IRONFISH.HOST)
Added block seq: 210040, hash: 00000...c2c96, txs: 301, progress: 99.69%, time: 9983.6ms
Requesting 20 blocks starting at 00000...c2c96 (210040) from qBqWA2U (WWW.IRONFISH.HOST)
Added block seq: 210060, hash: 00000...80c6c, txs: 301, progress: 99.70%, time: 9904.5ms
Requesting 20 blocks starting at 00000...80c6c (210060) from qBqWA2U (WWW.IRONFISH.HOST)
Added block seq: 210080, hash: 00000...57a76, txs: 115, progress: 99.71%, time: 4559.0ms
Requesting 20 blocks starting at 00000...57a76 (210080) from qBqWA2U (WWW.IRONFISH.HOST)
Added block seq: 210100, hash: 00000...c612a, txs: 65, progress: 99.72%, time: 2680.3ms
Requesting 20 blocks starting at 00000...c612a (210100) from qBqWA2U (WWW.IRONFISH.HOST)
Added block seq: 210120, hash: 00000...a2e83, txs: 301, progress: 99.72%, time: 11351.0ms
Requesting 20 blocks starting at 00000...a2e83 (210120) from qBqWA2U (WWW.IRONFISH.HOST)
Added block seq: 210140, hash: 00000...efc32, txs: 301, progress: 99.73%, time: 10987.8ms
Requesting 20 blocks starting at 00000...efc32 (210140) from qBqWA2U (WWW.IRONFISH.HOST)
Added block seq: 210160, hash: 00000...85c8a, txs: 301, progress: 99.74%, time: 8817.0ms
Requesting 20 blocks starting at 00000...85c8a (210160) from qBqWA2U (WWW.IRONFISH.HOST)
Added block seq: 210180, hash: 00000...3736e, txs: 301, progress: 99.74%, time: 11554.2ms
Requesting 20 blocks starting at 00000...3736e (210180) from qBqWA2U (WWW.IRONFISH.HOST)
Added block seq: 210200, hash: 00000...2349d, txs: 301, progress: 99.75%, time: 12106.6ms
Requesting 20 blocks starting at 00000...2349d (210200) from qBqWA2U (WWW.IRONFISH.HOST)
Added block seq: 210220, hash: 00000...6f617, txs: 251, progress: 99.76%, time: 7696.0ms
Requesting 20 blocks starting at 00000...6f617 (210220) from qBqWA2U (WWW.IRONFISH.HOST)
Added block seq: 210240, hash: 00000...880c1, txs: 149, progress: 99.77%, time: 5849.9ms
Requesting 20 blocks starting at 00000...880c1 (210240) from qBqWA2U (WWW.IRONFISH.HOST)
Added block seq: 210260, hash: 00000...2b66b, txs: 301, progress: 99.78%, time: 9926.3ms
Requesting 20 blocks starting at 00000...2b66b (210260) from qBqWA2U (WWW.IRONFISH.HOST)
Added block seq: 210280, hash: 00000...61d9d, txs: 301, progress: 99.79%, time: 10676.8ms
Requesting 20 blocks starting at 00000...61d9d (210280) from qBqWA2U (WWW.IRONFISH.HOST)
Added block seq: 210300, hash: 00000...a7b0d, txs: 224, progress: 99.80%, time: 10144.3ms
Requesting 20 blocks starting at 00000...a7b0d (210300) from qBqWA2U (WWW.IRONFISH.HOST)
Added block seq: 210320, hash: 00000...54142, txs: 301, progress: 99.81%, time: 11244.6ms
Requesting 20 blocks starting at 00000...54142 (210320) from qBqWA2U (WWW.IRONFISH.HOST)
Added block seq: 210340, hash: 00000...3638e, txs: 301, progress: 99.81%, time: 9325.6ms
Requesting 20 blocks starting at 00000...3638e (210340) from qBqWA2U (WWW.IRONFISH.HOST)
Added block seq: 210360, hash: 00000...2e5f9, txs: 301, progress: 99.82%, time: 12908.0ms
Requesting 20 blocks starting at 00000...2e5f9 (210360) from qBqWA2U (WWW.IRONFISH.HOST)
Added block seq: 210380, hash: 00000...c9fb9, txs: 301, progress: 99.83%, time: 14772.6ms
Requesting 20 blocks starting at 00000...c9fb9 (210380) from qBqWA2U (WWW.IRONFISH.HOST)
Added block seq: 210400, hash: 00000...63ff2, txs: 301, progress: 99.84%, time: 13135.3ms
Requesting 20 blocks starting at 00000...63ff2 (210400) from qBqWA2U (WWW.IRONFISH.HOST)
Added block seq: 210420, hash: 00000...c0bd8, txs: 301, progress: 99.85%, time: 14591.8ms
Requesting 20 blocks starting at 00000...c0bd8 (210420) from qBqWA2U (WWW.IRONFISH.HOST)
Added block seq: 210440, hash: 00000...ece25, txs: 301, progress: 99.85%, time: 12949.1ms
Requesting 20 blocks starting at 00000...ece25 (210440) from qBqWA2U (WWW.IRONFISH.HOST)
Added block seq: 210460, hash: 00000...13f20, txs: 160, progress: 99.86%, time: 17592.8ms
Requesting 20 blocks starting at 00000...13f20 (210460) from qBqWA2U (WWW.IRONFISH.HOST)
Added block seq: 210480, hash: 00000...8052f, txs: 301, progress: 99.86%, time: 22721.1ms
Requesting 20 blocks starting at 00000...8052f (210480) from qBqWA2U (WWW.IRONFISH.HOST)
Added block seq: 210500, hash: 00000...e238b, txs: 301, progress: 99.86%, time: 38159.1ms
Requesting 20 blocks starting at 00000...e238b (210500) from qBqWA2U (WWW.IRONFISH.HOST)
Peer qBqWA2U (WWW.IRONFISH.HOST) disconnected (DISCONNECTED) while syncing.
Starting sync from zWvNMFO (irontest). work: +166615066226546656, ours: 210508, theirs: 210792
Finding ancestor using linear search on last 3 blocks starting at 00000...d2c94 (210508) from peer zWvNMFO (irontest) at 210792
Found peer zWvNMFO (irontest) ancestor 00000...d2c94, syncing from 210508 -> 210792 (284) after 1 requests
Requesting 20 blocks starting at 00000...d2c94 (210508) from zWvNMFO (irontest)
Added block seq: 210520, hash: 00000...aedff, txs: 301, progress: 99.87%, time: 39645.5ms
Requesting 20 blocks starting at 00000...9fb67 (210528) from zWvNMFO (irontest)
Added block seq: 210540, hash: 00000...02aa6, txs: 301, progress: 99.87%, time: 42650.7ms
Requesting 20 blocks starting at 00000...1fa1f (210548) from zWvNMFO (irontest)
Error submitting telemetry to API: getaddrinfo ENOTFOUND api.ironfish.network
error parsing message   0��eM∟ލ�x%↔�↑E%
49.12.209.139�!���→�J�&�b����<M2F�2�ruL↓¶��u1☺♦Kash�ܼ���A撾_♠>`���s�["�↕�f4u♣xoradI#♫88.147.173.139����zU►�-׭����@f��→,F91k↓_↕)�e♠I#♫43.156.241.144N�S�♂g�&�r��
♥��m▼W_&→�*�搋��a♠wXijGSI#♀116.8.47.173؄�5ţ▲��i�5�J'�K�Ϫ↨"4N
43.133.200.74▼s�I�O�\\��Q�☼H`‼�`+�.�§v#hc|�M♠I#♫43.156.239.120+�↕m�٢F►♥����▼�<�͌§k�wM�W=�#G♥mncI#♫67.168.234.184�peЏ�s�XP$��L'�♣♫���lP�����(!nodn.cnI#♂49.73.38.30OT���KL�
43.156.132.16����p=��▬☻eDD�G���s-,�iJ{↓���c⌂♣jimenI#♀120.226.37.7��↕♦p]�ȗ)a�⌂�=�
�/♫♫��Fo$☻♫�}$M♠champ1I#☼188.243.183.105��&�@�M+���r�s-�'���X��A♣�∟�↨
�↔�c�`�▬�.Q�e�♫q�N�4�♥��186mh
120.226.37.44xr�c�b�{cs�����⌂TrickentI#☼149.102.146.102♫A}A�H���b3��2�j���,�gk�)֕�▼��‼♣pughjI#
↓�_j��g~↔☼֔�∟`�F∟��ZT♣gregbI#♀73.54.194.85�♣§����̑▬SJ�8���&��X��R~�����dB♠I#♫43.156.131.21�9?�a)�Ky%s���Qp�xA~P⌂
♣���♠,91&�*�ϼ�ҿ\�@�↓V�Ւ����♥*�/ުY��{.���►<�♀?` �N▼�Z^�Ţ�♫�F&6�Pi��(�͂"☼☺wQ��Ƌ���?�∟�↔�B�5e�↔+♠∟��♀Q���~♣�►☺��♣☺☻�☺�7♥�Y���@$e�q�)☻���9���*Y�ކʠR��P§�S�A�'�‼���>S-5��3�
`�bґ���2�:♠S�:9��◄~A�@MD�,♥�4r��*�9��b+���`�ࠓ�i☼��#'=�� NųK)cu��`2�Dƴx�C��(]►��#��)�◄^;&‼♣+Q☻��`a1p��!@/~�,↓�;K�3�♀���`��NS��+☺§�F���W♠"��ZA�a���l̮[!A���∟��=O��sv ◄♦�$t��:�����u‼�$�d��¶ӆxS�D����Ԙ��♂h↨v�Ӽ�V7G����;Y(�^4g↨Ʃ:��/�U턴<���F~@��@d}@m���L&R��j����↨�tM��Z↕">�6�j�U�+]��↕���Rj���cA��eKR↔[�♀Ć▬?w���       ▼\�>e�KI��r��Z��A��y�p�F�8Z☻�æ��7s▲↓�3��,=�5�$&��91���s�d�{$��Y:+¶�!@��4�e      �$���P��ᑬ�̘f��+���MjL☺���ZY�o�▼��
c��.BV♥♠5�)�ɭ▼�EZ�QBp6��?��"Z☻�Z�U�Jq��∟��ë�M@=Q�M8D�����♥n4�6�M�       8�}�J�◄�������-��a�9�2a�z↓�ط�☼�[�7�5b§�p�▬�♦ ����}�%�G�ۙr�↑����%Gg�x��♫▲\�↑��e��◄=►�0�-�3]����W�↕\�y♣�7→��♦�i�☺A�{����6►Ωc:�↕����0���9�~�}☼2_+��        k⌂▼Ԅ�R7�↕Q_��▬§ى�L��    ♀↔��↑�\�☼G�♠�jb�▲q�s6����#��o����*�↨?�u���u☻䆄@��7�`o'��♂��.!����R�Mp�$���b∟☼1��2/�‼�����7NHI��3�{���;�♠���I�z▬a=�
node:events:505
      throw er; // Unhandled 'error' event
      ^

RangeError: Invalid WebSocket frame: invalid opcode 11
    at Receiver.getInfo (C:\Users\ben\AppData\Roaming\npm\node_modules\ironfish\node_modules\ws\lib\receiver.js:269:14)
    at Receiver.startLoop (C:\Users\ben\AppData\Roaming\npm\node_modules\ironfish\node_modules\ws\lib\receiver.js:131:22)
    at Receiver._write (C:\Users\ben\AppData\Roaming\npm\node_modules\ironfish\node_modules\ws\lib\receiver.js:78:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Receiver.Writable.write (node:internal/streams/writable:334:10)
    at Socket.socketOnData (C:\Users\ben\AppData\Roaming\npm\node_modules\ironfish\node_modules\ws\lib\websocket.js:920:35)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
Emitted 'error' event on WebSocket instance at:
    at Receiver.receiverOnError (C:\Users\ben\AppData\Roaming\npm\node_modules\ironfish\node_modules\ws\lib\websocket.js:826:13)
    at Receiver.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'WS_ERR_INVALID_OPCODE',
  [Symbol(status-code)]: 1002
}

C:\Users\ben>
```

### Graffiti

https://testnet.ironfish.network/users/212263

**Comment by holahula** [comment]
Closing - this is a DNS issue due to `api.ironfish.network` not being found. This is either user-side or transient due to the domain being temporarily unavailable
