### ISSUE TITLE
Migration 013-wallet-2 failing

### ISSUE THREAD

**Issue by gzivdo** [iron-fish/ironfish#2296]
### What happened?

![изображение](https://user-images.githubusercontent.com/13568002/194056369-135514ef-effa-4657-ac45-063a2ad97997.png)

### Version

0.1.48

### Debug output

```shell
Database cannot be opened, skipping output that requires database.

DatabaseVersionError: Your database needs to be upgraded (v11 vs v13).
Run "ironfish migrations:start" or "ironfish start --upgrade"

    at LevelupDatabase.upgrade (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/storage/levelup/database.js:80:19)
    at async WalletDB.open (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/wallet/walletdb/walletdb.js:85:9)
    at async Wallet.open (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/wallet/wallet.js:111:9)
    at async IronfishNode.openDB (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/node.js:185:13)
    at async Debug.start (/usr/lib/node_modules/ironfish/build/src/commands/debug.js:21:13)
    at async Debug.run (/usr/lib/node_modules/ironfish/build/src/command.js:24:13)
    at async Debug._run (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/command.js:81:22)
    at async Config.runCommand (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/config/config.js:272:25)
    at async Object.run (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/main.js:76:5)

Iron Fish version               0.1.48 @ 6769ec1
Iron Fish library               0.0.25 @ 6769ec1
Operating system                Linux x64
CPU model(s)                    Intel(R) Core(TM) i5-3570S CPU @ 3.10GHz
CPU threads                     4
RAM total                       15.32 GiB
Heap total                      2.01 GiB
Node version                    v16.15.1
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
```

### Graffiti

ar2Obyahain

**Comment by sangtn0102** [comment]
If ironfish is running under a service, have you stopped it?

**Comment by gzivdo** [comment]
yes,  i stopped it before migrate

**Comment by gzivdo** [comment]
0.1.49 fixed issue
