### ISSUE TITLE
ironfish migrations:start does not work when upgrading to latest ironfish@0.1.48

### ISSUE THREAD

**Issue by darrencavell** [iron-fish/ironfish#2297]
### What happened?

After installing the latest version of ironfish using `npm install -g ironfish` I am unable to start and / or migrate the accounts to the new 2.0 wallet

```
Version       0.1.48 @ 6769ec1
Node Name     DarrzDC
Graffiti      DarrzDC
Peer Identity pRn06Kdq34118zHBs4byl7RPd0XPIamm+kKtTo5bPB4=
Peer Agent    ironfish/0.1.48/6769ec1
Peer Port     9033
Bootstrap     test.bn1.ironfish.network
 
Your database needs to be upgraded (v11 vs v13).
Run "ironfish migrations:start" or "ironfish start --upgrade"
```

```
Applying 1 migrations:
  013-wallet-2

Running 013-wallet-2...
Error applying 013-wallet-2
Error: Expected value not to be undefined
    at Function.isNotUndefined (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/assert.js:18:19)
    at Migration013.migrateAccountsData (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/migrations/data/013-wallet-2.js:182:29)
    at async Migration013.forward (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/migrations/data/013-wallet-2.js:87:9)
    at async Migrator.migrate (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/migrations/migrator.js:118:17)
    at async StartCommand.start (/usr/lib/node_modules/ironfish/build/src/commands/migrations/start.js:14:9)
    at async StartCommand.run (/usr/lib/node_modules/ironfish/build/src/command.js:24:13)
    at async StartCommand._run (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/command.js:81:22)
    at async Config.runCommand (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/config/config.js:272:25)
    at async Object.run (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/main.js:76:5)
```

### Version

0.1.48

### Debug output

```shell
Database cannot be opened, skipping output that requires database.

DatabaseVersionError: Your database needs to be upgraded (v11 vs v13).
Run "ironfish migrations:start" or "ironfish start --upgrade"

    at LevelupDatabase.upgrade (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/storage/levelup/database.js:80:19)
    at async WalletDB.open (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/wallet/walletdb/walletdb.js:85:9)
    at async Wallet.open (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/wallet/wallet.js:111:9)
    at async IronfishNode.openDB (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/node.js:185:13)
    at async Debug.start (/usr/lib/node_modules/ironfish/build/src/commands/debug.js:21:13)
    at async Debug.run (/usr/lib/node_modules/ironfish/build/src/command.js:24:13)
    at async Debug._run (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/command.js:81:22)
    at async Config.runCommand (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/config/config.js:272:25)
    at async Object.run (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/main.js:76:5)

Iron Fish version               0.1.48 @ 6769ec1
Iron Fish library               0.0.25 @ 6769ec1
Operating system                Linux x64
CPU model(s)                    11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz
CPU threads                     16
RAM total                       7.53 GiB
Heap total                      2.01 GiB
Node version                    v16.17.1
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       DarrzDC
Block graffiti                  DarrzDC
```

### Graffiti

DarrzDC

**Comment by NullSoldier** [comment]
We're working on this here, https://github.com/iron-fish/ironfish/pull/2298

**Comment by NullSoldier** [comment]
Thanks for the report, we're gonna use the first ticket reported about this issue as the megathread here, https://github.com/iron-fish/ironfish/issues/2296
