### ISSUE TITLE
`ironfish status` fails with `TypeError`

### ISSUE THREAD

**Issue by neuronull** [iron-fish/ironfish#2321]
### What happened?

My node is still syncing, at 98% or so.

Running the `ironfish status` command results in a `TypeError`.

```
$ ironfish status
TypeError: Cannot read properties of null (reading 'toFixed')
    at renderStatus (/usr/lib/node_modules/ironfish/build/src/commands/status.js:124:70)
    at Status.start (/usr/lib/node_modules/ironfish/build/src/commands/status.js:21:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Status.run (/usr/lib/node_modules/ironfish/build/src/command.js:24:13)
    at async Status._run (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/command.js:81:22)
    at async Config.runCommand (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/config/config.js:272:25)
    at async Object.run (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/main.js:76:5)

``

### Version

v0.1.49

### Debug output

```shell
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version               0.1.49 @ ec57ed3
Iron Fish library               0.0.26 @ ec57ed3
Operating system                Linux x64
CPU model(s)                    Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
CPU threads                     4
RAM total                       12.44 GiB
Heap total                      2.01 GiB
Node version                    v16.17.1
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       null
Block graffiti                  null
```

### Graffiti

null

**Comment by neuronull** [comment]
The issue went away after stopping the node and restarting it.

**Comment by neuronull** [comment]
I have seen this two more times now since the original instance.

**Comment by neuronull** [comment]
This is still happening with `v0.1.51`

```
 ironfish debug
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version               0.1.51 @ 67da183
Iron Fish library               0.0.28 @ 67da183
Operating system                Linux x64
CPU model(s)                    Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
CPU threads                     4
RAM total                       12.44 GiB
Heap total                      2.01 GiB
Node version                    v16.17.1
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       null
Block graffiti                  null
```

```

$ ironfish status
TypeError: Cannot read properties of null (reading 'toFixed')
    at renderStatus (/usr/lib/node_modules/ironfish/build/src/commands/status.js:124:70)
    at Status.start (/usr/lib/node_modules/ironfish/build/src/commands/status.js:21:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Status.run (/usr/lib/node_modules/ironfish/build/src/command.js:24:13)
    at async Status._run (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/command.js:81:22)
    at async Config.runCommand (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/config/config.js:272:25)
    at async Object.run (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/main.js:76:5)]
```

```
[17:25:59.777] [info] Finding ancestor using linear search on last 3 blocks starting at 00000...647c6 (256902) from peer tu/Dwyv (Web3isfuture) at 256904
[17:25:59.995] [info] Found peer tu/Dwyv (Web3isfuture) ancestor 00000...647c6, syncing from 256902 -> 256904 (2) after 1 requests
[17:25:59.996] [info] Requesting 5 blocks starting at 00000...647c6 (256902) from tu/Dwyv (Web3isfuture)
[17:26:12.278] [info] Finished syncing 2 blocks from tu/Dwyv (Web3isfuture), skipped 1
[17:33:51.646] [warn] Added block to fork seq: 256910, head-seq: 256910, hash: 00000...6d880, head-hash: 00000...cef10, work: 65952601070416085561, head-work: 65952601605009323692, work-diff:
 534593238131
[17:38:18.085] [warn] Added block to fork seq: 256913, head-seq: 256913, hash: 00000...ced78, head-hash: 00000...29773, work: 65955869600607058244, head-work: 65955870133114080850, work-diff:
 532507022606
[17:42:17.465] [info] Added block seq: 256920, hash: 00000...4ed3c, txs: 135, progress: 100.00%, time: 679.4ms
[17:42:29.421] [warn] Reorganizing chain from 00000...81803 (256921) for 00000...2eef5 (256921) on prev 00000...4ed3c (256920)
[17:42:29.436] [warn] Reorganized chain. blocks: 1, old: 00000...81803 (256921), new: 00000...4ed3c (256920), fork: 00000...4ed3c (256920)
[17:47:44.745] [warn] Added block to fork seq: 256923, head-seq: 256923, hash: 00000...4fc96, head-hash: 00000...76078, work: 65966790122274552221, head-work: 65966791185668152671, work-diff:
 1063393600450
[17:59:06.957] [warn] Added block to fork seq: 256931, head-seq: 256931, hash: 00000...4bb03, head-hash: 00000...6f543, work: 65975422814298383973, head-work: 65975423866795033673, work-diff:
 1052496649700
[18:05:00.077] [info] Added block seq: 256940, hash: 00000...ac59c, txs: 31, progress: 100.00%, time: 170.1ms
[18:11:57.495] [info] Starting sync from hNa4nkQ (feelinguniverse). work: +-3468146821922257395, ours: 256945, theirs: 256947
[18:11:57.495] [info] Finding ancestor using linear search on last 3 blocks starting at 00000...85fb8 (256945) from peer hNa4nkQ (feelinguniverse) at 256947
[18:11:57.815] [info] Found peer hNa4nkQ (feelinguniverse) ancestor 00000...85fb8, syncing from 256945 -> 256947 (2) after 1 requests
[18:11:57.815] [info] Requesting 5 blocks starting at 00000...85fb8 (256945) from hNa4nkQ (feelinguniverse)
[18:12:23.451] [info] Finished syncing 1 blocks from hNa4nkQ (feelinguniverse), skipped 1
[18:22:24.775] [info] Added block seq: 256960, hash: 00000...e2e5b, txs: 59, progress: 100.00%, time: 285.0ms
[18:47:34.146] [info] Added block seq: 256980, hash: 00000...70411, txs: 159, progress: 100.00%, time: 732.9ms
[18:58:01.654] [warn] Reorganizing chain from 00000...007bf (256991) for 00000...c85ac (256991) on prev 00000...e2d62 (256990)
[18:58:01.822] [warn] Reorganized chain. blocks: 1, old: 00000...007bf (256991), new: 00000...e2d62 (256990), fork: 00000...e2d62 (256990)
[19:13:34.938] [info] Added block seq: 257000, hash: 00000...b1c41, txs: 233, progress: 100.00%, time: 1052.0ms
[19:22:13.943] [warn] Added block to fork seq: 257007, head-seq: 257007, hash: 00000...ec799, head-hash: 00000...26e89, work: 66057719677004236984, head-work: 66057719677004236984, work-diff:
 0
[19:22:48.334] [warn] Added block to fork seq: 257008, head-seq: 257008, hash: 00000...02d99, head-hash: 00000...c467c, work: 66058776726306119591, head-work: 66058778273207536979, work-diff:
 1546901417388
```

**Comment by hughy** [comment]
Hi @neuronull , a couple of questions to help debug:
1. How did you install and run ironfish? (Docker, npm, source, etc.)
2. Have you noticed any pattern to when you see this error or have an idea of how to reproduce it?

Thanks!

**Comment by neuronull** [comment]
Hi @hughy :wave: 

> 1. How did you install and run ironfish? (Docker, npm, source, etc.)

All through npm.

> 2. Have you noticed any pattern to when you see this error or have an idea of how to reproduce it?

I suspect it might be occurring when `Accounts` is syncing.
It's interesting that it happened again after 0.1.5x what with all the syncing improvements :thinking: .
Right now, my node is syncing again since it had crashed 8 hours ago due to #2516 , but I'm running `ironfish status` here and so far am not triggering it.

Perhaps this is also a hint? 

```
[warn] Added block to fork...
```

Right now I'm only seeing info logs, no fork.

When it happens, it stays like that until I restart the node.

Is there anything I could run or capture when it happens again, to assist in debugging?

Thanks!

**Comment by holahula** [comment]
Closing - stale issue. If it persists in `> v1.0.0` please re-open an issue
