### ISSUE TITLE
Unable to Export Account Address Due to Limited Disk Space

### ISSUE THREAD

**Issue by airj1012** [iron-fish/ironfish#2328]
### What happened?

_Pulling from a different thread where this was previously documented but was a separate bug. I was unable to export my account address due to limited disk space and was also recognized that the account database couldn't be reset through normal commands._

@hughy "This is definitely a bug, and prevents even resetting the account database through normal commands!" 

Very similar. I initially added a node on my C: drive. Realized I didn't have enough room on that drive and moved (or created) a node on my D: drive. Unknowingly (new to nodes) I realized I was mining to my address on the C: node and thought (although probably incorrectly) I needed to be 100% synced on my C: node to receive the transactions (although I don't have enough disk space to get too 100%). I believe that I tried to move over the chain database from my working node to this node when I encountered the same error. Trying to get my node on C to function so I can export my address.

Version 0.1.49 @ https://github.com/iron-fish/ironfish/commit/ec57ed37ad7b484fb0e3573e57f3fb45bd886e7d
Node Name airj1012
Graffiti airj1012
Peer Identity 8MGPwIwQioxKHhM7qse2p4LaMY4qyT0GSG9pSQcSUko=
Peer Agent ironfish/0.1.49/ec57ed3
Peer Port 9033
Bootstrap test.bn1.ironfish.network

Error: getLatestHeadHash: No header found for 0000000000093f219e98868b0c10e8453ca0552599b8c0e828730e634f8b1487
at Function.isNotNull (C:\Users\micha\AppData\Roaming\npm\node_modules\ironfish\node_modules@ironfish\sdk\build\src\assert.js:23:19)
at Wallet.getLatestHeadHash (C:\Users\micha\AppData\Roaming\npm\node_modules\ironfish\node_modules@ironfish\sdk\build\src\wallet\wallet.js:766:29)
at async Wallet.load (C:\Users\micha\AppData\Roaming\npm\node_modules\ironfish\node_modules@ironfish\sdk\build\src\wallet\wallet.js:127:36)
at async Wallet.open (C:\Users\micha\AppData\Roaming\npm\node_modules\ironfish\node_modules@ironfish\sdk\build\src\wallet\wallet.js:112:9)
at async IronfishNode.openDB (C:\Users\micha\AppData\Roaming\npm\node_modules\ironfish\node_modules@ironfish\sdk\build\src\node.js:185:13)
at async Object.waitForOpen (C:\Users\micha\AppData\Roaming\npm\node_modules\ironfish\node_modules@ironfish\sdk\build\src\utils\node.js:16:13)
at async Start.start (C:\Users\micha\AppData\Roaming\npm\node_modules\ironfish\build\src\commands\start.js:96:9)
at async Start.run (C:\Users\micha\AppData\Roaming\npm\node_modules\ironfish\build\src\command.js:24:13)
at async Start._run (C:\Users\micha\AppData\Roaming\npm\node_modules\ironfish\node_modules@oclif\core\lib\command.js:81:22)
at async Config.runCommand (C:\Users\micha\AppData\Roaming\npm\node_modules\ironfish\node_modules@oclif\core\lib\config\config.js:272:25)

### Version

0.1.49

### Graffiti

airj1012

**Comment by airj1012** [comment]
Additional details on this bug can be found here - https://github.com/iron-fish/ironfish/issues/2304#issuecomment-1270585436

**Comment by airj1012** [comment]
Never received bug points for this issue. Was provided instructions to submit a request for points here.

https://github.com/iron-fish/ironfish/issues/2304#issuecomment-1275041326

**Comment by hughy** [comment]
The underlying issue for the `getLatestHeadHash` error was fixed in #2462

Please reach out on Discord if you're still missing points for this issue!
