### ISSUE TITLE
Uncertain balance value

### ISSUE THREAD

**Issue by Shekelme** [iron-fish/ironfish#2362]
### What happened?

A bug happened! It seems that ironfish himself does not fully know what kind of balance he has for deposits. Below is the contents of the terminal, all commands are executed within 1-2 minutes, sequentially one after another.

### Version

v0.1.49

### Debug output

```shell
Iron Fish version                  0.1.49 @ ec57ed3
Iron Fish library                  0.0.26 @ ec57ed3
Operating system                   Linux x64
CPU model(s)                       AMD Ryzen Threadripper PRO 3955WX 16-Cores
CPU threads                        32
RAM total                          503.53 GiB
Heap total                         16.01 GiB
Node version                       v16.17.0
ironfish in PATH                   true
Garbage Collector Exposed          false
Telemetry enabled                  true
Node name                          len01
Block graffiti                     saturnia
Account 5ba130 uuid                5ba13036-a204-4130-8c00-c06672b46dfd
Account 5ba130 name                default
Account 5ba130 head hash           0000000000001713dde1be099e442be1d30f420a2ff0fcf72f839a8e56f59fe3
Account 5ba130 head in chain       true
Account 5ba130 sequence            231587
```

### Relevant log output

```shell
admfc@lenovo1:~$ ironfish accounts:balance
Account: default (5ba1303)
Balance: $IRON 1,114.55697440
admfc@lenovo1:~$ ironfish deposit

Your balance is $IRON 1,114.55697440 ($ORE 111,455,697,440).

You are about to send $IRON 0.10000000 ($ORE 10,000,000) plus a transaction fee of $IRON 0.00000663 ($ORE 663) to the Iron Fish deposit account.
Your remaining balance after this transaction will be $IRON 1,114.45696777 ($ORE 111,445,696,777).
The memo will contain the graffiti "saturnia".

* This action is NOT reversible *

Do you confirm (Y/N)?: Y
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s
An error occurred while sending the transaction.
 ›   Error: Request failed (400) insufficient-balance: Your balance changed while creating a transaction.
admfc@lenovo1:~$
admfc@lenovo1:~$ ironfish accounts:balance
Account: default (5ba1303)
Balance: $IRON 30.25182280
admfc@lenovo1:~$ ironfish deposit

Your balance is $IRON 30.25182280 ($ORE 3,025,182,280).

You are about to send $IRON 0.10000000 ($ORE 10,000,000) plus a transaction fee of $IRON 0.00000663 ($ORE 663) to the Iron Fish deposit account.
Your remaining balance after this transaction will be $IRON 30.15181617 ($ORE 3,015,181,617).
The memo will contain the graffiti "saturnia".

* This action is NOT reversible *

Do you confirm (Y/N)?: Y
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s
An error occurred while sending the transaction.
 ›   Error: Request failed (400) insufficient-balance: Your balance changed while creating a transaction.
admfc@lenovo1:~$ ironfish accounts:balance
Account: default (5ba1303)
Balance: $IRON 13.37789300
admfc@lenovo1:~$ ironfish deposit

Your balance is $IRON 175.54624726 ($ORE 17,554,624,726).

You are about to send $IRON 0.10000000 ($ORE 10,000,000) plus a transaction fee of $IRON 0.00000663 ($ORE 663) to the Iron Fish deposit account.
Your remaining balance after this transaction will be $IRON 175.44624063 ($ORE 17,544,624,063).
The memo will contain the graffiti "saturnia".

* This action is NOT reversible *

Do you confirm (Y/N)?: Y
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s
An error occurred while sending the transaction.
 ›   Error: Request failed (400) insufficient-balance: Your balance changed while creating a transaction.
admfc@lenovo1:~$ ironfish accounts:balance
Account: default (5ba1303)
Balance: $IRON 13.37789300
```

### Graffiti

saturnia

**Comment by Shekelme** [comment]
[ironfish_logs.txt](https://github.com/iron-fish/ironfish/files/9799870/ironfish_logs.txt)
Last 500 lines of log from that node.

**Comment by hughy** [comment]
@Shekelme are you still seeing balance issues? Version 0.1.50 included a change (#2399) that may have resolved this issue.

**Comment by Shekelme** [comment]
While I'm watching. It's hard to say anything. If old errors have been fixed, then at least few new ones have appeared... One day, maybe, I'll document them.

**Comment by Shekelme** [comment]
I will stop deposit on a couple of nodes now to check this problem.

**Comment by Shekelme** [comment]
For example I often find my `depositAll` interrupted with `Invalid transaction amount, -560000000`.

**Comment by Shekelme** [comment]
No, at least two nodes out of about thirty had to do a full rescan, because this command was not executed.
```
Repairing wallet for account default
Repairing expired transactions
Error: nullifierToNote mappings must have a corresponding decryptedNote
    at Function.isNotUndefined (/home/rabinovitch/.npm-global/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/assert.js:18:19)
    at /home/rabinovitch/.npm-global/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/wallet/account.js:213:37
    at async LevelupDatabase.withTransaction (/home/rabinovitch/.npm-global/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/storage/database/database.js:41:28)
    at async Account.expireTransaction (/home/rabinovitch/.npm-global/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/wallet/account.js:198:9)
    at async Repair.repairTransactions (/home/rabinovitch/.npm-global/lib/node_modules/ironfish/build/src/commands/accounts/repair.js:53:17)
    at async Repair.start (/home/rabinovitch/.npm-global/lib/node_modules/ironfish/build/src/commands/accounts/repair.js:18:9)
    at async Repair.run (/home/rabinovitch/.npm-global/lib/node_modules/ironfish/build/src/command.js:24:13)
    at async Repair._run (/home/rabinovitch/.npm-global/lib/node_modules/ironfish/node_modules/@oclif/core/lib/command.js:81:22)
    at async Config.runCommand (/home/rabinovitch/.npm-global/lib/node_modules/ironfish/node_modules/@oclif/core/lib/config/config.js:272:25)
    at async Object.run (/home/rabinovitch/.npm-global/lib/node_modules/ironfish/node_modules/@oclif/core/lib/main.js:76:5)
```

**Comment by hughy** [comment]
There's an issue with the ordering of functions in `accounts:repair`, resolved here: https://github.com/iron-fish/ironfish/pull/2630

One workaround is to run the command using v0.1.53, before upgrading and running it with v0.1.54
