### ISSUE TITLE
OpenError: Corruption: error in middle of record

### ISSUE THREAD

**Issue by belgeran** [iron-fish/ironfish#2404]
### What happened?

Had syncing issue like this:

Round peer 5/lWICV (ZK.Work) ancestor 00000...cbf04, syncing from 240702 -> 241433 (731) after 1 requests
Requesting 5 blocks starting at 00000...cbf04 (240702) from 5/lWICV (ZK.Work)
**Stopping sync from 5/lWICV (ZK.Work) due to WriteError: IO error: /home/ubuntu/.ironfish/databases/default/MANIFEST-14144313: Structure needs cleaning**
    at /home/ubuntu/.nvm/versions/node/v16.17.0/lib/node_modules/ironfish/node_modules/levelup/lib/levelup.js:274:23
Peer 5/lWICV (ZK.Work) disconnected (DISCONNECTED) while syncing.
Starting sync from rHBl0I/ (nodn.cn). work: +551510111294631153, ours: 240702, theirs: 241365
Finding ancestor using linear search on last 3 blocks starting at 00000...cbf04 (240702) from peer rHBl0I/ (nodn.cn) at 241365

So i Ctrl C to stop the node, which is what i've done for quite a few times when encountering the above error..

however this time i got this error:

OpenError: Corruption: error in middle of record
    at /home/ubuntu/.nvm/versions/node/v16.17.0/lib/node_modules/ironfish/node_modules/levelup/lib/levelup.js:119:23
    at /home/ubuntu/.nvm/versions/node/v16.17.0/lib/node_modules/ironfish/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
    at /home/ubuntu/.nvm/versions/node/v16.17.0/lib/node_modules/ironfish/node_modules/deferred-leveldown/deferred-leveldown.js:31:21
    at /home/ubuntu/.nvm/versions/node/v16.17.0/lib/node_modules/ironfish/node_modules/abstract-leveldown/abstract-leveldown.js:38:14

### Version

0.1.49

### Debug output

```shell
Database cannot be opened, skipping output that requires database.

OpenError: Corruption: error in middle of record
    at /home/ubuntu/.nvm/versions/node/v16.17.0/lib/node_modules/ironfish/node_modules/levelup/lib/levelup.js:119:23
    at /home/ubuntu/.nvm/versions/node/v16.17.0/lib/node_modules/ironfish/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
    at /home/ubuntu/.nvm/versions/node/v16.17.0/lib/node_modules/ironfish/node_modules/deferred-leveldown/deferred-leveldown.js:31:21
    at /home/ubuntu/.nvm/versions/node/v16.17.0/lib/node_modules/ironfish/node_modules/abstract-leveldown/abstract-leveldown.js:38:14

Iron Fish version               0.1.49 @ ec57ed3
Iron Fish library               0.0.26 @ ec57ed3
Operating system                Linux x64
CPU model(s)                    Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
CPU threads                     8
RAM total                       15.30 GiB
Heap total                      2.01 GiB
Node version                    v16.17.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       iron_fish
Block graffiti                  iron_fish
```

### Relevant log output

```shell
Added block seq: 240680, hash: 00000...96009, txs: 301, progress: 99.69%, time: 5034.4ms
Requesting 5 blocks starting at 00000...2045a (240682) from LsRo5lq (ironfserv)
Requesting 5 blocks starting at 00000...09167 (240687) from LsRo5lq (ironfserv)
Requesting 5 blocks starting at 00000...9d604 (240692) from LsRo5lq (ironfserv)
Requesting 5 blocks starting at 00000...ceffe (240697) from LsRo5lq (ironfserv)
Added block seq: 240700, hash: 00000...a1d3f, txs: 301, progress: 99.69%, time: 3917.8ms
Requesting 5 blocks starting at 00000...cbf04 (240702) from LsRo5lq (ironfserv)
Stopping sync from LsRo5lq (ironfserv) due to WriteError: IO error: /home/ubuntu/.ironfish/databases/default/MANIFEST-14144313: Structure needs cleaning
    at /home/ubuntu/.nvm/versions/node/v16.17.0/lib/node_modules/ironfish/node_modules/levelup/lib/levelup.js:274:23
Peer LsRo5lq (ironfserv) disconnected (DISCONNECTED) while syncing.
Starting sync from zfaVIIk (cross). work: +555535600748158538, ours: 240702, theirs: 241428
Finding ancestor using linear search on last 3 blocks starting at 00000...cbf04 (240702) from peer zfaVIIk (cross) at 241428
Found peer zfaVIIk (cross) ancestor 00000...cbf04, syncing from 240702 -> 241428 (726) after 1 requests
Requesting 5 blocks starting at 00000...cbf04 (240702) from zfaVIIk (cross)
Peer zfaVIIk (cross) disconnected (DISCONNECTED) while syncing.
Starting sync from X/Yd9dM (Romko). work: +544308731248073922, ours: 240702, theirs: 241356
Finding ancestor using linear search on last 3 blocks starting at 00000...cbf04 (240702) from peer X/Yd9dM (Romko) at 241356
Found peer X/Yd9dM (Romko) ancestor 00000...cbf04, syncing from 240702 -> 241356 (654) after 1 requests
Requesting 5 blocks starting at 00000...cbf04 (240702) from X/Yd9dM (Romko)
Peer X/Yd9dM (Romko) disconnected (DISCONNECTED) while syncing.
Starting sync from jYsKdvE (Durge). work: +580390846856037719, ours: 240702, theirs: 241428
Finding ancestor using linear search on last 3 blocks starting at 00000...cbf04 (240702) from peer jYsKdvE (Durge) at 241428
Found peer jYsKdvE (Durge) ancestor 00000...cbf04, syncing from 240702 -> 241428 (726) after 1 requests
Requesting 5 blocks starting at 00000...cbf04 (240702) from jYsKdvE (Durge)
Stopping sync from jYsKdvE (Durge) due to WriteError: IO error: /home/ubuntu/.ironfish/databases/default/MANIFEST-14144313: Structure needs cleaning
    at /home/ubuntu/.nvm/versions/node/v16.17.0/lib/node_modules/ironfish/node_modules/levelup/lib/levelup.js:274:23
Peer jYsKdvE (Durge) disconnected (DISCONNECTED) while syncing.
Starting sync from qs3Ioyx (sethester). work: +591479667701957574, ours: 240702, theirs: 241431
Finding ancestor using linear search on last 3 blocks starting at 00000...cbf04 (240702) from peer qs3Ioyx (sethester) at 241431
Found peer qs3Ioyx (sethester) ancestor 00000...cbf04, syncing from 240702 -> 241431 (729) after 1 requests
Requesting 5 blocks starting at 00000...cbf04 (240702) from qs3Ioyx (sethester)
Stopping sync from qs3Ioyx (sethester) due to WriteError: IO error: /home/ubuntu/.ironfish/databases/default/MANIFEST-14144313: Structure needs cleaning
    at /home/ubuntu/.nvm/versions/node/v16.17.0/lib/node_modules/ironfish/node_modules/levelup/lib/levelup.js:274:23
Peer qs3Ioyx (sethester) disconnected (DISCONNECTED) while syncing.
Starting sync from pEZeP3n (tetsugyo). work: +604294028657188341, ours: 240702, theirs: 241431
Finding ancestor using linear search on last 3 blocks starting at 00000...cbf04 (240702) from peer pEZeP3n (tetsugyo) at 241431
Found peer pEZeP3n (tetsugyo) ancestor 00000...cbf04, syncing from 240702 -> 241431 (729) after 1 requests
Requesting 5 blocks starting at 00000...cbf04 (240702) from pEZeP3n (tetsugyo)
Stopping sync from pEZeP3n (tetsugyo) due to WriteError: IO error: /home/ubuntu/.ironfish/databases/default/MANIFEST-14144313: Structure needs cleaning
    at /home/ubuntu/.nvm/versions/node/v16.17.0/lib/node_modules/ironfish/node_modules/levelup/lib/levelup.js:274:23
Peer pEZeP3n (tetsugyo) disconnected (DISCONNECTED) while syncing.
Starting sync from ETnmLC+ (freem). work: +605102420356168884, ours: 240702, theirs: 241432
Finding ancestor using linear search on last 3 blocks starting at 00000...cbf04 (240702) from peer ETnmLC+ (freem) at 241432
Found peer ETnmLC+ (freem) ancestor 00000...cbf04, syncing from 240702 -> 241432 (730) after 1 requests
Requesting 5 blocks starting at 00000...cbf04 (240702) from ETnmLC+ (freem)
Peer ETnmLC+ (freem) disconnected (DISCONNECTED) while syncing.
Starting sync from hUuqUXN (hammo). work: +594665932706371406, ours: 240702, theirs: 241419
Finding ancestor using linear search on last 3 blocks starting at 00000...cbf04 (240702) from peer hUuqUXN (hammo) at 241419
Found peer hUuqUXN (hammo) ancestor 00000...cbf04, syncing from 240702 -> 241419 (717) after 1 requests
Requesting 5 blocks starting at 00000...cbf04 (240702) from hUuqUXN (hammo)
Stopping sync from hUuqUXN (hammo) due to WriteError: IO error: /home/ubuntu/.ironfish/databases/default/MANIFEST-14144313: Structure needs cleaning
    at /home/ubuntu/.nvm/versions/node/v16.17.0/lib/node_modules/ironfish/node_modules/levelup/lib/levelup.js:274:23
Peer hUuqUXN (hammo) disconnected (DISCONNECTED) while syncing.
Starting sync from 5/lWICV (ZK.Work). work: +596269774754466995, ours: 240702, theirs: 241433
Finding ancestor using linear search on last 3 blocks starting at 00000...cbf04 (240702) from peer 5/lWICV (ZK.Work) at 241433
Found peer 5/lWICV (ZK.Work) ancestor 00000...cbf04, syncing from 240702 -> 241433 (731) after 1 requests
Requesting 5 blocks starting at 00000...cbf04 (240702) from 5/lWICV (ZK.Work)
Stopping sync from 5/lWICV (ZK.Work) due to WriteError: IO error: /home/ubuntu/.ironfish/databases/default/MANIFEST-14144313: Structure needs cleaning
    at /home/ubuntu/.nvm/versions/node/v16.17.0/lib/node_modules/ironfish/node_modules/levelup/lib/levelup.js:274:23
Peer 5/lWICV (ZK.Work) disconnected (DISCONNECTED) while syncing.
Starting sync from rHBl0I/ (nodn.cn). work: +551510111294631153, ours: 240702, theirs: 241365
Finding ancestor using linear search on last 3 blocks starting at 00000...cbf04 (240702) from peer rHBl0I/ (nodn.cn) at 241365
Found peer rHBl0I/ (nodn.cn) ancestor 00000...cbf04, syncing from 240702 -> 241365 (663) after 1 requests
Requesting 5 blocks starting at 00000...cbf04 (240702) from rHBl0I/ (nodn.cn)
Peer rHBl0I/ (nodn.cn) disconnected (DISCONNECTED) while syncing.
Starting sync from l1kD8FB (LVB). work: +597866187028575255, ours: 240702, theirs: 241423
Finding ancestor using linear search on last 3 blocks starting at 00000...cbf04 (240702) from peer l1kD8FB (LVB) at 241423
Found peer l1kD8FB (LVB) ancestor 00000...cbf04, syncing from 240702 -> 241423 (721) after 1 requests
Requesting 5 blocks starting at 00000...cbf04 (240702) from l1kD8FB (LVB)
Peer l1kD8FB (LVB) disconnected (DISCONNECTED) while syncing.
Starting sync from rHBl0I/ (nodn.cn). work: +554728934240915537, ours: 240702, theirs: 241369
Finding ancestor using linear search on last 3 blocks starting at 00000...cbf04 (240702) from peer rHBl0I/ (nodn.cn) at 241369
Found peer rHBl0I/ (nodn.cn) ancestor 00000...cbf04, syncing from 240702 -> 241369 (667) after 1 requests
Requesting 5 blocks starting at 00000...cbf04 (240702) from rHBl0I/ (nodn.cn)
Peer rHBl0I/ (nodn.cn) disconnected (DISCONNECTED) while syncing.
^CShutting down node after SIGINT
Not connected to the Iron Fish network
ubuntu@ubuntu:~$ 
ubuntu@ubuntu:~$ 
ubuntu@ubuntu:~$ ironfish start

                                           
::::::::::          :::::::::::::::::         
::::::::::::       :::::::::::::::::::        
:::::::::::::     :::::::::::::::::::::       
::::::::::::::   ::::::::::::::::::::::::     
 ::::::::::::: ::::::::::        :::::::::    
   :::::::::::::::::::::          ::::::::::  
   :::::::::::::::::::::          :::::::::   
 ::::::::::::: ::::::::::        :::::::::    
::::::::::::::   ::::::::::::::::::::::::     
:::::::::::::     :::::::::::::::::::::       
::::::::::::       :::::::::::::::::::        
::::::::::           ::::::::::::::::         

Version       0.1.49 @ ec57ed3
Node Name     iron_fish
Graffiti      iron_fish
Peer Identity 4k4nXe5KE9gKEdguyxoqkc68vjmdwR3L0LjSW0IXokk=
Peer Agent    ironfish/0.1.49/ec57ed3
Peer Port     9033
Bootstrap     test.bn1.ironfish.network
 
OpenError: Corruption: error in middle of record
    at /home/ubuntu/.nvm/versions/node/v16.17.0/lib/node_modules/ironfish/node_modules/levelup/lib/levelup.js:119:23
    at /home/ubuntu/.nvm/versions/node/v16.17.0/lib/node_modules/ironfish/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
    at /home/ubuntu/.nvm/versions/node/v16.17.0/lib/node_modules/ironfish/node_modules/deferred-leveldown/deferred-leveldown.js:31:21
    at /home/ubuntu/.nvm/versions/node/v16.17.0/lib/node_modules/ironfish/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
```

### Graffiti

iron_fish

**Comment by hughy** [comment]
@belgeran , `Structure needs cleaning` often indicates file system corruption on Linux.

You may need to run `chain:download` with a fresh datadir, and then copy the data over to your database at `/home/ubuntu/.ironfish/databases/default`
