### ISSUE TITLE
Error: ProvingError     at Transaction.takeReference

### ISSUE THREAD

**Issue by mumu714** [iron-fish/ironfish#2405]
### What happened?

Account rescan error.
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/99628484/197478363-9be4a3b9-edfb-4643-8fde-f0cc9d5c3963.png">

### Version

v0.1.49

### Debug output

```shell
/home/ps/ironfish/ironfish/ironfish/build/src/primitives/transaction.js:60
            this.transactionPosted = new rust_nodejs_1.TransactionPosted(this.transactionPostedSerialized);
                                     ^

Error: ProvingError
    at Transaction.takeReference (/home/ps/ironfish/ironfish/ironfish/build/src/primitives/transaction.js:60:38)
    at Transaction.withReference (/home/ps/ironfish/ironfish/ironfish/build/src/primitives/transaction.js:78:34)
    at Wallet.syncTransaction (/home/ps/ironfish/ironfish/ironfish/build/src/wallet/wallet.js:274:27)
    at /home/ps/ironfish/ironfish/ironfish/build/src/wallet/wallet.js:59:28
    at async Promise.all (index 0)
    at async Event.emitAsync (/home/ps/ironfish/ironfish/ironfish/build/src/event.js:64:9)
    at async ChainProcessor.add (/home/ps/ironfish/ironfish/ironfish/build/src/chainProcessor.js:39:9)
    at async ChainProcessor.update (/home/ps/ironfish/ironfish/ironfish/build/src/chainProcessor.js:84:13)
    at async Wallet.updateHead (/home/ps/ironfish/ironfish/ironfish/build/src/wallet/wallet.js:84:37)
    at async Wallet.eventLoop (/home/ps/ironfish/ironfish/ironfish/build/src/wallet/wallet.js:183:9) {
  code: 'GenericFailure'
}
```

### Graffiti

muyao

**Comment by ygao76** [comment]
I just tried accounts:rescan, I dont have any error. Can you try yarn install or pull the latest ironfish v0.1.50

**Comment by hairtail** [comment]
> I just tried accounts:rescan, I dont have any error. Can you try yarn install or pull the latest ironfish v0.1.50
Same error during rescan, running on version 0.1.51.
