### ISSUE TITLE
Node crashed after issuing `accounts:rescan` with `"Expected value not to be undefined"`

### ISSUE THREAD

**Issue by neuronull** [iron-fish/ironfish#2446]
### What happened?

My node was experiencing the known issue #2322 where the balance increases after sending transactions.

From discord I saw the recommendation is to do a rescan, so I followed the instructions and backed up my account info using:

```
$ ironfish accounts:export
...
```

Then I ran the rescan command:

```
$ ironfish accounts:rescan --reset

```

Unfortunately I don't have the output from the rescan command, but it finished very quickly and I checked the return code with `echo $?` and it was zero.

It is not clear to me whether the rescan command completed normally or some error condition occurred there, as the displayed output on the CLI documentation does not include the `--reset` option so I presume that the output might be expected to be different from what the CLI documentation displays, but that is an unknown.

I monitored the node for a few minutes after the rescan command completed and everything seemed normal.

The next morning I checked on the node and noticed it had been offline 12 hours because of this crash :(
Backtrace is below.

### Version

v0.1.49

### Debug output

```shell
Iron Fish version               0.1.49 @ ec57ed3
Iron Fish library               0.0.26 @ ec57ed3
Operating system                Linux x64
CPU model(s)                    Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
CPU threads                     4
RAM total                       12.44 GiB
Heap total                      2.01 GiB
Node version                    v16.17.1
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
```

### Relevant log output

```shell
[19:22:22.140] [info] Added block seq: 248240, hash: 00000...00a09, txs: 301, progress: 99.99%, time: 46852.2ms
[19:32:50.712] [info] Requesting 20 blocks starting at 00000...3688e (248251) from D6kInSy (ironfish11)
/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/assert.js:18
            throw new Error(message || `Expected value not to be undefined`);
                  ^

Error: Expected value not to be undefined
    at Function.isNotUndefined (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/assert.js:18:19)
    at WalletDB.loadExpiredTransactions (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/wallet/walletdb/walletdb.js:269:29)
    at async Wallet.expireTransactions (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/wallet/wallet.js:581:44)
    at async Wallet.eventLoop (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/wallet/wallet.js:183:9)
```

### Graffiti

null

**Comment by NullSoldier** [comment]
A fix for this crash was released in v50.
