### ISSUE TITLE
RangeError: Invalid WebSocket frame: RSV2 and RSV3 must be clear

### ISSUE THREAD

**Issue by guilhermeysm** [iron-fish/ironfish#2447]
### What happened?

While I was syncing my node, an error ocurred as bellow and syncing stopped.

_Starting sync from 4e+EE6U (zinastya696). work: +55435509431776667428, ours: 69779, theirs: 247059
Finding ancestor using linear search on last 3 blocks starting at 00000...aa578 (69779) from peer 4e+EE6U (zinastya696) at 247059
Found peer 4e+EE6U (zinastya696) ancestor 00000...aa578, syncing from 69779 -> 247059 (177280) after 1 requests
Requesting 20 blocks starting at 00000...aa578 (69779) from 4e+EE6U (zinastya696)
node:events:491
      throw er; // Unhandled 'error' event
      ^

RangeError: Invalid WebSocket frame: RSV2 and RSV3 must be clear
    at Receiver.getInfo (C:\Users\guilh\AppData\Roaming\npm\node_modules\ironfish\node_modules\ws\lib\receiver.js:171:14)
    at Receiver.startLoop (C:\Users\guilh\AppData\Roaming\npm\node_modules\ironfish\node_modules\ws\lib\receiver.js:131:22)
    at Receiver._write (C:\Users\guilh\AppData\Roaming\npm\node_modules\ironfish\node_modules\ws\lib\receiver.js:78:10)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at Receiver.Writable.write (node:internal/streams/writable:336:10)
    at Socket.socketOnData (C:\Users\guilh\AppData\Roaming\npm\node_modules\ironfish\node_modules\ws\lib\websocket.js:920:35)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
Emitted 'error' event on WebSocket instance at:
    at Receiver.receiverOnError (C:\Users\guilh\AppData\Roaming\npm\node_modules\ironfish\node_modules\ws\lib\websocket.js:826:13)
    at Receiver.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'WS_ERR_UNEXPECTED_RSV_2_3',
  [Symbol(status-code)]: 1002
}_

In the .zip file bellow are "ws" directory content and LOG and MANIFEST files from the moment where error happened.
[ws.zip](https://github.com/iron-fish/ironfish/files/9894574/ws.zip)

### Version

v0.1.49

### Debug output

```shell
Iron Fish version                  0.1.49 @ ec57ed3
Iron Fish library                  0.0.26 @ ec57ed3
Operating system                   Windows_NT x64
CPU model(s)                       Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
CPU threads                        8
RAM total                          7.87 GiB
Heap total                         2.01 GiB
Node version                       v16.18.0
ironfish in PATH                   true
Garbage Collector Exposed          false
Telemetry enabled                  false
Node name
Block graffiti                     guilhermeysm
Account a46ce6 uuid                a46ce653-f929-4e1b-890d-f4807f56ca47
Account a46ce6 name                guilhermeysm
Account a46ce6 head hash           00000000000054253d594b9d58515a674633a1aeb1ea21be30525c70682c98cc
Account a46ce6 head in chain       true
Account a46ce6 sequence            78738
```

### Graffiti

guilhermeysm

**Comment by holahula** [comment]
Closing due to staleness. If the issue persists in versions `1.0.0+` - please file a new issue
