### ISSUE TITLE
No leaf found in the tree

### ISSUE THREAD

**Issue by limeahn** [iron-fish/ironfish#2448]
### What happened?

As I try to use chain:download, unknown bug happens to interfere with the download. This is repeated with the "ironfish start" command as well

### Version

0.1.49

### Debug output

```shell
root@DESKTOP-V0ONO5I:~/ironfish/ironfish-cli# yarn start chain:download
yarn run v1.22.19
$ yarn build && yarn start:js chain:download
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run chain:download
/root/ironfish/ironfish/src/merkletree/merkletree.ts:112
      throw new Error(`No leaf found in tree ${this.name} at index ${index}`)
            ^

Error: No leaf found in tree n at index 0
    at MerkleTree.getLeaf (/root/ironfish/ironfish/src/merkletree/merkletree.ts:112:13)
    at MerkleTree.get (/root/ironfish/ironfish/src/merkletree/merkletree.ts:99:13)
    at <anonymous> (/root/ironfish/ironfish/src/blockchain/blockchain.ts:978:26)
    at LevelupDatabase.withTransaction (/root/ironfish/ironfish/src/storage/database/database.ts:211:22)
    at Blockchain.saveConnect (/root/ironfish/ironfish/src/blockchain/blockchain.ts:1249:7)
    at Blockchain.saveBlock (/root/ironfish/ironfish/src/blockchain/blockchain.ts:1306:7)
    at Blockchain.addHeadToChain (/root/ironfish/ironfish/src/blockchain/blockchain.ts:719:5)
    at Blockchain.connect (/root/ironfish/ironfish/src/blockchain/blockchain.ts:584:7)
    at <anonymous> (/root/ironfish/ironfish/src/blockchain/blockchain.ts:345:18)
    at LevelupDatabase.withTransaction (/root/ironfish/ironfish/src/storage/database/database.ts:211:22)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Graffiti

limeahn

**Comment by danield9tqh** [comment]
@limeahn can you check to see what the size of your `.ironfish` folder is? We had a known issue where `chain:download` will silently fail if the machine does not have enough storage for the entire chain. How much storage does your machine have? It should need around 160GB of storage for the entire chain. 

This issue of silently failing has been fixed here https://github.com/iron-fish/ironfish/pull/2441 in the next release but I would suggest you increase your storage, delete your node's database (`~/.ironfish/databases`) and try running `chain:download` again.

**Comment by hughy** [comment]
Closing this issue as stale.
