### ISSUE TITLE
EncodingError: Number exceeds 2^53-1

### ISSUE THREAD

**Issue by cyberguy85** [iron-fish/ironfish#2471]
### What happened?

After node upgrade from 0.1.49 to 0.1.50 unable to start node. The below error is present in the logs: 

```
 WebSocket server started at :::9033
/usr/lib/node_modules/ironfish/node_modules/bufio/lib/encoding.js:61
  check((hi & 0xffe00000) === 0, off, 'Number exceeds 2^53-1');
  ^
EncodingError: Number exceeds 2^53-1 (offset=0).
    at Object.readU64 (/usr/lib/node_modules/ironfish/node_modules/bufio/lib/encoding.js:61:3)
    at BufferReader.readU64 (/usr/lib/node_modules/ironfish/node_modules/bufio/lib/reader.js:364:26)
    at new Transaction (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/primitives/transaction.js:21:38)
    at TransactionsValueEncoding.deserialize (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/blockchain/database/transactions.js:24:31)
    at LevelupStore.get (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/storage/levelup/store.js:43:39)
    at async LevelupTransaction.get (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/storage/levelup/transaction.js:63:23)
    at async Promise.all (index 1)
    at async /usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/blockchain/blockchain.js:511:44
    at async LevelupDatabase.withTransaction (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/storage/database/database.js:41:28)
    at async Blockchain.iterateBlockTransactions (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/blockchain/blockchain.js:789:23) {
  type: 'EncodingError',
  code: 'ERR_ENCODING'
} 
```

### Version

0.1.50

### Debug output

```shell
Iron Fish version                  0.1.50 @ 02939ae
Iron Fish library                  0.0.27 @ 02939ae
Operating system                   Linux x64
CPU model(s)                       AMD Ryzen 9 5950X 16-Core Processor
CPU threads                        8
RAM total                          3.83 GiB
Heap total                         1.92 GiB
Node version                       v16.17.0
ironfish in PATH                   true
Garbage Collector Exposed          false
Telemetry enabled                  true
Node name                          cyberguy23
Block graffiti                     cyberguy23
Account c6abbb uuid                c6abbb92-ef2d-4083-8b09-42f135a39d09
Account c6abbb name                zkworkwallet
Account c6abbb head hash           0000000000002c07376f637160ac940eae4645508f6cbd4dc905b57c00ffde2c
Account c6abbb head in chain       true
Account c6abbb sequence            251361
Account d00eda uuid                d00eda91-d416-44ae-982b-529dc4044630
Account d00eda name                default
Account d00eda head hash           0000000000002c07376f637160ac940eae4645508f6cbd4dc905b57c00ffde2c
Account d00eda head in chain       true
Account d00eda sequence            251361
Account f4d833 uuid                f4d833d2-d6b7-4e93-85fd-7ea8c2144b42
Account f4d833 name                deposit01
Account f4d833 head hash           0000000000002c07376f637160ac940eae4645508f6cbd4dc905b57c00ffde2c
Account f4d833 head in chain       true
Account f4d833 sequence            251361
Account f5cccb uuid                f5cccbb7-39ff-46ea-b802-d4f8fb680fc6
Account f5cccb name                deposit02
Account f5cccb head hash           0000000000002c07376f637160ac940eae4645508f6cbd4dc905b57c00ffde2c
Account f5cccb head in chain       true
Account f5cccb sequence            251361
```

### Relevant log output

```shell
Started IronFish Node.
                                           
::::::::::          :::::::::::::::::
::::::::::::       :::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::::   ::::::::::::::::::::::::
 ::::::::::::: ::::::::::        :::::::::
   :::::::::::::::::::::          ::::::::::
   :::::::::::::::::::::          :::::::::
 ::::::::::::: ::::::::::        :::::::::
::::::::::::::   ::::::::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::       :::::::::::::::::::
::::::::::           ::::::::::::::::
Version       0.1.50 @ 02939ae
Node Name     cyberguy23
Graffiti      cyberguy23
Peer Agent    ironfish/0.1.50/02939ae
Peer Port     9033
Bootstrap     test.bn1.ironfish.network
 
WebSocket server started at :::9033
Connected to the Iron Fish network
/usr/lib/node_modules/ironfish/node_modules/bufio/lib/encoding.js:61
  check((hi & 0xffe00000) === 0, off, 'Number exceeds 2^53-1');
  ^
EncodingError: Number exceeds 2^53-1 (offset=0).
    at Object.readU64 (/usr/lib/node_modules/ironfish/node_modules/bufio/lib/encoding.js:61:3)
    at BufferReader.readU64 (/usr/lib/node_modules/ironfish/node_modules/bufio/lib/reader.js:364:26)
    at new Transaction (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/primitives/transaction.js:21:38)
    at TransactionsValueEncoding.deserialize (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/blockchain/database/transactions.js:24:31)
    at LevelupStore.get (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/storage/levelup/store.js:43:39)
    at async LevelupTransaction.get (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/storage/levelup/transaction.js:63:23)
    at async Promise.all (index 1)
    at async /usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/blockchain/blockchain.js:511:44
    at async LevelupDatabase.withTransaction (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/storage/database/database.js:41:28)
    at async Blockchain.iterateBlockTransactions (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/blockchain/blockchain.js:789:23) {
  type: 'EncodingError',
  code: 'ERR_ENCODING'
}
ironfishd.service: Main process exited, code=exited, status=1/FAILURE
ironfishd.service: Failed with result 'exit-code'.
ironfishd.service: Consumed 2.284s CPU time.
```

### Graffiti

cyberguy23

**Comment by NullSoldier** [comment]
Thanks for the bug report, we're looking into it.

**Comment by wd021** [comment]
don't think this is related to 0.1.50 update, old error.

**Comment by tolyod** [comment]
have same error on `Version       0.1.55 @ 38d2528`, after `ironfish chain:download` and then `ironfish start`

**Comment by tolyod** [comment]
more details
```
$ docker run --rm --tty --interactive --network host --volume /home/user/.ironfish:/root/.ironfish ghcr.io/iron-fish/ironfish:latest start


::::::::::          :::::::::::::::::
::::::::::::       :::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::::   ::::::::::::::::::::::::
 ::::::::::::: ::::::::::        :::::::::
   :::::::::::::::::::::          ::::::::::
   :::::::::::::::::::::          :::::::::
 ::::::::::::: ::::::::::        :::::::::
::::::::::::::   ::::::::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::       :::::::::::::::::::
::::::::::           ::::::::::::::::

Version       0.1.55 @ 38d2528
Node Name     NTG18
Graffiti      NTG18
Peer Identity L74xkQqZPV19RRFE2s47MvLoTwgXnfvaLDw6iVJANE4=
Peer Agent    ironfish/0.1.55/38d2528
Peer Port     9033
Bootstrap     NONE

EncodingError: Number exceeds 2^53-1 (offset=144).
    at Object.readU64 (/usr/src/app/node_modules/bufio/lib/encoding.js:96:3)
    at BufferReader.readU64 (/usr/src/app/node_modules/bufio/lib/reader.js:394:26)
    at HeaderEncoding.deserialize (/usr/src/app/node_modules/@ironfish/sdk/build/src/blockchain/database/headers.js:41:34)
    at LevelupStore.get (/usr/src/app/node_modules/@ironfish/sdk/build/src/storage/levelup/store.js:42:35)
    at async Blockchain.getHeader (/usr/src/app/node_modules/@ironfish/sdk/build/src/blockchain/blockchain.js:631:17)
    at async Blockchain.open (/usr/src/app/node_modules/@ironfish/sdk/build/src/blockchain/blockchain.js:170:29)
    at async IronfishNode.openDB (/usr/src/app/node_modules/@ironfish/sdk/build/src/node.js:193:13)
    at async Object.waitForOpen (/usr/src/app/node_modules/@ironfish/sdk/build/src/utils/node.js:16:13)
    at async Start.start (/usr/src/app/build/src/commands/start.js:105:9)
    at async Start.run (/usr/src/app/build/src/command.js:24:13)
    ```

**Comment by holahula** [comment]
Closing - dupe
