### ISSUE TITLE
Error: libdatachannel error while creating datachannel: Failed to gather local ICE candidates

### ISSUE THREAD

**Issue by guilhermeysm** [iron-fish/ironfish#2480]
### What happened?

Error while syncing.

Added block seq: 88060, hash: 00000...3bd86, txs: 2, progress: 35.33%, time: 667.8ms
C:\Users\guilh\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\network\peers\connections\webRtcConnection.js:133
            this.initializeDataChannel(this.peer.createDataChannel(''));
                                                 ^

Error: libdatachannel error while creating datachannel: Failed to gather local ICE candidates
    at PeerConnection.createDataChannel (<anonymous>)
    at new WebRtcConnection (C:\Users\guilh\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\network\peers\connections\webRtcConnection.js:133:50)
    at PeerManager.initWebRtcConnection (C:\Users\guilh\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\network\peers\peerManager.js:190:28)
    at PeerManager.handleSignalRequestMessage (C:\Users\guilh\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\network\peers\peerManager.js:900:14)
    at PeerManager.handleMessage (C:\Users\guilh\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\network\peers\peerManager.js:624:18)
    at C:\Users\guilh\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\network\peers\peerManager.js:496:18
    at Event.emitAsync (C:\Users\guilh\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\event.js:61:39)
    at Event.emit (C:\Users\guilh\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\event.js:52:19)
    at messageHandler (C:\Users\guilh\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\network\peers\peer.js:419:32)
    at Event.emitAsync (C:\Users\guilh\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\event.js:61:39)

### Version

v0.1.49

### Debug output

```shell
Iron Fish version                  0.1.49 @ ec57ed3
Iron Fish library                  0.0.26 @ ec57ed3
Operating system                   Windows_NT x64
CPU model(s)                       Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
CPU threads                        8
RAM total                          7.87 GiB
Heap total                         2.01 GiB
Node version                       v16.18.0
ironfish in PATH                   true
Garbage Collector Exposed          false
Telemetry enabled                  false
Node name
Block graffiti                     guilhermeysm
Account a46ce6 uuid                a46ce653-f929-4e1b-890d-f4807f56ca47
Account a46ce6 name                guilhermeysm
Account a46ce6 head hash           0000000000002b612fed98507572d93cd389394ece79222cceeba75e320c3083
Account a46ce6 head in chain       true
Account a46ce6 sequence            88061
```

### Relevant log output

```shell
2022/10/30-20:23:12.395 b3c Recovering log #583009
2022/10/30-20:23:12.515 b3c Delete type=0 #583009
2022/10/30-20:23:12.515 b3c Delete type=2 #583010
2022/10/30-20:23:12.517 b3c Delete type=3 #583007
2022/10/30-20:23:12.518 39e4 Compacting 1@2 + 38@3 files
2022/10/30-20:23:12.847 39e4 Generated table #583012@2: 1698 keys, 560131 bytes
2022/10/30-20:23:13.381 39e4 Generated table #583013@2: 1795 keys, 592783 bytes
2022/10/30-20:23:13.691 39e4 Generated table #583014@2: 1641 keys, 541944 bytes
2022/10/30-20:23:14.258 39e4 Generated table #583015@2: 1636 keys, 540258 bytes
2022/10/30-20:23:14.625 39e4 Generated table #583016@2: 1722 keys, 568665 bytes
2022/10/30-20:23:14.921 39e4 Generated table #583017@2: 1792 keys, 591763 bytes
2022/10/30-20:23:15.224 39e4 Generated table #583018@2: 1696 keys, 560081 bytes
2022/10/30-20:23:15.479 39e4 Generated table #583019@2: 1655 keys, 546565 bytes
2022/10/30-20:23:15.724 39e4 Generated table #583020@2: 1646 keys, 543574 bytes
2022/10/30-20:23:16.058 39e4 Generated table #583021@2: 1761 keys, 581539 bytes
```

### Graffiti

guilhermeysm

**Comment by danield9tqh** [comment]
@guilhermeysm I am going to close this in favor of the other one you opened since it seems like these are the same issue https://github.com/iron-fish/ironfish/issues/2482
