### ISSUE TITLE
Ironfish Node Crashed - Will not restart

### ISSUE THREAD

**Issue by ADADarkpool** [iron-fish/ironfish#2533]
### What happened?

I am running several accounts because deposit-all is too slow on just one account to finish in time.

Backend node has been running fine for at least 2 weeks.  Was transferring some stuff around.  Switched default accounts with accounts:use XYZ.  I think that is when the node crashed.

Running Docker 0.1.51

### Version

v0.1.51

### Debug output

```shell
Version       0.1.51 @ 67da183
Node Name     NONE
Graffiti      XXXX
Peer Identity 1unmXZG7Q8An54gVnhHozcnDuGBPv+pHdZomIkAu/HY=
Peer Agent    ironfish/0.1.51/67da183
Peer Port     9033
Bootstrap     test.bn1.ironfish.network
 
WebSocket server started at :::9033
/usr/src/app/node_modules/@ironfish/sdk/build/src/assert.js:18
            throw new Error(message || `Expected value not to be undefined`);
                  ^

Error: nullifierToNote mappings must have a corresponding decryptedNote
    at Function.isNotUndefined (/usr/src/app/node_modules/@ironfish/sdk/build/src/assert.js:18:19)
    at /usr/src/app/node_modules/@ironfish/sdk/build/src/wallet/account.js:213:37
    at async LevelupDatabase.withTransaction (/usr/src/app/node_modules/@ironfish/sdk/build/src/storage/database/database.js:41:28)
    at async Account.expireTransaction (/usr/src/app/node_modules/@ironfish/sdk/build/src/wallet/account.js:198:9)
    at async Wallet.expireTransactions (/usr/src/app/node_modules/@ironfish/sdk/build/src/wallet/wallet.js:601:17)
    at async Wallet.eventLoop (/usr/src/app/node_modules/@ironfish/sdk/build/src/wallet/wallet.js:183:9)
```

### Graffiti

DarkPool

**Comment by pasha121** [comment]
I have the same error.
I caught it at version 0.1.50 and sometimes node worked and let me do depositAll..
But then it crashed again

**Comment by hughy** [comment]
Closed because we've made significant changes to the wallet (e.g., #2783) since the end of Phase 2 intended to address issues like this one.
