### ISSUE TITLE
Error during connection to miner pool

### ISSUE THREAD

**Issue by PavelMal** [iron-fish/ironfish#2543]
### What happened?

What happened?

During the execution the following command: 

`ironfish miners:start --pool pool.ironfish.network --address d435d4477471a5795bbc62017a5234d844d325e49acb37a86bb402889f105e92beb8970bf1513d3cda210f`

I've got an error: 

```
Error: The module '/usr/local/lib/node_modules/ironfish/node_modules/segfault-handler/build/Release/segfault-handler.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 108. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/usr/local/lib/node_modules/ironfish/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/local/lib/node_modules/ironfish/node_modules/segfault-handler/index.js:3:37)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'ERR_DLOPEN_FAILED'
}
```

### Version

-  0.1.51 npm package version  
- 16.13.2 node.js version

### Graffiti

PaulBro

**Comment by holahula** [comment]
Closing - after ironfish upgrades, the pkg needs to be re-built
