### ISSUE TITLE
rpc:status is breaking when node is not running

### ISSUE THREAD

**Issue by aditya-manit** [iron-fish/ironfish#2561]
### What happened?

rpc:status works fine when node is running but when its stopped the command breaks

### Version

0.1.51 (6d57e3832d15fc7f84eb20bc831b2c4ae195b372)

### Debug output

```shell
/Users/aditya.verma/WebStromProjects/ironfish/ironfish/src/storage/levelup/database.ts:49
      throw new Error('Database is not open. Call IDatabase.open() first')
            ^

Error: Database is not open. Call IDatabase.open() first
    at LevelupDatabase.get levelup (/Users/aditya.verma/WebStromProjects/ironfish/ironfish/src/storage/levelup/database.ts:49:13)
    at LevelupStore.getAllIter (/Users/aditya.verma/WebStromProjects/ironfish/ironfish/src/storage/levelup/store.ts:124:28)
    at getAllIter.next (<anonymous>)
    at WalletDB.loadHeadHashes (/Users/aditya.verma/WebStromProjects/ironfish/ironfish/src/wallet/walletdb/walletdb.ts:266:42)
    at loadHeadHashes.next (<anonymous>)
    at Debug.outputRequiringDB (/Users/aditya.verma/WebStromProjects/ironfish/ironfish-cli/src/commands/debug.ts:96:43)
    at Debug.start (/Users/aditya.verma/WebStromProjects/ironfish/ironfish-cli/src/commands/debug.ts:48:51)
    at Debug.run (/Users/aditya.verma/WebStromProjects/ironfish/ironfish-cli/src/command.ts:76:7)
    at async Debug._run (/Users/aditya.verma/WebStromProjects/ironfish/ironfish-cli/node_modules/@oclif/core/lib/command.js:81:22)
    at async Config.runCommand (/Users/aditya.verma/WebStromProjects/ironfish/ironfish-cli/node_modules/@oclif/core/lib/config/config.js:272:25)
```

### Relevant log output

```shell
TypeError: 'size' must be a(n) integer.
    at BufferReader.readBytes (/Users/aditya.verma/WebStromProjects/ironfish/node_modules/bufio/lib/reader.js:710:5)
    at <anonymous> (/Users/aditya.verma/WebStromProjects/ironfish/ironfish/src/primitives/transaction.ts:66:39)
    at Function.from (<anonymous>)
    at Transaction (/Users/aditya.verma/WebStromProjects/ironfish/ironfish/src/primitives/transaction.ts:62:25)
    at TransactionsValueEncoding.deserialize (/Users/aditya.verma/WebStromProjects/ironfish/ironfish/src/blockchain/database/transactions.ts:30:25)
    at LevelupStore.get (/Users/aditya.verma/WebStromProjects/ironfish/ironfish/src/storage/levelup/store.ts:71:33)
    at LevelupTransaction.get (/Users/aditya.verma/WebStromProjects/ironfish/ironfish/src/storage/levelup/transaction.ts:95:19)
    at async Promise.all (index 1)
    at <anonymous> (/Users/aditya.verma/WebStromProjects/ironfish/ironfish/src/blockchain/blockchain.ts:816:38)
    at LevelupDatabase.withTransaction (/Users/aditya.verma/WebStromProjects/ironfish/ironfish/src/storage/database/database.ts:211:22)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Graffiti

KingSuper

**Comment by holahula** [comment]
Closing due to staleness
