### ISSUE TITLE
IPC client crashes when connection is reset

### ISSUE THREAD

**Issue by NullSoldier** [iron-fish/ironfish#2567]
### What happened?

When the server closes, the IPCClient will crash some times.

### Version

v0.1.51

### Debug output

```shell
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version               0.1.51 @ 67da183
Iron Fish library               0.0.28 @ 67da183
Operating system                Darwin arm64
CPU model(s)                    Apple M1 Pro
CPU threads                     10
RAM total                       16.00 GiB
Heap total                      4.01 GiB
Node version                    v16.15.1
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       JASON💪💎🚀
Block graffiti                  JASON💪💎🚀
```

### Relevant log output

```shell
> ironfish peers -f

Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:817:11)
    at Socket._write (node:net:829:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at RpcIpcClient.send (/Users/jasonspafford/.nvm/versions/node/v16.15.1/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/rpc/clients/socketClient.js:243:21)
    at RpcIpcClient.request (/Users/jasonspafford/.nvm/versions/node/v16.15.1/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/rpc/clients/socketClient.js:229:14)
    at RpcIpcClient.getPeersStream (/Users/jasonspafford/.nvm/versions/node/v16.15.1/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/rpc/clients/client.js:69:21)
```
```


### Graffiti

JASON💪💎🚀

**Comment by depinwhale** [comment]
The RPC client layer has been rewritten since v0.1.51: `RpcIpcClient` is now a thin subclass of `RpcSocketClient` (`ironfish/src/rpc/clients/ipcClient.ts`), which registers persistent `error`/`close` handlers on the socket (`socketClient.ts`). The crash described here no longer applies to the current architecture. Suggest closing as obsolete.
