### ISSUE TITLE
[Node is not starting] "throw new Error(message || `Expected value not to be undefined`);"

### ISSUE THREAD

**Issue by pasha121** [iron-fish/ironfish#2615]
### What happened?

I have an errors since 0.1.50: sometimes node crashed when I have made operation "depositAll" and my node won't started some times.
After some time of errors during restarts node starts and working some time.
When I am trying to make some transactions node crashes and will not starting.

I think, that node starts after some timeout.

### Version

0.1.52

### Debug output

```shell
ironfish debug
Iron Fish version                  0.1.52 @ 1bf0c8e
Iron Fish library                  0.0.29 @ 1bf0c8e
Operating system                   Linux x64
CPU model(s)                       Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
CPU threads                        8
RAM total                          23.35 GiB
Heap total                         4.01 GiB
Node version                       v16.17.0
ironfish in PATH                   true
Garbage Collector Exposed          false
Telemetry enabled                  true
Node name                          fsck_node
Block graffiti                     fsck_node
Account 01aea9 uuid                01aea956-fd47-44da-a7a5-cf7aa5398881
Account 01aea9 name                wallet1
Account 01aea9 head hash           000000000000402efb3c491e92000547f3ad7721521e230f04621d9405a31f66
Account 01aea9 head in chain       true
Account 01aea9 sequence            275585
Account aa9b52 uuid                aa9b52aa-f420-4562-9217-3d46d78fe705
Account aa9b52 name                default
Account aa9b52 head hash           000000000000402efb3c491e92000547f3ad7721521e230f04621d9405a31f66
Account aa9b52 head in chain       true
Account aa9b52 sequence            275585
root@hf89:~# uname -a; df -h
Linux hf89 5.15.0-48-generic #54~20.04.1-Ubuntu SMP Thu Sep 1 16:17:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Filesystem                         Size  Used Avail Use% Mounted on
udev                                12G     0   12G   0% /dev
tmpfs                              2.4G  1.3M  2.4G   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv  115G   11G   99G  10% /
tmpfs                               12G     0   12G   0% /dev/shm
tmpfs                              5.0M     0  5.0M   0% /run/lock
tmpfs                               12G     0   12G   0% /sys/fs/cgroup
/dev/mapper/ubuntu--vg-data        251G   99G  152G  40% /data
/dev/loop1                          64M   64M     0 100% /snap/core20/1634
/dev/sda2                          1.5G  426M  958M  31% /boot
/dev/sda1                          1.1G  5.3M  1.1G   1% /boot/efi
/dev/loop2                          68M   68M     0 100% /snap/lxd/21835
/dev/loop3                          48M   48M     0 100% /snap/snapd/17336
/dev/loop4                          68M   68M     0 100% /snap/lxd/22753
tmpfs                              2.4G     0  2.4G   0% /run/user/1000
/dev/loop6                          64M   64M     0 100% /snap/core20/1695
/dev/loop0                          50M   50M     0 100% /snap/snapd/17576
```

### Relevant log output

```shell
This is the first error:
Nov 04 17:07:03 hf89 ironfish[22731]: Added block seq: 257880, hash: 00000...8074e, txs: 199, progress: 100.00%, time: 3377.3ms
Nov 04 17:10:09 hf89 ironfish[22731]: Reorganizing chain from 00000...e3238 (257882) for 00000...34583 (257882) on prev 00000...21eb7 (257881)
Nov 04 17:10:10 hf89 ironfish[22731]: Reorganized chain. blocks: 1, old: 00000...e3238 (257882), new: 00000...21eb7 (257881), fork: 00000...21eb7 (257881)
Nov 04 17:12:26 hf89 ironfish[22731]: Reorganizing chain from 00000...eeabd (257885) for 00000...da573 (257885) on prev 00000...5aea2 (257884)
Nov 04 17:12:26 hf89 ironfish[22731]: Reorganized chain. blocks: 1, old: 00000...eeabd (257885), new: 00000...5aea2 (257884), fork: 00000...5aea2 (257884)
Nov 04 17:17:57 hf89 ironfish[22731]: Added block to fork seq: 257886, head-seq: 257886, hash: 00000...df99e, head-hash: 00000...0df2e, work: 66837480645242147199, head-work: 668374884>
Nov 04 17:18:38 hf89 ironfish[22731]: Added block to fork seq: 257887, head-seq: 257888, hash: 00000...31be5, head-hash: 00000...f776d, work: 66838316962161236479, head-work: 668391599>
Nov 04 17:18:51 hf89 ironfish[22731]: Added block to fork seq: 257888, head-seq: 257888, hash: 00000...cbc14, head-hash: 00000...f776d, work: 66839154912511808355, head-work: 668391599>
Nov 04 17:19:33 hf89 ironfish[22731]: Added block to fork seq: 257889, head-seq: 257889, hash: 00000...d20a1, head-hash: 00000...9da79, work: 66839994499484158691, head-work: 668399970>
Nov 04 17:19:34 hf89 ironfish[22731]: Added block to fork seq: 257889, head-seq: 257889, hash: 00000...84443, head-hash: 00000...9da79, work: 66839993272017824846, head-work: 668399970>
Nov 04 17:20:14 hf89 ironfish[22731]: Reorganizing chain from 00000...9da79 (257889) for 00000...2ddbe (257890) on prev 00000...d20a1 (257889)
Nov 04 17:20:40 hf89 ironfish[22731]: Reorganized chain. blocks: 8, old: 00000...9da79 (257889), new: 00000...d20a1 (257889), fork: 00000...da573 (257885)
Nov 04 17:20:40 hf89 ironfish[22731]: Starting sync from AynV/kA (Lenox). work: +-2442167461102650600, ours: 257889, theirs: 257891
Nov 04 17:20:40 hf89 ironfish[22731]: Finding ancestor using linear search on last 3 blocks starting at 00000...d20a1 (257889) from peer AynV/kA (Lenox) at 257891
Nov 04 17:20:40 hf89 ironfish[22731]: Found peer AynV/kA (Lenox) ancestor 00000...d20a1, syncing from 257889 -> 257891 (2) after 1 requests
Nov 04 17:20:40 hf89 ironfish[22731]: Requesting 20 blocks starting at 00000...d20a1 (257889) from AynV/kA (Lenox)
Nov 04 17:20:43 hf89 ironfish[22731]: Finished syncing 1 blocks from AynV/kA (Lenox), skipped 1
Nov 04 17:22:10 hf89 ironfish[22731]: Reorganizing chain from 00000...03537 (257893) for 00000...15e44 (257893) on prev 00000...779b5 (257892)
Nov 04 17:22:11 hf89 ironfish[22731]: Reorganized chain. blocks: 1, old: 00000...03537 (257893), new: 00000...779b5 (257892), fork: 00000...779b5 (257892)
Nov 04 17:27:10 hf89 ironfish[22731]: Added block seq: 257900, hash: 00000...632a2, txs: 195, progress: 100.00%, time: 3218.3ms
Nov 04 17:31:40 hf89 ironfish[22731]: /usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/assert.js:18
Nov 04 17:31:40 hf89 ironfish[22731]:             throw new Error(message || `Expected value not to be undefined`);
Nov 04 17:31:40 hf89 ironfish[22731]:                   ^
Nov 04 17:31:40 hf89 ironfish[22731]: Error: nullifierToNote mappings must have a corresponding decryptedNote
Nov 04 17:31:40 hf89 ironfish[22731]:     at Function.isNotUndefined (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/assert.js:18:19)
Nov 04 17:31:40 hf89 ironfish[22731]:     at /usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/wallet/account.js:213:37
Nov 04 17:31:40 hf89 ironfish[22731]:     at async LevelupDatabase.withTransaction (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/storage/database/database.js:41:>
Nov 04 17:31:40 hf89 ironfish[22731]:     at async Account.expireTransaction (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/wallet/account.js:198:9)
Nov 04 17:31:40 hf89 ironfish[22731]:     at async Wallet.expireTransactions (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/wallet/wallet.js:601:17)
Nov 04 17:31:40 hf89 ironfish[22731]:     at async Wallet.eventLoop (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/wallet/wallet.js:183:9)
Nov 04 17:31:43 hf89 systemd[1]: ironfishd.service: Main process exited, code=exited, status=1/FAILURE
Nov 04 17:31:43 hf89 systemd[1]: ironfishd.service: Failed with result 'exit-code'.
Nov 04 17:31:53 hf89 systemd[1]: ironfishd.service: Scheduled restart job, restart counter is at 1.
Nov 04 17:31:53 hf89 systemd[1]: ironfishd.service: Scheduled restart job, restart counter is at 1.
Nov 04 17:31:53 hf89 systemd[1]: Stopped IronFish Node.
Nov 04 17:31:53 hf89 systemd[1]: Started IronFish Node.
Nov 04 17:31:54 hf89 ironfish[39446]:                                            
Nov 04 17:31:54 hf89 ironfish[39446]: ::::::::::          :::::::::::::::::
Nov 04 17:31:54 hf89 ironfish[39446]: ::::::::::::       :::::::::::::::::::
Nov 04 17:31:54 hf89 ironfish[39446]: :::::::::::::     :::::::::::::::::::::
Nov 04 17:31:54 hf89 ironfish[39446]: ::::::::::::::   ::::::::::::::::::::::::
Nov 04 17:31:54 hf89 ironfish[39446]:  ::::::::::::: ::::::::::        :::::::::
Nov 04 17:31:54 hf89 ironfish[39446]:    :::::::::::::::::::::          ::::::::::
Nov 04 17:31:54 hf89 ironfish[39446]:    :::::::::::::::::::::          :::::::::
Nov 04 17:31:54 hf89 ironfish[39446]:  ::::::::::::: ::::::::::        :::::::::
Nov 04 17:31:54 hf89 ironfish[39446]: ::::::::::::::   ::::::::::::::::::::::::
Nov 04 17:31:54 hf89 ironfish[39446]: :::::::::::::     :::::::::::::::::::::
Nov 04 17:31:54 hf89 ironfish[39446]: ::::::::::::       :::::::::::::::::::
Nov 04 17:31:54 hf89 ironfish[39446]: ::::::::::           ::::::::::::::::
Nov 04 17:31:54 hf89 ironfish[39446]: Version       0.1.50 @ 02939ae
Nov 04 17:31:54 hf89 ironfish[39446]: Node Name     fsck_node
Nov 04 17:31:54 hf89 ironfish[39446]: Graffiti      fsck_node
Nov 04 17:31:54 hf89 ironfish[39446]: Peer Identity /iyXhmq/vk1ga+HCGPakjp56wAoKgqqx7vyZrhdt5j8=
Nov 04 17:31:54 hf89 ironfish[39446]: Peer Agent    ironfish/0.1.50/02939ae
Nov 04 17:31:54 hf89 ironfish[39446]: Peer Port     9033
Nov 04 17:31:54 hf89 ironfish[39446]: Bootstrap     test.bn1.ironfish.network
Nov 04 17:31:54 hf89 ironfish[39446]:  
Nov 04 17:32:18 hf89 ironfish[39446]: WebSocket server started at :::9033
Nov 04 17:32:18 hf89 ironfish[39446]: /usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/assert.js:18
Nov 04 17:32:18 hf89 ironfish[39446]:             throw new Error(message || `Expected value not to be undefined`);
Nov 04 17:32:18 hf89 ironfish[39446]:                   ^
Nov 04 17:32:18 hf89 ironfish[39446]: Error: nullifierToNote mappings must have a corresponding decryptedNote
Nov 04 17:32:18 hf89 ironfish[39446]:     at Function.isNotUndefined (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/assert.js:18:19)

Today:
Nov 18 21:46:54 hf89 ironfish[345625]:                                            
Nov 18 21:46:54 hf89 ironfish[345625]: ::::::::::          :::::::::::::::::
Nov 18 21:46:54 hf89 ironfish[345625]: ::::::::::::       :::::::::::::::::::
Nov 18 21:46:54 hf89 ironfish[345625]: :::::::::::::     :::::::::::::::::::::
Nov 18 21:46:54 hf89 ironfish[345625]: ::::::::::::::   ::::::::::::::::::::::::
Nov 18 21:46:54 hf89 ironfish[345625]:  ::::::::::::: ::::::::::        :::::::::
Nov 18 21:46:54 hf89 ironfish[345625]:    :::::::::::::::::::::          ::::::::::
Nov 18 21:46:54 hf89 ironfish[345625]:    :::::::::::::::::::::          :::::::::
Nov 18 21:46:54 hf89 ironfish[345625]:  ::::::::::::: ::::::::::        :::::::::
Nov 18 21:46:54 hf89 ironfish[345625]: ::::::::::::::   ::::::::::::::::::::::::
Nov 18 21:46:54 hf89 ironfish[345625]: :::::::::::::     :::::::::::::::::::::
Nov 18 21:46:54 hf89 ironfish[345625]: ::::::::::::       :::::::::::::::::::
Nov 18 21:46:54 hf89 ironfish[345625]: ::::::::::           ::::::::::::::::
Nov 18 21:46:54 hf89 ironfish[345625]: Version       0.1.52 @ 1bf0c8e
Nov 18 21:46:54 hf89 ironfish[345625]: Node Name     fsck_node
Nov 18 21:46:54 hf89 ironfish[345625]: Graffiti      fsck_node
Nov 18 21:46:54 hf89 ironfish[345625]: Peer Identity /iyXhmq/vk1ga+HCGPakjp56wAoKgqqx7vyZrhdt5j8=
Nov 18 21:46:54 hf89 ironfish[345625]: Peer Agent    ironfish/0.1.52/1bf0c8e
Nov 18 21:46:54 hf89 ironfish[345625]: Peer Port     9033
Nov 18 21:46:54 hf89 ironfish[345625]: Bootstrap     test.bn1.ironfish.network
Nov 18 21:46:54 hf89 ironfish[345625]:  
Nov 18 21:46:54 hf89 ironfish[345625]: WebSocket server started at :::9033
Nov 18 21:46:54 hf89 ironfish[345625]: /usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/assert.js:18
Nov 18 21:46:54 hf89 ironfish[345625]:             throw new Error(message || `Expected value not to be undefined`);
Nov 18 21:46:54 hf89 ironfish[345625]:                   ^
Nov 18 21:46:54 hf89 ironfish[345625]: Error: nullifierToNote mappings must have a corresponding decryptedNote
Nov 18 21:46:54 hf89 ironfish[345625]:     at Function.isNotUndefined (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/assert.js:18:19)
Nov 18 21:46:54 hf89 ironfish[345625]:     at /usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/wallet/account.js:213:37
Nov 18 21:46:54 hf89 ironfish[345625]:     at async LevelupDatabase.withTransaction (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/storage/database/database.js:41:28)
Nov 18 21:46:54 hf89 ironfish[345625]:     at async Account.expireTransaction (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/wallet/account.js:198:9)
Nov 18 21:46:54 hf89 ironfish[345625]:     at async Wallet.expireTransactions (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/wallet/wallet.js:598:17)
Nov 18 21:46:54 hf89 ironfish[345625]:     at async Wallet.eventLoop (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/wallet/wallet.js:184:9)
05]:                                            

Nov 18 21:58:03 hf89 ironfish[346836]:                                            
Nov 18 21:58:03 hf89 ironfish[346836]: ::::::::::          :::::::::::::::::
Nov 18 21:58:03 hf89 ironfish[346836]: ::::::::::::       :::::::::::::::::::
Nov 18 21:58:03 hf89 ironfish[346836]: :::::::::::::     :::::::::::::::::::::
Nov 18 21:58:03 hf89 ironfish[346836]: ::::::::::::::   ::::::::::::::::::::::::
Nov 18 21:58:03 hf89 ironfish[346836]:  ::::::::::::: ::::::::::        :::::::::
Nov 18 21:58:03 hf89 ironfish[346836]:    :::::::::::::::::::::          ::::::::::
Nov 18 21:58:03 hf89 ironfish[346836]:    :::::::::::::::::::::          :::::::::
Nov 18 21:58:03 hf89 ironfish[346836]:  ::::::::::::: ::::::::::        :::::::::
Nov 18 21:58:03 hf89 ironfish[346836]: ::::::::::::::   ::::::::::::::::::::::::
Nov 18 21:58:03 hf89 ironfish[346836]: :::::::::::::     :::::::::::::::::::::
Nov 18 21:58:03 hf89 ironfish[346836]: ::::::::::::       :::::::::::::::::::
Nov 18 21:58:03 hf89 ironfish[346836]: ::::::::::           ::::::::::::::::
Nov 18 21:58:03 hf89 ironfish[346836]: Version       0.1.52 @ 1bf0c8e
Nov 18 21:58:03 hf89 ironfish[346836]: Node Name     fsck_node
Nov 18 21:58:03 hf89 ironfish[346836]: Graffiti      fsck_node
Nov 18 21:58:03 hf89 ironfish[346836]: Peer Identity /iyXhmq/vk1ga+HCGPakjp56wAoKgqqx7vyZrhdt5j8=
Nov 18 21:58:03 hf89 ironfish[346836]: Peer Agent    ironfish/0.1.52/1bf0c8e
Nov 18 21:58:03 hf89 ironfish[346836]: Peer Port     9033
Nov 18 21:58:03 hf89 ironfish[346836]: Bootstrap     test.bn1.ironfish.network
Nov 18 21:58:03 hf89 ironfish[346836]:  
Nov 18 21:58:04 hf89 ironfish[346836]: WebSocket server started at :::9033
Nov 18 21:58:04 hf89 ironfish[346836]: /usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/assert.js:18
Nov 18 21:58:04 hf89 ironfish[346836]:             throw new Error(message || `Expected value not to be undefined`);
Nov 18 21:58:04 hf89 ironfish[346836]:                   ^
Nov 18 21:58:04 hf89 ironfish[346836]: Error: nullifierToNote mappings must have a corresponding decryptedNote
Nov 18 21:58:04 hf89 ironfish[346836]:     at Function.isNotUndefined (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/assert.js:18:19)
Nov 18 21:58:04 hf89 ironfish[346836]:     at /usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/wallet/account.js:213:37
Nov 18 21:58:04 hf89 ironfish[346836]:     at async LevelupDatabase.withTransaction (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/storage/database/database.js:41>
Nov 18 21:58:04 hf89 ironfish[346836]:     at async Account.expireTransaction (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/wallet/account.js:198:9)
Nov 18 21:58:04 hf89 ironfish[346836]:     at async Wallet.expireTransactions (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/wallet/wallet.js:598:17)
Nov 18 21:58:04 hf89 ironfish[346836]:     at async Wallet.eventLoop (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/wallet/wallet.js:184:9)
Nov 18 21:58:04 hf89 systemd[1]: ironfishd.service: Main process exited, code=exited, status=1/FAILURE
Nov 18 21:58:04 hf89 systemd[1]: ironfishd.service: Failed with result 'exit-code'.
Nov 18 21:58:14 hf89 systemd[1]: ironfishd.service: Scheduled restart job, restart counter is at 11523.
Nov 18 21:58:14 hf89 systemd[1]: Stopped IronFish Node.


```

### Graffiti

fsck_node

**Comment by hughy** [comment]
The `accounts:repair` command in the latest version should help to resolve `nullifierToNote` errors like the one you're seeing here!

**Comment by pasha121** [comment]
Thanks! 
After some thousands restarts i saw node running. 
I have updated to new version. 
Now my node is up!

**Comment by hughy** [comment]
Great, I'm glad that the new version resolved this for you!
