### ISSUE TITLE
Error: Genesis block in network definition does not match existing chain genesis block

### ISSUE THREAD

**Issue by CooperNic** [iron-fish/ironfish#2978]
### What happened?

When I updated to version 0.1.60 and started the node, an error message appeared:
Error: Genesis block in network definition does not match existing chain genesis block

### Version

0.1.60

### Debug output

```shell
$ docker run --rm --tty --interactive --name iron_fish_node --network host --volume $HOME/.ironfish:/root/.ironfish ghcr.io/iron-fish/ironfish:latest debug
Error: Database is not open. Call IDatabase.open() first
    at get levelup [as levelup] (/usr/src/app/node_modules/@ironfish/sdk/build/src/storage/levelup/database.js:34:19)
    at LevelupDatabase.getAllIter (/usr/src/app/node_modules/@ironfish/sdk/build/src/storage/levelup/database.js:144:29)
    at getAllIter.next (<anonymous>)
    at LevelupStore.getAllIter (/usr/src/app/node_modules/@ironfish/sdk/build/src/storage/levelup/store.js:79:37)
    at getAllIter.next (<anonymous>)
    at WalletDB.loadHeads (/usr/src/app/node_modules/@ironfish/sdk/build/src/wallet/walletdb/walletdb.js:155:42)
    at loadHeads.next (<anonymous>)
    at Debug.outputRequiringDB (/usr/src/app/build/src/commands/debug.js:77:44)
    at Debug.start (/usr/src/app/build/src/commands/debug.js:37:57)
    at async Debug.run (/usr/src/app/build/src/command.js:24:13)
```

### Relevant log output

```shell
Version       0.1.60 @ d532750
Node Name     Cooper
Graffiti      Cooper
Peer Identity mNBpjXQvAYdYfGsRKp9VswZ5AGODau4ZIa8GwT+3Ig4=
Peer Agent    ironfish/0.1.60/d532750
Peer Port     9045
Bootstrap     test.bn1.ironfish.network

Error: Genesis block in network definition does not match existing chain genesis block
    at Assert.isTrue (/usr/src/app/node_modules/@ironfish/sdk/build/src/assert.js:46:19)
    at Blockchain.open (/usr/src/app/node_modules/@ironfish/sdk/build/src/blockchain/blockchain.js:173:29)
    at async IronfishNode.openDB (/usr/src/app/node_modules/@ironfish/sdk/build/src/node.js:193:13)
    at async Object.waitForOpen (/usr/src/app/node_modules/@ironfish/sdk/build/src/utils/node.js:16:13)
    at async Start.start (/usr/src/app/build/src/commands/start.js:105:9)
    at async Start.run (/usr/src/app/build/src/command.js:24:13)
    at async Start._run (/usr/src/app/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/usr/src/app/node_modules/@oclif/core/lib/config/config.js:272:25)
    at async Object.run (/usr/src/app/node_modules/@oclif/core/lib/main.js:74:5)
```

### Graffiti

Cooper

**Comment by Nixonu** [comment]
I have same issue

**Comment by epidemiash** [comment]
And what kind of fix was it?

**Comment by CooperNic** [comment]
> And what kind of fix was it?

Try 
`ironfish reset`

**Comment by epidemiash** [comment]
> > And what kind of fix was it?
> 
> Try `ironfish reset`

Yes, it just helped me, I was going to write a little earlier. In general, I had errors when I installed the wallet exe file, and then the node. Therefore, you need to do a reset and then run the node.
