### ISSUE TITLE
Cannot start node

### ISSUE THREAD

**Issue by paijobakso** [iron-fish/ironfish#3034]
### What happened?

![_20230120_171754](https://user-images.githubusercontent.com/116818316/213671579-ebb8a952-8290-42e7-9cac-2fd2534bd0df.JPG)

### Version

0.1.62

### Debug output

```shell
Error: Database is not open. Call IDatabase.open() first
    at get levelup [as levelup] (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/storage/levelup/database.js:34:19)
    at LevelupDatabase.getAllIter (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/storage/levelup/database.js:144:29)
    at getAllIter.next (<anonymous>)
    at LevelupStore.getAllIter (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/storage/levelup/store.js:79:37)
    at getAllIter.next (<anonymous>)
    at WalletDB.loadHeads (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/wallet/walletdb/walletdb.js:155:42)
    at loadHeads.next (<anonymous>)
    at Debug.outputRequiringDB (/usr/lib/node_modules/ironfish/build/src/commands/debug.js:77:44)
    at Debug.start (/usr/lib/node_modules/ironfish/build/src/commands/debug.js:37:57)
    at async Debug.run (/usr/lib/node_modules/ironfish/build/src/command.js:24:13)
```

### Graffiti

<mainet>

**Comment by ygao76** [comment]
thanks for reporting this.
