### ISSUE TITLE
incorrect amount of asset / ironfish wallet:send 

### ISSUE THREAD

**Issue by BlockOverView** [iron-fish/ironfish#3045]
### What happened?

When I am going to use this command --> ironfish wallet:send, command prompt asks to enter the amount of asset when I enter incorrect value like this 7e3018832633dcacc412ab2a9c0473fb667e2733feffc6bdf7df023fac22f38c I get error

![Screenshot_20230121_124741](https://user-images.githubusercontent.com/121298825/213807036-56c286df-ef2e-45bb-be4b-ca0cf4e4ce02.png)

### Version

v0.1.62

### Debug output

```shell
root@Ironfish:~# ironfish debug
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version               0.1.62 @ 4ab43f3
Iron Fish library               0.0.39 @ 4ab43f3
Operating system                Linux x64
CPU model(s)                    AMD EPYC Processor
CPU threads                     4
RAM total                       7.58 GiB
Heap total                      1.99 GiB
Node version                    v18.13.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       Seengo
Block graffiti                  Seengo
```

### Relevant log output

```shell
root@Ironfish:~# ironfish wallet:send
? Select the asset you wish to send 56fd13343bf5fa79faeec684f27f312258289365c0782538255e79919019ee02 (Seengo)
Enter the amount (balance: 1000.00000000): 7e3018832633dcacc412ab2a9c0473fb667e2733feffc6bdf7df023fac22f38c
Error: invalid decimal value (argument="value", value="7e3018832633dcacc412ab2a9c0473fb667e2733feffc6bdf7df023fac22f38c", code=INVALID_ARGUMENT, version=bignumber/5.7.0)
    at Logger.makeError (/usr/lib/node_modules/ironfish/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/usr/lib/node_modules/ironfish/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at Logger.throwArgumentError (/usr/lib/node_modules/ironfish/node_modules/@ethersproject/logger/lib/index.js:250:21)
    at Object.parseFixed (/usr/lib/node_modules/ironfish/node_modules/@ethersproject/bignumber/lib/fixednumber.js:73:16)
    at CurrencyUtils.decodeIron (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/utils/currency.js:21:28)
    at Send.start (/usr/lib/node_modules/ironfish/build/src/commands/wallet/send.js:47:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Send.run (/usr/lib/node_modules/ironfish/build/src/command.js:24:13)
    at async Send._run (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/config/config.js:272:25)
```

### Graffiti

https://testnet.ironfish.network/users/232968

**Comment by wd021** [comment]
`7e3018832633dcacc412ab2a9c0473fb667e2733feffc6bdf7df023fac22f38c` is not a correct input for amount
