### ISSUE TITLE
Ironfish fail to start after install in Mac OS

### ISSUE THREAD

**Issue by larryhopecode** [iron-fish/ironfish#3057]
### What happened?

Normal install in Mac OS using brew as in instructions.
Execute ironfish CLI got the following error...
usr/local/Cellar/ironfish/74/libexec/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: The module '/usr/local/Cellar/ironfish/74/libexec/node_modules/segfault-handler/build/Release/segfault-handler.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 108. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1249:18)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at bindings (/usr/local/Cellar/ironfish/74/libexec/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/local/Cellar/ironfish/74/libexec/node_modules/segfault-handler/index.js:3:37)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32) {
  code: 'ERR_DLOPEN_FAILED'
}

### Version

0.1.62

### Debug output

```shell
usr/local/Cellar/ironfish/74/libexec/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: The module '/usr/local/Cellar/ironfish/74/libexec/node_modules/segfault-handler/build/Release/segfault-handler.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 108. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1249:18)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at bindings (/usr/local/Cellar/ironfish/74/libexec/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/local/Cellar/ironfish/74/libexec/node_modules/segfault-handler/index.js:3:37)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32) {
  code: 'ERR_DLOPEN_FAILED'
}
```

### Graffiti

Ironman2021

**Comment by wd021** [comment]
looks like you need to upgrade your node version

**Comment by larryhopecode** [comment]
Is V18.13.0 still not updated enough?

￼

**Comment by holahula** [comment]
Closing - `segfault-handler` has been removed as a dependency
