### ISSUE TITLE
'Error: fractional component exceeds decimals' error appears when user tries to set fee 0.000000001

### ISSUE THREAD

**Issue by ipohosov** [iron-fish/ironfish#3066]
### What happened?

STR:
1. Try to mint an asset using fee 0.000000001
Example: ironfish wallet:mint -a 100 -f mplife -m $iron_name -n $iron_name -o 0.00000001 --confirm

Actual Output:
`Error: fractional component exceeds decimals [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT ] (fault="underflow", operation="parseFixed", code=NUMERIC_FAULT, version=bignumber/5.7.0)
    at Logger.Logger.makeError (/usr/src/app/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.Logger.throwError (/usr/src/app/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at throwFault (/usr/src/app/node_modules/@ethersproject/bignumber/src.ts/fixednumber.ts:19:19)
    at Object.parseFixed (/usr/src/app/node_modules/@ethersproject/bignumber/src.ts/fixednumber.ts:104:9)
    at Function.decodeIron (/usr/src/app/node_modules/@ironfish/sdk/src/utils/currency.ts:23:12)
    at Mint.start (/usr/src/app/src/commands/wallet/mint.ts:132:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Mint.run (/usr/src/app/src/command.ts:73:7)
    at async Mint._run (/usr/src/app/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/usr/src/app/node_modules/@oclif/core/lib/config/config.js:272:25)`

Expected Output: Some message about increasing fee because it's so small.

<img width="993" alt="Termius" src="https://user-images.githubusercontent.com/6196297/213920448-a5c21f5a-b857-4085-a250-19992db3fc3a.png">

### Version

0.1.62 @ 4ab43f3

### Debug output

```shell
Iron Fish version               0.1.62 @ 4ab43f3
Iron Fish library               0.0.39 @ 4ab43f3
Operating system                Linux x64
CPU model(s)                    AMD EPYC 7282 16-Core Processor
CPU threads                     8
RAM total                       29.39 GiB
Heap total                      4.00 GiB
Node version                    v18.12.1
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       mplife
Block graffiti                  mplife
```

### Graffiti

mplife

**Comment by Qloun** [comment]
In ironfish only 8 decimal are allowed. If you try to use the command _ironfish wallet:mint_ with no flags, at the stage of setting the fee it will be said that the minimum size is 0.00000001

**Comment by ipohosov** [comment]
> In ironfish only 8 decimal are allowed. If you try to use the command _ironfish wallet:mint_ with no flags, at the stage of setting the fee it will be said that the minimum size is 0.00000001

I understand it but I expect some user friendly message instead of ts stacktrace....

**Comment by Qloun** [comment]
> > In ironfish only 8 decimal are allowed. If you try to use the command _ironfish wallet:mint_ with no flags, at the stage of setting the fee it will be said that the minimum size is 0.00000001
> 
> I understand it but I expect some user friendly message instead of ts stacktrace....

Me too :(
