### ISSUE TITLE
ironfish wallet:import command not working

### ISSUE THREAD

**Issue by Savytskiy** [iron-fish/ironfish#3075]
### What happened?

when I tried to use
`ironfish wallet:import`
I have an error
```
ParseJsonError: Parsing undefined Failed
Unexpected end of JSON input while parsing empty string
    at tryParse (/usr/src/app/node_modules/@ironfish/sdk/build/src/utils/json.js:53:27)
    at Object.parse (/usr/src/app/node_modules/@ironfish/sdk/build/src/utils/json.js:39:29)
    at ImportCommand.importPipe (/usr/src/app/build/src/commands/wallet/import.js:59:32)
    at async ImportCommand.start (/usr/src/app/build/src/commands/wallet/import.js:24:23)
    at async ImportCommand.run (/usr/src/app/build/src/command.js:24:13)
    at async ImportCommand._run (/usr/src/app/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/usr/src/app/node_modules/@oclif/core/lib/config/config.js:272:25)
    at async Object.run (/usr/src/app/node_modules/@oclif/core/lib/main.js:74:5)

```
I am being able to import with `ironfish wallet:import filename`
But according to the guide from the developers, there are several options for importing. This command should work without a filename. 
![image](https://user-images.githubusercontent.com/111236879/213963280-881eda63-031e-410e-9d06-e7bb4c6a8186.png)

### Version

0.1.62

### Debug output

```shell
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version               0.1.62 @ 4ab43f3
Iron Fish library               0.0.39 @ 4ab43f3
Operating system                Linux x64
CPU model(s)                    Intel(R) Core(TM) i5-3350P CPU @ 3.10GHz
CPU threads                     4
RAM total                       23.41 GiB
Heap total                      3.99 GiB
Node version                    v18.12.1
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       mynode
Block graffiti                  iioxhabce
```

### Relevant log output

```shell
root@iioxhabcenodes:~/ironfish# ironfish wallet:import
ParseJsonError: Parsing undefined Failed
Unexpected end of JSON input while parsing empty string
    at tryParse (/usr/src/app/node_modules/@ironfish/sdk/build/src/utils/json.js:53:27)
    at Object.parse (/usr/src/app/node_modules/@ironfish/sdk/build/src/utils/json.js:39:29)
    at ImportCommand.importPipe (/usr/src/app/build/src/commands/wallet/import.js:59:32)
    at async ImportCommand.start (/usr/src/app/build/src/commands/wallet/import.js:24:23)
    at async ImportCommand.run (/usr/src/app/build/src/command.js:24:13)
    at async ImportCommand._run (/usr/src/app/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/usr/src/app/node_modules/@oclif/core/lib/config/config.js:272:25)
    at async Object.run (/usr/src/app/node_modules/@oclif/core/lib/main.js:74:5)
```

### Graffiti

iioxhabce

**Comment by hughy** [comment]
We've made significant changes to the import command. Please open a new issue if you're continuing to run into problems with account imports.
