### ISSUE TITLE
A bug in running the node

### ISSUE THREAD

**Issue by zaidbsousa** [iron-fish/ironfish#3108]
### What happened?

I installed the node, and everything was perfect, then the hole node stopped and I got this err:

> OpenError: IO error: /home/zaid/.ironfish/databases/chain/LOCK: Read-only file system
>     at /usr/lib/node_modules/ironfish/node_modules/levelup/lib/levelup.js:119:23
>     at /usr/lib/node_modules/ironfish/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
>     at /usr/lib/node_modules/ironfish/node_modules/deferred-leveldown/deferred-leveldown.js:31:21
>     at /usr/lib/node_modules/ironfish/node_modules/abstract-leveldown/abstract-leveldown.js:38:14

I tried to sudo then I got this err:

> (node:1217) [EIO] Error: EIO: i/o error, open '/root/.local/share/ironfish/package.json'
> (Use node --trace-warnings ... to show where the warning was created)
>     Error: ENOENT: no such file or directory, mkdir '/root/.ironfish'
>     Code: ENOENT

### Version

Ubuntu 22.04.1 

### Debug output

```shell
Database cannot be opened, skipping output that requires database.

OpenError: IO error: /home/zaid/.ironfish/databases/chain/LOCK: Read-only file system
    at /usr/lib/node_modules/ironfish/node_modules/levelup/lib/levelup.js:119:23
    at /usr/lib/node_modules/ironfish/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
    at /usr/lib/node_modules/ironfish/node_modules/deferred-leveldown/deferred-leveldown.js:31:21
    at /usr/lib/node_modules/ironfish/node_modules/abstract-leveldown/abstract-leveldown.js:38:14

Iron Fish version               0.1.62 @ 4ab43f3
Iron Fish library               0.0.39 @ 4ab43f3
Operating system                Linux x64
CPU model(s)                    Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
CPU threads                     6
RAM total                       11.07 GiB
Heap total                      1.99 GiB
Node version                    v18.13.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       CryptoNerd
Block graffiti                  CryptoNerd
```

### Graffiti

CryptoNerd

**Comment by zaidbsousa** [comment]
Update: I just restart the PC and the node then everything got back to normal, no idea what caused the problem but it was solved by restarting both the PC & the node.
