### ISSUE TITLE
Ironfish:send

### ISSUE THREAD

**Issue by itcare247vn** [iron-fish/ironfish#3184]
### What happened?

A bug happened!
The bugs display when you enter the characters instead of the number at "Enter the amount." For me, it should be filter and not allow to input the characters... and avoid confusing to users. 

Regards
Thanh Phuong
Testnet account: itcare247vn@gmail.com

### Version

0.1.62 @ 4ab43f3

### Debug output

```shell
root@localhost:~# ironfish wallet:send
? Select the asset you wish to send
47e630cbe0e2450539fc88c3d61d65a3cc0dcc4f8af6a15f5e69ff7dc007a544 (pcoin1983)
Enter the amount (balance: 40.00000000): abcd
Error: invalid decimal value (argument="value", value="abcd", code=INVALID_ARGUMENT, version=bignumber/5.7.0)
    at Logger.makeError (/usr/lib/node_modules/ironfish/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/usr/lib/node_modules/ironfish/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at Logger.throwArgumentError (/usr/lib/node_modules/ironfish/node_modules/@ethersproject/logger/lib/index.js:250:21)
    at Object.parseFixed (/usr/lib/node_modules/ironfish/node_modules/@ethersproject/bignumber/lib/fixednumber.js:73:16)
    at CurrencyUtils.decodeIron (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/utils/currency.js:21:28)
    at Send.start (/usr/lib/node_modules/ironfish/build/src/commands/wallet/send.js:47:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Send.run (/usr/lib/node_modules/ironfish/build/src/command.js:24:13)
    at async Send._run (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/config/config.js:272:25)
root@localhost:~#
```

### Relevant log output

```shell
root@localhost:~# ironfish wallet:send
? Select the asset you wish to send
47e630cbe0e2450539fc88c3d61d65a3cc0dcc4f8af6a15f5e69ff7dc007a544 (pcoin1983)
Enter the amount (balance: 40.00000000): abcd
Error: invalid decimal value (argument="value", value="abcd", code=INVALID_ARGUMENT, version=bignumber/5.7.0)
    at Logger.makeError (/usr/lib/node_modules/ironfish/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/usr/lib/node_modules/ironfish/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at Logger.throwArgumentError (/usr/lib/node_modules/ironfish/node_modules/@ethersproject/logger/lib/index.js:250:21)
    at Object.parseFixed (/usr/lib/node_modules/ironfish/node_modules/@ethersproject/bignumber/lib/fixednumber.js:73:16)
    at CurrencyUtils.decodeIron (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/utils/currency.js:21:28)
    at Send.start (/usr/lib/node_modules/ironfish/build/src/commands/wallet/send.js:47:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Send.run (/usr/lib/node_modules/ironfish/build/src/command.js:24:13)
    at async Send._run (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/config/config.js:272:25)
root@localhost:~#
```

### Graffiti

pcoin1983

**Comment by wd021** [comment]
the error message has been updated
