### ISSUE TITLE
Ironfish CLI does not start

### ISSUE THREAD

**Issue by proftechrus** [iron-fish/ironfish#330]
**System:**
Linux vps 5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Status:**
service ironfishd status

ironfishd.service - IronFish Node
     Loaded: loaded (/etc/systemd/system/ironfishd.service; enabled; vendor pre>
     Active: active (running) since Sun 2021-08-15 19:43:53 UTC; 18min ago
   Main PID: 987 (node)
      Tasks: 91 (limit: 629145)
     Memory: 681.3M
     CGroup: /system.slice/ironfishd.service
             ├─ 987 node /usr/bin/yarn --cwd /root/ironfish/ironfish-cli/ start>
             ├─1117 /bin/sh -c node start start
             ├─1118 /usr/bin/node start start
             ├─1147 /bin/sh -c tsc-watch --build --onSuccess "yarn run start:js>
             ├─1149 /usr/bin/node /root/ironfish/ironfish-cli/node_modules/.bin>
             ├─1197 /usr/bin/node /root/ironfish/node_modules/typescript/bin/ts>
             ├─1271 /usr/bin/node /usr/bin/yarn run start:js start
             ├─1303 /bin/sh -c cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node >
             ├─1304 /usr/bin/node /root/ironfish/ironfish-cli/node_modules/.bin>
             └─1319 /usr/bin/node bin/run start

Aug 15 20:02:26 vps yarn[1319]: Connected to the Iron Fish network
Aug 15 20:02:26 vps yarn[1319]: Starting sync from 1MhOpDu (bootstrap). work: +>
Aug 15 20:02:26 vps yarn[1319]: Found peer 1MhOpDu (bootstrap) ancestor e12b4..>
Aug 15 20:02:26 vps yarn[1319]: Requesting 20 blocks starting at e12b4...5978c >
Aug 15 20:02:28 vps yarn[1319]: Added block seq: 20, hash: 00007...043e2, txs: 

**service ironfishd-miner status**
ironfishd-miner.service - IronFish Miner
     Loaded: loaded (/etc/systemd/system/ironfishd-miner.service; enabled; vend>
     Active: active (running) since Sun 2021-08-15 19:43:53 UTC; 20min ago
   Main PID: 986 (node)
      Tasks: 68 (limit: 629145)
     Memory: 342.4M
     CGroup: /system.slice/ironfishd-miner.service
             ├─ 986 node /usr/bin/yarn --cwd /root/ironfish/ironfish-cli/ start>
             ├─1126 /bin/sh -c node start miners:start -t -1
             ├─1128 /usr/bin/node start miners:start -t -1
             ├─1145 /bin/sh -c tsc-watch --build --onSuccess "yarn run start:js>
             ├─1148 /usr/bin/node /root/ironfish/ironfish-cli/node_modules/.bin>
             ├─1202 /usr/bin/node /root/ironfish/node_modules/typescript/bin/ts>
             ├─1272 /usr/bin/node /usr/bin/yarn run start:js miners:start -t -1
             ├─1311 /bin/sh -c cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node >
             ├─1312 /usr/bin/node /root/ironfish/ironfish-cli/node_modules/.bin>
             └─1320 /usr/bin/node bin/run miners:start -t -1

Aug 15 19:43:53 vps systemd[1]: Started IronFish Miner.
Aug 15 19:43:55 vps yarn[986]: yarn run v1.22.11
Aug 15 19:43:55 vps yarn[986]: $ node start miners:start -t -1
Aug 15 19:43:56 vps yarn[1148]: [52B blob data]
Aug 15 19:43:56 vps yarn[1148]: 7:43:56 PM - Found 0 errors. Watching for file 

**sudo ironfish status -f**

internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '/usr/bin/run'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

******
please advise how to fix

**Comment by unordered-set** [comment]
What do you have in your service file? `/usr/bin/run` looks weird, may be you had `yarn start run` or something like that...

**Comment by deekerno** [comment]
Closing due to inactivity. If you are still encountering this problem after updating to the newest version, feel free to re-open this issue.
