### ISSUE TITLE
Specifying a datadir on faucet requests results in an error

### ISSUE THREAD

**Issue by prostoalex** [iron-fish/ironfish#3363]
### What happened?

Previously faucet requests on a full node running in a custom directory were successful. Yet now they return an ENOENT error

d:\if>ironfish faucet --datadir=="d:/if" 
    Error: ENOENT: no such file or directory, mkdir 'd:\if\=d:\if'
    Code: ENOENT

d:\if>ironfish --version --datadir="d:\if"
name       ironfish
version    0.1.63      
git        693ff0f     
runtime    node/18.12.1

### Version

0.1.63

### Debug output

```shell
d:\if>ironfish debug --datadir="d:\if"     
Database cannot be opened, skipping output that requires database.

OpenError: IO error: LockFile d:\if\databases\chain/LOCK: The process cannot access the file because it is being used by another process.

    at C:\Users\lx\AppData\Roaming\npm\node_modules\ironfish\node_modules\levelup\lib\levelup.js:119:23
    at C:\Users\lx\AppData\Roaming\npm\node_modules\ironfish\node_modules\abstract-leveldown\abstract-leveldown.js:38:14
    at C:\Users\lx\AppData\Roaming\npm\node_modules\ironfish\node_modules\deferred-leveldown\deferred-leveldown.js:31:21
    at C:\Users\lx\AppData\Roaming\npm\node_modules\ironfish\node_modules\abstract-leveldown\abstract-leveldown.js:38:14

Iron Fish version               0.1.63 @ 693ff0f
Iron Fish library               0.0.40 @ 693ff0f
Operating system                Windows_NT x64
CPU model(s)                    Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
CPU threads                     8
RAM total                       31.95 GiB
Heap total                      4.00 GiB
Node version                    v18.12.1
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       lxlxlxlx
Block graffiti                  lxlxlxlx

d:\if>
```

### Graffiti

lxlxlxlx

**Comment by hughy** [comment]
It looks like this error may have happened because of an extra `=` when setting datadir:

> d:\if>ironfish faucet --datadir=="d:/if"
Error: ENOENT: no such file or directory, mkdir 'd:\if=d:\if'

Do you get the same error if you run `ironfish faucet --datadir="d:/if"`?

**Comment by prostoalex** [comment]
My bad.
