### ISSUE TITLE
ironfish status

### ISSUE THREAD

**Issue by cyberkd** [iron-fish/ironfish#3376]
### What happened?

When ironfish is called, status fails with an error. Log and debug attached.

**ironfish status**
TypeError: Cannot read properties of null (reading 'toFixed')
    at renderStatus (/usr/src/app/build/src/commands/status.js:130:70)
    at Status.start (/usr/src/app/build/src/commands/status.js:21:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Status.run (/usr/src/app/build/src/command.js:24:13)
    at async Status._run (/usr/src/app/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/usr/src/app/node_modules/@oclif/core/lib/config/config.js:272:25)
    at async Object.run (/usr/src/app/node_modules/@oclif/core/lib/main.js:74:5)

### Version

0.1.65 git f3fdfa1 runtime node/18.12.1

### Debug output

```shell
Iron Fish version               0.1.65 @ f3fdfa1
Iron Fish library               0.0.42 @ f3fdfa1
Operating system                Linux x64
CPU model(s)                    AMD EPYC 7282 16-Core Processor
CPU threads                     4
RAM total                       7.77 GiB
Heap total                      1.99 GiB
Node version                    v18.12.1
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       cyberkd
Block graffiti                  cyberkd
```

### Relevant log output

```shell
**ironfish status**
TypeError: Cannot read properties of null (reading 'toFixed')
    at renderStatus (/usr/src/app/build/src/commands/status.js:130:70)
    at Status.start (/usr/src/app/build/src/commands/status.js:21:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Status.run (/usr/src/app/build/src/command.js:24:13)
    at async Status._run (/usr/src/app/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/usr/src/app/node_modules/@oclif/core/lib/config/config.js:272:25)
    at async Object.run (/usr/src/app/node_modules/@oclif/core/lib/main.js:74:5)
```

### Graffiti

cyberkd

**Comment by ygao76** [comment]
Can you upgrade to the latest version and restart Ironfish node, and rerun the status? I can not reproduce your errors and we dont have any other user report any issue with status command.

**Comment by ygao76** [comment]
If you continue experience same issue after doing the above steps, feel free to reopen it.
