### ISSUE TITLE
Accounts export does not support directory

### ISSUE THREAD

**Issue by NullSoldier** [iron-fish/ironfish#338]
IF you try to use `ironfish accounts:export default ~/` you will get an error like this...

```
Error: EISDIR: illegal operation on a directory, open '/home/dvm/IRON/iii/ironfish/ironfish-cli'
    at Object.openSync (fs.js:498:3)
    at Object.writeFileSync (fs.js:1524:35)
    at ExportCommand.start (/home/dvm/IRON/iii/ironfish/ironfish-cli/build/commands/accounts/export.js:26:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExportCommand.run (/home/dvm/IRON/iii/ironfish/ironfish-cli/build/command.js:22:13)
    at async ExportCommand._run (/home/dvm/IRON/iii/ironfish/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/home/dvm/IRON/iii/ironfish/node_modules/@oclif/config/lib/config.js:173:24)
    at async Main.run (/home/dvm/IRON/iii/ironfish/node_modules/@oclif/command/lib/main.js:27:9)
    at async Main._run (/home/dvm/IRON/iii/ironfish/node_modules/@oclif/command/lib/command.js:43:20)
```

This code needs to detect its exporting to a directory and specify a default export name here.

https://github.com/iron-fish/ironfish/blob/master/ironfish-cli/src/commands/accounts/export.ts#L49-L50

Reported here, https://discord.com/channels/771503434028941353/816795916627345450/879788757430181918

**Comment by deekerno** [comment]
This was fixed in #340.
