### ISSUE TITLE
Could not upgrade iron database for latest version 0.1.67

### ISSUE THREAD

**Issue by satya-jugran** [iron-fish/ironfish#3405]
### What happened?

Getting an error while running the command - 
`ironfish start --upgrade`

Also, now I could not start ironfish node.

### Version

0.1.67

### Relevant log output

```shell
Version       0.1.67 @ bba0453
Node Name     satyaj
Graffiti      satyaj
Peer Identity DHvz0BH3giTeGQMkmVbaC8MdIafuMV3vZHtNkXcBElg=
Peer Agent    ironfish/0.1.67/bba0453
Peer Port     9033
Bootstrap     test.bn1.ironfish.network

Applying 2 migrations:
  019-backfill-wallet-assets-from-chain
  020-backfill-null-asset-supplies

Running 019-backfill-wallet-assets-from-chain...
Backfilling assets for 1 accounts

  Backfilling assets for account default
Error applying 019-backfill-wallet-assets-from-chain
Error: Asset must be non-null in the chain
    at Assert.isNotUndefined (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/assert.js:18:19)
    at Migration019.forward (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/migrations/data/019-backfill-wallet-assets-from-chain.js:45:37)
    at async Migrator.migrate (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/migrations/migrator.js:118:17)
    at async IronfishNode.openDB (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/node.js:189:13)
    at async Object.waitForOpen (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/utils/node.js:16:13)
    at async Start.start (/usr/lib/node_modules/ironfish/build/src/commands/start.js:105:9)
    at async Start.run (/usr/lib/node_modules/ironfish/build/src/command.js:24:13)
    at async Start._run (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/config/config.js:272:25)
    at async Object.run (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/main.js:74:5)
```

### Graffiti

satyaj

**Comment by Jensnicolaigustavsen** [comment]
for me it worked out well doing:
ironfish chain:download

**Comment by Raisahabji** [comment]
Facing same issue

**Comment by satya-jugran** [comment]
After re-installing everything, I am no longer facing any issue.
