### ISSUE TITLE
[issue namehe first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined

### ISSUE THREAD

**Issue by thomvn1** [iron-fish/ironfish#3430]
### What happened?

Hi Team, while trying to perform burn and send.

 I get this error: ironfish wallet:burn
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at Function.from (node:buffer:334:9)
    at /usr/lib/node_modules/ironfish/build/src/utils/asset.js:33:60
    at Array.map (<anonymous>)
    at Object.selectAsset (/usr/lib/node_modules/ironfish/build/src/utils/asset.js:32:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Burn.start (/usr/lib/node_modules/ironfish/build/src/commands/wallet/burn.js:38:27)
    at async Burn.run (/usr/lib/node_modules/ironfish/build/src/command.js:24:13)
    at async Burn._run (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/config/config.js:272:25)
What can be done to fix this? I confirm that my node is updated to the latest version 1.67.

### Version

V1.67

### Graffiti

tomv#4161

**Comment by wd021** [comment]
can you check your node and status versions, may be same situation as https://github.com/iron-fish/ironfish/issues/3397
