### ISSUE TITLE
Installation using npm fails

### ISSUE THREAD

**Issue by kamenkadmitry** [iron-fish/ironfish#3543]
### What happened?

Installation using npm fails

Installation attempts have been made [Ubuntu](url) 20.04, Ubuntu 22.04 

https://fex.net/ru/s/tmkatzc  Full log debag

### Version

latest npm

### Debug output

```shell
3629 info run leveldown@5.6.0 install node_modules/ironfish/node_modules/leveldown node-gyp-build
3630 info run node-datachannel@0.4.0 install node_modules/ironfish/node_modules/node-datachannel prebuild-install || (npm install --ignore-scripts && npm run _prebuild)
3631 info run leveldown@5.6.0 install { code: 0, signal: null }
3632 timing build:run:install:node_modules/ironfish/node_modules/leveldown Completed in 171ms
3633 info run segfault-handler@1.3.0 install node_modules/ironfish/node_modules/segfault-handler node-gyp rebuild
3634 info run node-datachannel@0.4.0 install { code: 0, signal: null }
3635 timing build:run:install:node_modules/ironfish/node_modules/node-datachannel Completed in 2808ms
3636 info run sqlite3@5.0.4 install node_modules/ironfish/node_modules/sqlite3 node-pre-gyp install --fallback-to-build
3637 info run segfault-handler@1.3.0 install { code: 1, signal: null }
3638 info run sqlite3@5.0.4 install { code: 0, signal: null }
3639 timing build:run:install:node_modules/ironfish/node_modules/sqlite3 Completed in 1178ms
3640 timing reify:rollback:createSparse Completed in 1594ms
3641 timing reify:rollback:retireShallow Completed in 0ms
3642 timing command:install Completed in 43586ms
3643 notice
3643 notice New patch version of npm available! 9.5.0 -> 9.5.1
3643 notice Changelog: https://github.com/npm/cli/releases/tag/v9.5.1
3643 notice Run npm install -g npm@9.5.1 to update!
3643 notice
3644 verbose stack Error: command failed
3644 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
3644 verbose stack     at ChildProcess.emit (node:events:513:28)
3644 verbose stack     at maybeClose (node:internal/child_process:1091:16)
3644 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
3645 verbose pkgid segfault-handler@1.3.0
3646 verbose cwd /root
3647 verbose Linux 5.4.0-139-generic
3648 verbose node v18.14.2
3649 verbose npm  v9.5.0
3650 error code 1
3651 error path /usr/lib/node_modules/ironfish/node_modules/segfault-handler
3652 error command failed
3653 error command sh -c node-gyp rebuild
3654 error gyp info it worked if it ends with ok
3654 error gyp info using node-gyp@8.4.1
3654 error gyp info using node@18.14.2 | linux | x64
3654 error gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
3654 error gyp http GET https://nodejs.org/download/release/v18.14.2/node-v18.14.2-headers.tar.gz
3654 error gyp http 200 https://nodejs.org/download/release/v18.14.2/node-v18.14.2-headers.tar.gz
3654 error gyp http GET https://nodejs.org/download/release/v18.14.2/SHASUMS256.txt
3654 error gyp http 200 https://nodejs.org/download/release/v18.14.2/SHASUMS256.txt
3654 error gyp info spawn /usr/bin/python3
3654 error gyp info spawn args [
3654 error gyp info spawn args   '/usr/lib/node_modules/ironfish/node_modules/node-gyp/gyp/gyp_main.py',
3654 error gyp info spawn args   'binding.gyp',
3654 error gyp info spawn args   '-f',
3654 error gyp info spawn args   'make',
3654 error gyp info spawn args   '-I',
3654 error gyp info spawn args   '/usr/lib/node_modules/ironfish/node_modules/segfault-handler/build/config.gypi',
3654 error gyp info spawn args   '-I',
3654 error gyp info spawn args   '/usr/lib/node_modules/ironfish/node_modules/node-gyp/addon.gypi',
3654 error gyp info spawn args   '-I',
3654 error gyp info spawn args   '/root/.cache/node-gyp/18.14.2/include/node/common.gypi',
3654 error gyp info spawn args   '-Dlibrary=shared_library',
3654 error gyp info spawn args   '-Dvisibility=default',
3654 error gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/18.14.2',
3654 error gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/ironfish/node_modules/node-gyp',
3654 error gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/18.14.2/<(target_arch)/node.lib',
3654 error gyp info spawn args   '-Dmodule_root_dir=/usr/lib/node_modules/ironfish/node_modules/segfault-handler',
3654 error gyp info spawn args   '-Dnode_engine=v8',
3654 error gyp info spawn args   '--depth=.',
3654 error gyp info spawn args   '--no-parallel',
3654 error gyp info spawn args   '--generator-output',
3654 error gyp info spawn args   'build',
3654 error gyp info spawn args   '-Goutput_dir=.'
3654 error gyp info spawn args ]
3654 error gyp ERR! build error
3654 error gyp ERR! stack Error: not found: make
3654 error gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/ironfish/node_modules/node-gyp/node_modules/which/which.js:10:17)
3654 error gyp ERR! stack     at /usr/lib/node_modules/ironfish/node_modules/node-gyp/node_modules/which/which.js:57:18
3654 error gyp ERR! stack     at new Promise (<anonymous>)
3654 error gyp ERR! stack     at step (/usr/lib/node_modules/ironfish/node_modules/node-gyp/node_modules/which/which.js:54:21)
3654 error gyp ERR! stack     at /usr/lib/node_modules/ironfish/node_modules/node-gyp/node_modules/which/which.js:71:22
3654 error gyp ERR! stack     at new Promise (<anonymous>)
3654 error gyp ERR! stack     at subStep (/usr/lib/node_modules/ironfish/node_modules/node-gyp/node_modules/which/which.js:69:33)
3654 error gyp ERR! stack     at /usr/lib/node_modules/ironfish/node_modules/node-gyp/node_modules/which/which.js:80:22
3654 error gyp ERR! stack     at /usr/lib/node_modules/ironfish/node_modules/isexe/index.js:42:5
3654 error gyp ERR! stack     at /usr/lib/node_modules/ironfish/node_modules/isexe/mode.js:8:5
3654 error gyp ERR! System Linux 5.4.0-139-generic
3654 error gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/ironfish/node_modules/.bin/node-gyp" "rebuild"
3654 error gyp ERR! cwd /usr/lib/node_modules/ironfish/node_modules/segfault-handler
3654 error gyp ERR! node -v v18.14.2
3654 error gyp ERR! node-gyp -v v8.4.1
3654 error gyp ERR! not ok
3655 verbose exit 1
3656 timing npm Completed in 43649ms
3657 verbose unfinished npm timer reify 1677241715848
3658 verbose unfinished npm timer reify:build 1677241754331
3659 verbose unfinished npm timer build 1677241754333
3660 verbose unfinished npm timer build:deps 1677241754334
3661 verbose unfinished npm timer build:run:install 1677241754473
3662 verbose unfinished npm timer build:run:install:node_modules/ironfish/node_modules/segfault-handler 1677241754644
```

### Relevant log output

```shell
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated @types/minipass@3.3.5: This is a stub types definition. minipass provides its own type definitions, so you do not need this installed.
npm WARN deprecated @oclif/screen@3.0.4: Deprecated in favor of @oclif/core
npm notice
npm notice New patch version of npm available! 9.5.0 -> 9.5.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.5.1
npm notice Run npm install -g npm@9.5.1 to update!
npm notice
npm ERR! code 1
npm ERR! path /usr/lib/node_modules/ironfish/node_modules/segfault-handler
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@18.14.2 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v18.14.2/node-v18.14.2-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v18.14.2/node-v18.14.2-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v18.14.2/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v18.14.2/SHASUMS256.txt
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/lib/node_modules/ironfish/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/ironfish/node_modules/segfault-handler/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/ironfish/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/18.14.2/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/18.14.2',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/ironfish/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/18.14.2/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/usr/lib/node_modules/ironfish/node_modules/segfault-handler',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: not found: make
npm ERR! gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/ironfish/node_modules/node-gyp/node_modules/which/which.js:10:17)
npm ERR! gyp ERR! stack     at /usr/lib/node_modules/ironfish/node_modules/node-gyp/node_modules/which/which.js:57:18
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at step (/usr/lib/node_modules/ironfish/node_modules/node-gyp/node_modules/which/which.js:54:21)
npm ERR! gyp ERR! stack     at /usr/lib/node_modules/ironfish/node_modules/node-gyp/node_modules/which/which.js:71:22
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at subStep (/usr/lib/node_modules/ironfish/node_modules/node-gyp/node_modules/which/which.js:69:33)
npm ERR! gyp ERR! stack     at /usr/lib/node_modules/ironfish/node_modules/node-gyp/node_modules/which/which.js:80:22
npm ERR! gyp ERR! stack     at /usr/lib/node_modules/ironfish/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /usr/lib/node_modules/ironfish/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! System Linux 5.4.0-139-generic
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/ironfish/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /usr/lib/node_modules/ironfish/node_modules/segfault-handler
npm ERR! gyp ERR! node -v v18.14.2
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok
```

### Graffiti

cyberkd

**Comment by dguenther** [comment]
This is an issue with missing dependencies on your local environment -- if you run `apt-get install build-essentials`, it should fix the missing `make`. Regardless, I believe this should no longer be necessary on the latest version of `ironfish`.
