### ISSUE TITLE
Cannot convert amount to a BigInt in 0.1.69

### ISSUE THREAD

**Issue by ziggy010** [iron-fish/ironfish#3555]
### What happened?

Hey there, 

In the latest update, while sending the iron to other wallet, there's a bug, 'Cannot convert amount of iron to a BigInt.

<img width="1050" alt="Screenshot 2023-02-25 at 1 26 51 PM" src="https://user-images.githubusercontent.com/93469715/221345296-18fd46a0-e3c8-4fa5-9cf5-800199dcae75.png">

### Version

v0.1.69

### Relevant log output

```shell
SyntaxError: Cannot convert 0.5 to a BigInt
    at BigInt (<anonymous>)
    at Object.tryParse (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/utils/bigint.js:113:17)
    at CurrencyUtils.decodeTry (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/utils/currency.js:31:37)
    at Object.promptCurrency (/usr/lib/node_modules/ironfish/build/src/utils/currency.js:27:53)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Send.start (/usr/lib/node_modules/ironfish/build/src/commands/wallet/send.js:47:22)
    at async Send.run (/usr/lib/node_modules/ironfish/build/src/command.js:24:13)
    at async Send._run (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/config/config.js:272:25)
    at async Object.run (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/main.js:74:5)
```

### Graffiti

Ziggy

**Comment by irontankfish** [comment]
I've noticed that too. I'll try to fix this

**Comment by ziggy010** [comment]
> I've noticed that too. I'll try to fix this

Any points for catching this bug? Can i try to solve it too?

**Comment by velyar** [comment]
I confirm, same error.
![image](https://user-images.githubusercontent.com/22917604/221355115-14e96dd4-6f4e-440a-93f9-34f9d99f0d04.png)

**Comment by irontankfish** [comment]
Went through the code, and the reference to BigInt is more than once for the amount, so there might be a reason that they are making it BigInt. I'll check with the developers if there is a particular reason they are doing that. Maybe it's just for the testnet. I'll double check and see

**Comment by hughy** [comment]
Please check that you've restarted your node after updating. You can run `ironfish status` to see which version your node is running.

It looks like your CLI is running v0.1.69, but your node is still using an earlier version.
