### ISSUE TITLE
I can't see my wallet blance

### ISSUE THREAD

**Issue by joykali569** [iron-fish/ironfish#3566]
### What happened?

my wallet balance does not showing.

VERSION
  ironfish/0.1.70 linux-x64 node-v18.14.0
root@joyironfish:~# ironfish wallet:balance joy
Account: joy
Error: invalid BigNumber value (argument="value", value=undefined, code=INVALID_ARGUMENT, version=bignumber/5.7.0)
    at Logger.makeError (/usr/lib/node_modules/ironfish/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/usr/lib/node_modules/ironfish/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at Logger.throwArgumentError (/usr/lib/node_modules/ironfish/node_modules/@ethersproject/logger/lib/index.js:250:21)
    at BigNumber.from (/usr/lib/node_modules/ironfish/node_modules/@ethersproject/bignumber/lib/bignumber.js:239:23)
    at Object.formatFixed (/usr/lib/node_modules/ironfish/node_modules/@ethersproject/bignumber/lib/fixednumber.js:43:35)
    at FixedNumberUtils.render (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/utils/fixedNumber.js:10:35)
    at CurrencyUtils.renderIron (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/utils/currency.js:46:53)
    at BalanceCommand.start (/usr/lib/node_modules/ironfish/build/src/commands/wallet/balance.js:37:60)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BalanceCommand.run (/usr/lib/node_modules/ironfish/build/src/command.js:24:13)

### Version

ironfish/0.1.70 linux-x64 node-v18.14.0

### Debug output

```shell
root@joyironfish:~# ironfish debug
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version               0.1.70 @ 6fb75f4
Iron Fish library               0.0.47 @ 6fb75f4
Operating system                Linux x64
CPU model(s)                    DO-Premium-AMD
CPU threads                     4
RAM total                       7.76 GiB
Heap total                      2.00 GiB
Node version                    v18.14.0
ironfish in PATH                true
Garbage Collector Exposed       false
Telemetry enabled               true
Node name                       joy
Block graffiti                  joy
root@joyironfish:~#
```

### Relevant log output

```shell
Account: joy
Error: invalid BigNumber value (argument="value", value=undefined, code=INVALID_ARGUMENT, version=bignumber/5.7.0)
    at Logger.makeError (/usr/lib/node_modules/ironfish/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/usr/lib/node_modules/ironfish/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at Logger.throwArgumentError (/usr/lib/node_modules/ironfish/node_modules/@ethersproject/logger/lib/index.js:250:21)
    at BigNumber.from (/usr/lib/node_modules/ironfish/node_modules/@ethersproject/bignumber/lib/bignumber.js:239:23)
    at Object.formatFixed (/usr/lib/node_modules/ironfish/node_modules/@ethersproject/bignumber/lib/fixednumber.js:43:35)
    at FixedNumberUtils.render (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/utils/fixedNumber.js:10:35)
    at CurrencyUtils.renderIron (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/utils/currency.js:46:53)
    at BalanceCommand.start (/usr/lib/node_modules/ironfish/build/src/commands/wallet/balance.js:37:60)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BalanceCommand.run (/usr/lib/node_modules/ironfish/build/src/command.js:24:13)
```

### Graffiti

joy

**Comment by hughy** [comment]
Please check that you've restarted your node after updating to version 0.1.70.

You can see which version your node is running with `ironfish status`

**Comment by holahula** [comment]
stale - closing
