### ISSUE TITLE
Genesis Block

### ISSUE THREAD

**Issue by Thomas-Veil** [iron-fish/ironfish#3626]
### What happened?

Error: Genesis block in network definition does not match existing chain genesis block

### Version

0.1.71

### Debug output

```shell
Error: Genesis block in network definition does not match existing chain genesis block
    at Function.isTrue (/root/ironfish/ironfish/src/assert.ts:54:13)
    at Blockchain.open (/root/ironfish/ironfish/src/blockchain/blockchain.ts:303:14)
    at IronfishNode.openDB (/root/ironfish/ironfish/src/node.ts:310:7)
    at Object.waitForOpen (/root/ironfish/ironfish/src/utils/node.ts:17:7)
    at Start.start (/root/ironfish/ironfish-cli/src/commands/start.ts:218:5)
    at Start.run (/root/ironfish/ironfish-cli/src/command.ts:73:7)
    at async Start._run (/root/ironfish/ironfish-cli/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/root/ironfish/ironfish-cli/node_modules/@oclif/core/lib/config/config.js:272:25)
    at async Object.run (/root/ironfish/ironfish-cli/node_modules/@oclif/core/lib/main.js:74:5)
```

### Graffiti

Hello_World

**Comment by dguenther** [comment]
Closing this, we reset to a new testnet on 0.1.71, so this is expected. I agree with wd021, we recommend installing 0.1.70 by running `npm install -g ironfish@0.1.70`.
