### ISSUE TITLE
Node crash when invalid rpc parameters sent

### ISSUE THREAD

**Issue by maxhiker** [iron-fish/ironfish#3662]
### What happened?

I sent incorrecly formatted feeRate field in request to RPC-server and node crashed. 

### Version

0.1.70

### Debug output

```shell
Iron Fish version                  0.1.70 @ 6fb75f4
Iron Fish library                  0.0.47 @ 6fb75f4
Operating system                   Linux x64
CPU model(s)                       Intel(R) Core(TM) i7-3612QM CPU @ 2.10GHz
CPU threads                        8
RAM total                          9.18 GiB
Heap total                         2.00 GiB
Node version                       v18.15.0
ironfish in PATH                   true
Garbage Collector Exposed          false
Telemetry enabled                  false
Node name                          
Block graffiti
```

### Relevant log output

```shell
/home/user/.nvm/versions/node/v18.15.0/lib/node_modules/ironfish/node_modules/yup/lib/util/createValidation.js:64
    return (0, _extends2.default)(new _ValidationError.default(formatError(message, params), value, path, type), {
                                  ^
ValidationError: Must be encoded currency
    at createError (/home/user/.nvm/versions/node/v18.15.0/lib/node_modules/ironfish/node_modules/yup/lib/util/createValidation.js:64:35)
    at /home/user/.nvm/versions/node/v18.15.0/lib/node_modules/ironfish/node_modules/yup/lib/util/createValidation.js:113:108
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  value: '0.00000001',
  path: 'feeRate',
  type: 'currency',
  errors: [ 'Must be encoded currency' ],
  inner: [],
  params: {
    path: 'feeRate',
    value: '0.00000001',
    originalValue: '0.00000001',
    label: undefined
  }
}
```

### Graffiti

maxhiker

**Comment by hughy** [comment]
Thanks for reporting this! Fix is in #3688
