### ISSUE TITLE
failed to start ironfish 0.1.72

### ISSUE THREAD

**Issue by xqjcool1** [iron-fish/ironfish#3667]
### What happened?

I updated the ironfish to version 0.1.72 and run "ironfish start". It failed to start and print Error information.

### Version

v0.1.72

### Relevant log output

```shell
root@DESKTOP-7B1REV8:/home/xqjcool# ironfish start


::::::::::          :::::::::::::::::
::::::::::::       :::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::::   ::::::::::::::::::::::::
 ::::::::::::: ::::::::::        :::::::::
   :::::::::::::::::::::          ::::::::::
   :::::::::::::::::::::          :::::::::
 ::::::::::::: ::::::::::        :::::::::
::::::::::::::   ::::::::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::       :::::::::::::::::::
::::::::::           ::::::::::::::::

Version       0.1.72 @ 2c7f84a
Node Name     xqjcool
Graffiti      xqjcool
Peer Identity 86/as9/3Rt2sA9UHhlpHmh9ozosoGkHIYU1Xug20OGg=
Peer Agent    ironfish/0.1.72/2c7f84a
Peer Port     9033
Bootstrap     1.test.bn.ironfish.network,2.test.bn.ironfish.network

Error: Genesis block in network definition does not match existing chain genesis block
    at Assert.isTrue (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/assert.js:46:19)
    at Blockchain.open (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/blockchain/blockchain.js:173:29)
    at async IronfishNode.openDB (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/node.js:202:13)
    at async Object.waitForOpen (/usr/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/utils/node.js:16:13)
    at async Start.start (/usr/lib/node_modules/ironfish/build/src/commands/start.js:105:9)
    at async Start.run (/usr/lib/node_modules/ironfish/build/src/command.js:24:13)
    at async Start._run (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/config/config.js:272:25)
    at async Object.run (/usr/lib/node_modules/ironfish/node_modules/@oclif/core/lib/main.js:74:5)
```

### Graffiti

xqjcool

**Comment by YuriChetverikov** [comment]
`ironfish reset` → `ironfish start`

from [discord](https://discord.com/channels/771503434028941353/828803908067262484/1097180714388164658)
