### ISSUE TITLE
Launching ironfish error

### ISSUE THREAD

**Issue by foss-solutions** [iron-fish/ironfish#3814]
Trying to launch ironfish on Linux Mint. However it throws me an error that i can't fix

```
/usr/local/lib/node_modules/ironfish/node_modules/@ironfish/rust-nodejs/index.js:244
    throw loadError
    ^

Error: Cannot find module '@ironfish/rust-nodejs-linux-x64-gnu'
Require stack:
- /usr/local/lib/node_modules/ironfish/node_modules/@ironfish/rust-nodejs/index.js
- /usr/local/lib/node_modules/ironfish/bin/run
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/ironfish/node_modules/@ironfish/rust-nodejs/index.js:184:31)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/ironfish/node_modules/@ironfish/rust-nodejs/index.js',
    '/usr/local/lib/node_modules/ironfish/bin/run'
  ]
}
```

![image_2023-04-21_12-08-28](https://user-images.githubusercontent.com/112813404/233610961-e553ad5b-e873-4a7c-afa3-3773514fa275.png)

### Version

v1.0.0

**Comment by foss-solutions** [comment]
My bad. forgot to install js via npm

**Comment by Wysiwyg76** [comment]
Hi, I have exactly the same error output when I try to launch ironfish. 
I use Ubuntu 22.04, nodejs v18.16, npm v9.5.1

**Comment by rbfx4x** [comment]
@foss-solutions Please explain exactly how you fixed it. I have the same problem

**Comment by Wysiwyg76** [comment]
Hi, I had exactly the same error (on Ubuntu 22, NodeJS 18)
In my situation, it seems to be a conflict with a previous install of oreos light wallet (that use rust-nodejs)
On a fresh VM, I run ironfish successfully.

**Comment by rbfx4x** [comment]
I never thought of Oreos getting in the way.  
Somehow I may have "fixed" something by running Nodes Guru's script a couple of times. Node now running and syncing as a service. It at least looks OK
