### ISSUE TITLE
Error: Genesis block in network definition does not match existing chain genesis block

### ISSUE THREAD

**Issue by christiangelone** [iron-fish/ironfish#3826]
### What happened?

After upgrading from `v0.1.76` to `v1.0.1`
I ended up with the following error when i try to run any command:
```bash
ironfish wallet:which
Error: Genesis block in network definition does not match existing chain genesis block
    at Assert.isTrue (/Users/username/.nvm/versions/node/v18.16.0/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/assert.js:46:19)
    at Blockchain.open (/Users/username/.nvm/versions/node/v18.16.0/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/blockchain/blockchain.js:178:29)
    at async IronfishNode.openDB (/Users/username/.nvm/versions/node/v18.16.0/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/node.js:205:13)
    at async Object.waitForOpen (/Users/username/.nvm/versions/node/v18.16.0/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/utils/node.js:16:13)
    at async IronfishSdk.connectRpc (/Users/username/.nvm/versions/node/v18.16.0/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/sdk.js:140:9)
    at async WhichCommand.start (/Users/username/.nvm/versions/node/v18.16.0/lib/node_modules/ironfish/build/src/commands/wallet/which.js:13:24)
    at async WhichCommand.run (/Users/username/.nvm/versions/node/v18.16.0/lib/node_modules/ironfish/build/src/command.js:24:13)
    at async WhichCommand._run (/Users/username/.nvm/versions/node/v18.16.0/lib/node_modules/ironfish/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/Users/username/.nvm/versions/node/v18.16.0/lib/node_modules/ironfish/node_modules/@oclif/core/lib/config/config.js:272:25)
    at async Object.run (/Users/username/.nvm/versions/node/v18.16.0/lib/node_modules/ironfish/node_modules/@oclif/core/lib/main.js:74:5)
```

### Version

v1.0.1

### Debug output

```shell
ironfish debug
Error: Database is not open. Call IDatabase.open() first
    at get levelup [as levelup] (/Users/username/.nvm/versions/node/v18.16.0/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/storage/levelup/database.js:34:19)
    at LevelupDatabase.getAllIter (/Users/username/.nvm/versions/node/v18.16.0/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/storage/levelup/database.js:144:29)
    at getAllIter.next (<anonymous>)
    at LevelupStore.getAllIter (/Users/username/.nvm/versions/node/v18.16.0/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/storage/levelup/store.js:79:37)
    at getAllIter.next (<anonymous>)
    at WalletDB.loadHeads (/Users/username/.nvm/versions/node/v18.16.0/lib/node_modules/ironfish/node_modules/@ironfish/sdk/build/src/wallet/walletdb/walletdb.js:190:42)
    at loadHeads.next (<anonymous>)
    at Debug.outputRequiringDB (/Users/username/.nvm/versions/node/v18.16.0/lib/node_modules/ironfish/build/src/commands/debug.js:77:44)
    at Debug.start (/Users/username/.nvm/versions/node/v18.16.0/lib/node_modules/ironfish/build/src/commands/debug.js:37:57)
    at async Debug.run (/Users/username/.nvm/versions/node/v18.16.0/lib/node_modules/ironfish/build/src/command.js:24:13)
```

**Comment by wd021** [comment]
run `ironfish mainnet`

**Comment by mail022584** [comment]
try ironfish reset

**Comment by christiangelone** [comment]
Yes, the issue was solved by running `ironfish reset`. Would be great if you can add this on the Documentation :).
