### ISSUE TITLE
OpenError: IO error

### ISSUE THREAD

**Issue by wd021** [iron-fish/ironfish#4831]
### What happened?

Was looking to run the node on testnet and hit this error.

### Version

2.0.0

### Debug output

```shell
ironfish debug
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version                2.0.0 @ f996f89
Iron Fish library                2.0.0 @ f996f89
Operating system                 Linux x64
CPU model(s)                     Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz
CPU threads                      128
RAM total                        1007.21 GiB
Heap total                       4.00 GiB
Node version                     v18.19.1
ironfish in PATH                 true
Garbage Collector Exposed        false
Telemetry enabled                false
Asset Verification enabled       true
Node name
Block graffiti
```

### Relevant log output

```shell
ironfish reset --networkId=0

You are about to destroy your local copy of the blockchain. The following directories and files will be deleted:

Blockchain: /root/.ironfish/databases/chain
Hosts: /root/.ironfish/hosts.json
Your wallet, accounts, and keys will NOT be deleted.

The network ID will be changed from 1 to the new value of 0

Are you sure? (Y)es / (N)o: y
OpenError: IO error: lock /root/.ironfish/databases/wallet/LOCK: Resource temporarily unavailable
    at /usr/lib/node_modules/ironfish/node_modules/levelup/lib/levelup.js:119:23
    at /usr/lib/node_modules/ironfish/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
    at /usr/lib/node_modules/ironfish/node_modules/deferred-leveldown/deferred-leveldown.js:31:21
    at /usr/lib/node_modules/ironfish/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
Deleting databases...... !
```

**Comment by wd021** [comment]
nvm worked it out.
