### ISSUE TITLE
Miner's fee

### ISSUE THREAD

**Issue by sp88011** [iron-fish/ironfish#487]
When mining with multiple threads, I'm getting the following error after a while:
```
Error: Miner's fee is incorrect
    at /usr/local/Cellar/ironfish/17/libexec/node_modules/ironfish/build/src/blockchain/blockchain.js:569:27
    at async LevelupDatabase.withTransaction (/usr/local/Cellar/ironfish/17/libexec/node_modules/ironfish/build/src/storage/database/database.js:39:28)
...
```

**Comment by dguenther** [comment]
We've deployed a fix for this in 0.1.5: https://github.com/iron-fish/ironfish/releases/tag/v0.1.5
