### ISSUE TITLE
Leaderboard rows throws error

### ISSUE THREAD

**Issue by sp88011** [iron-fish/ironfish#506]
https://testnet.ironfish.network/leaderboard

When you click on a row inside the leaderboard, nothing happens on the front-end. However, the console throws an object with an error

```
error: Error: No token available. at https://testnet.ironfish.network/_next/static/chunks/pages/_app-d36cd3a85a66723d60cc.js:1:8646 at l (https://testnet.ironfish.network/_next/static/chunks/main-a76b5552fbb06f190312.js:1:57390) at Generator._invoke (https://testnet.ironfish.network/_next/static/chunks/main-a76b5552fbb06f190312.js:1:57178) at Generator.throw (https://testnet.ironfish.network/_next/static/chunks/main-a76b5552fbb06f190312.js:1:57819) at n (https://testnet.ironfish.network/_next/static/chunks/pages/_app-d36cd3a85a66723d60cc.js:1:91383) at c (https://testnet.ironfish.network/_next/static/chunks/pages/_app-d36cd3a85a66723d60cc.js:1:91622)
status: "not_found"
[[Prototype]]: Object
```
![image](https://user-images.githubusercontent.com/5287078/144317931-fdee3d80-0b8b-41f2-8b49-34d542c5bfef.png)

**Comment by dguenther** [comment]
This should be fixed now -- if not, could you reopen the issue and add some details about the user that doesn't work?
