### ISSUE TITLE
Node crashes when running 'ironfish logs'

### ISSUE THREAD

**Issue by jackkates** [iron-fish/ironfish#507]
Node crashes with BigInt (maybe the difficulty?) serialization error when tailing the logs. Occurs in both verbose and normal mode, and happens especially if you are also running the miner. 

![image](https://user-images.githubusercontent.com/1587680/144322644-6c83c6d2-64f6-4eb3-96c7-3fe553a5476f.png)

```WebSocket server started at :::9033

Connected to the Iron Fish network

Starting sync from AxMVf78. work: +2670289461, ours: 4051, theirs: 4052

Finding ancestor using linear search on last 3 blocks starting at 00000...9dc00 (4051) from peer AxMVf78 at 4052

Found peer AxMVf78 ancestor 00000...9dc00, syncing from 4051 -> 4052 (1) after 1 requests

Requesting 20 blocks starting at 00000...9dc00 (4051) from AxMVf78

Finished syncing 1 blocks from AxMVf78

/usr/local/Cellar/ironfish/17/libexec/node_modules/js-message/Message.js:38

        return JSON.stringify(

                    ^

TypeError: Do not know how to serialize a BigInt

    at JSON.stringify (<anonymous>)

    at Message.getJSON [as JSON] (/usr/local/Cellar/ironfish/17/libexec/node_modules/js-message/Message.js:38:21)

    at Parser.format (/usr/local/Cellar/ironfish/17/libexec/node_modules/node-ipc/entities/EventParser.js:21:21)

    at Server.emit (/usr/local/Cellar/ironfish/17/libexec/node_modules/node-ipc/dao/socketServer.js:79:29)

    at IpcAdapter.emitStream (/usr/local/Cellar/ironfish/17/libexec/node_modules/ironfish/build/src/rpc/adapters/ipcAdapter.js:206:21)

    at Request.onStream (/usr/local/Cellar/ironfish/17/libexec/node_modules/ironfish/build/src/rpc/adapters/ipcAdapter.js:180:18)

    at Request.stream (/usr/local/Cellar/ironfish/17/libexec/node_modules/ironfish/build/src/rpc/request.js:41:14)

    at InterceptReporter.callback (/usr/local/Cellar/ironfish/17/libexec/node_modules/ironfish/build/src/rpc/routes/node/getLogStream.js:41:17)

    at InterceptReporter.log (/usr/local/Cellar/ironfish/17/libexec/node_modules/ironfish/build/src/logger/reporters/intercept.js:12:14)

    at _log (/usr/local/Cellar/ironfish/17/libexec/node_modules/consola/dist/consola.js:1:7915)
```

My graffiti is rainjackets

**Comment by dguenther** [comment]
Thanks for the bug report! Could you fill out [the form here](https://docs.google.com/forms/d/e/1FAIpQLSelFU47XxF6U8Tatn0K79uQ4MLpGM2DtEwtg-WhFxt2TGLs1A/viewform) if you're interested in testnet credit.

For anyone looking at fixing this, we have a serializer called IJSON that handles bigints already -- The fix might be to proactively serialize the logs in the InterceptReporter or the RPC stream before sending them through node-ipc.

**Comment by mat-if** [comment]
Yeah, closing as this appears to be resolved, thanks
