### ISSUE TITLE
Miner crashed and required a restart

### ISSUE THREAD

**Issue by alterkahn** [iron-fish/ironfish#510]
My miner mined 1 block and crashed with the following message right after:
```
Dec 01 22:26:50 vmi675023.contaboserver.net yarn[222680]: error Command failed with exit code 1.
Dec 01 22:26:50 vmi675023.contaboserver.net yarn[222680]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

And works well a couple of hours after the restart.

**Comment by alterkahn** [comment]
and again crashed with the same error right after mined a block.

**Comment by dguenther** [comment]
Could you test on version 0.1.9 and see if you're still seeing this error? If you have any more error information from the output, that would be useful too -- there's not enough info to investigate it further based on the logs here.

**Comment by alterkahn** [comment]
seems it was a memory issue on two of my miners, but after 0.1.9 update the third one still crashes with the same output, and the node itself also started to crash after update with the next output: 
```
root@vmi675023:~# journalctl -u ironfishd -f
-- Logs begin at Wed 2021-12-01 14:53:03 CET. --
Dec 10 10:56:53 vmi675023.contaboserver.net yarn[3495576]: /root/ironfish/ironfish-rust-nodejs/index.node(+0x83048)[0x7f39f4e03048]
Dec 10 10:56:53 vmi675023.contaboserver.net yarn[3495576]: /root/ironfish/ironfish-rust-nodejs/index.node(+0x45db3)[0x7f39f4dc5db3]
Dec 10 10:56:53 vmi675023.contaboserver.net yarn[3495576]: /root/ironfish/ironfish-rust-nodejs/index.node(+0x58438)[0x7f39f4dd8438]
Dec 10 10:56:53 vmi675023.contaboserver.net yarn[3495576]: /root/ironfish/ironfish-rust-nodejs/index.node(+0x4905b)[0x7f39f4dc905b]
Dec 10 10:56:53 vmi675023.contaboserver.net yarn[3495576]: /usr/bin/node[0xaabfcd]
Dec 10 10:56:53 vmi675023.contaboserver.net yarn[3495576]: /usr/bin/node[0xd4a35e]
Dec 10 10:56:53 vmi675023.contaboserver.net yarn[3495576]: /usr/bin/node(_ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE+0xaf)[0xd4b77f]
Dec 10 10:56:53 vmi675023.contaboserver.net yarn[3495576]: /usr/bin/node[0x15e78f9]
Dec 10 10:56:55 vmi675023.contaboserver.net yarn[3495557]: error Command failed with exit code 1.
Dec 10 10:56:55 vmi675023.contaboserver.net yarn[3495557]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

what about miner crash logs, I tried to start it manually and observe within a couple of hours but it didn't crash, but when I start it as daemon service it crashed again with the output like above... will try to observe it manually again to get more error logs.

**Comment by alterkahn** [comment]
And I also can't start mining with 128 threads on my 64 cores 128 RAM machine, the maximum amount of threads I can start mining with is 100, otherwise, it stops with the next output:
```
root@Ubuntu-2004-focal-64-minimal ~ # ironfish miners:start -t 128
yarn run v1.22.17
$ yarn build && yarn start:js miners:start -t 128
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run miners:start -t 128
Starting to mine with 128 threads
Mining block 16343 on request 303... done

node:internal/event_target:777
  process.nextTick(() => { throw err; });
                           ^
RangeError [Error]: WebAssembly.Instance(): Out of memory: wasm memory
    at Object.<anonymous> (/root/ironfish/node_modules/blake3-wasm/dist/wasm/nodejs/blake3_js.js:193:22)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/ironfish/node_modules/blake3-wasm/dist/node/hash-fn.js:4:21)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (node:internal/worker:289:10)
    at Worker.[kOnMessage] (node:internal/worker:300:37)
    at MessagePort.<anonymous> (node:internal/worker:201:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:562:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@Ubuntu-2004-focal-64-minimal ~ # ironfish miners:start -t 126
yarn run v1.22.17
$ yarn build && yarn start:js miners:start -t 126
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run miners:start -t 126
Starting to mine with 126 threads
Mining block 16343 on request 306... done

node:internal/event_target:777
  process.nextTick(() => { throw err; });
                           ^
RangeError [Error]: WebAssembly.Instance(): Out of memory: wasm memory
    at Object.<anonymous> (/root/ironfish/node_modules/blake3-wasm/dist/wasm/nodejs/blake3_js.js:193:22)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/ironfish/node_modules/blake3-wasm/dist/node/hash-fn.js:4:21)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (node:internal/worker:289:10)
    at Worker.[kOnMessage] (node:internal/worker:300:37)
    at MessagePort.<anonymous> (node:internal/worker:201:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:562:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Is this a bug?

**Comment by alterkahn** [comment]
And again miner crashed:
```
-- Logs begin at Wed 2021-12-01 14:53:03 CET. --
Dec 11 02:30:32 vmi675023.contaboserver.net yarn[3655838]: /usr/bin/node(_ZN2v88internal23EvacuateNewSpaceVisitor5VisitENS0_10HeapObjectEi+0x1d3)[0xed48b3]
Dec 11 02:30:32 vmi675023.contaboserver.net yarn[3655838]: /usr/bin/node(_ZN2v88internal13FullEvacuator15RawEvacuatePageEPNS0_11MemoryChunkEPl+0xbbe)[0xef40ce]
Dec 11 02:30:32 vmi675023.contaboserver.net yarn[3655838]: /usr/bin/node(_ZN2v88internal9Evacuator12EvacuatePageEPNS0_11MemoryChunkE+0x7f)[0xece52f]
Dec 11 02:30:32 vmi675023.contaboserver.net yarn[3655838]: /usr/bin/node(_ZN2v88internal17PageEvacuationJob3RunEPNS_11JobDelegateE+0x14b)[0xece84b]
Dec 11 02:30:32 vmi675023.contaboserver.net yarn[3655838]: /usr/bin/node(_ZN2v88platform16DefaultJobWorker3RunEv+0x84)[0x18da9e4]
Dec 11 02:30:32 vmi675023.contaboserver.net yarn[3655838]: /usr/bin/node[0xb6d4b5]
Dec 11 02:30:32 vmi675023.contaboserver.net yarn[3655838]: /lib/x86_64-linux-gnu/libpthread.so.0(+0x9609)[0x7eff3c9dd609]
Dec 11 02:30:32 vmi675023.contaboserver.net yarn[3655838]: /lib/x86_64-linux-gnu/libc.so.6(clone+0x43)[0x7eff3c904293]
Dec 11 02:30:32 vmi675023.contaboserver.net yarn[3655817]: error Command failed with exit code 1.
Dec 11 02:30:32 vmi675023.contaboserver.net yarn[3655817]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by alterkahn** [comment]
```
n request 1659... 317293 H/sMining block 17626 on request 1659... 330006 H/sMining block 17626 on request 1659... 358068 H/sMining block 17626 on request 1659... 385464 H/sMining block 17626 on request 1659... 403310 H/sMining block 17626 on request 1659... 413310 H/sMining block 17626 on request 1659... 411392 H/sMining block 17626 on request 1659... 387392 H/sMining block 17626 on request 1659... 385996 H/sMining block 17626 on request 1659... 372082 H/sPID 3661050 received SIGSEGV for address: 0x14201e7df94
Dec 12 00:02:38 vmi675023.contaboserver.net yarn[3661050]: /root/ironfish/node_modules/segfault-handler/build/Release/segfault-handler.node(+0x3785)[0x7fa0754c7785]
Dec 12 00:02:38 vmi675023.contaboserver.net yarn[3661050]: /lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0)[0x7fa077ee53c0]
Dec 12 00:02:38 vmi675023.contaboserver.net yarn[3661050]: /lib/x86_64-linux-gnu/libpthread.so.0(pthread_rwlock_unlock+0xe)[0x7fa077edfb6e]
Dec 12 00:02:38 vmi675023.contaboserver.net yarn[3661050]: /usr/bin/node(_ZN2v88internal6String11WriteToFlatIhEEvS1_PT_ii+0x31)[0x11053b1]
Dec 12 00:02:38 vmi675023.contaboserver.net yarn[3661050]: /usr/bin/node(_ZN2v88internal7JSArray33ArrayJoinConcatToSequentialStringEPNS0_7IsolateEmlmm+0x1f4)[0x10c2e34]
Dec 12 00:02:38 vmi675023.contaboserver.net yarn[3661050]: /usr/bin/node[0x15fcd54]
Dec 12 00:02:39 vmi675023.contaboserver.net yarn[3661031]: error Command failed with exit code 1.
Dec 12 00:02:39 vmi675023.contaboserver.net yarn[3661031]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by alterkahn** [comment]
and again... 

```
root@Ubuntu-2004-focal-64-minimal ~ # journalctl -u ironfishd-miner -f
-- Logs begin at Tue 2021-12-07 14:56:12 CET. --
Dec 13 09:09:21 Ubuntu-2004-focal-64-minimal yarn[755124]: 13: 0x155a336  [/usr/bin/node]
Dec 13 09:09:21 Ubuntu-2004-focal-64-minimal yarn[755124]: 14: 0x156c7a4  [/usr/bin/node]
Dec 13 09:09:21 Ubuntu-2004-focal-64-minimal yarn[755124]: 15: 0x155ac68 uv_run [/usr/bin/node]
Dec 13 09:09:21 Ubuntu-2004-focal-64-minimal yarn[755124]: 16: 0xa3dfe5 node::SpinEventLoop(node::Environment*) [/usr/bin/node]
Dec 13 09:09:21 Ubuntu-2004-focal-64-minimal yarn[755124]: 17: 0xb42dc6 node::NodeMainInstance::Run(node::EnvSerializeInfo const*) [/usr/bin/node]
Dec 13 09:09:21 Ubuntu-2004-focal-64-minimal yarn[755124]: 18: 0xac4812 node::Start(int, char**) [/usr/bin/node]
Dec 13 09:09:21 Ubuntu-2004-focal-64-minimal yarn[755124]: 19: 0x7fe5f6e700b3 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
Dec 13 09:09:21 Ubuntu-2004-focal-64-minimal yarn[755124]: 20: 0xa3bf3c  [/usr/bin/node]
Dec 13 09:09:22 Ubuntu-2004-focal-64-minimal yarn[755105]: error Command failed with exit code 1.
Dec 13 09:09:22 Ubuntu-2004-focal-64-minimal yarn[755105]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm on Version 0.1.10 @ src
