### ISSUE TITLE
RangeError [Error]: WebAssembly.Instance(): Out of memory: wasm memory

### ISSUE THREAD

**Issue by toints** [iron-fish/ironfish#554]
this is the error log:

```
Requesting 20 blocks starting at 8fb5b...82068 (1) from qmw3XDg (labelchain)

node:internal/event_target:777
  process.nextTick(() => { throw err; });
                           ^
RangeError [Error]: WebAssembly.Instance(): Out of memory: wasm memory
    at Object.<anonymous> (/usr/src/app/node_modules/blake3-wasm/dist/wasm/nodejs/blake3_js.js:193:22)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/src/app/node_modules/blake3-wasm/dist/node/hash-fn.js:4:21)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (node:internal/worker:289:10)
    at Worker.[kOnMessage] (node:internal/worker:300:37)
    at MessagePort.<anonymous> (node:internal/worker:201:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:562:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
```

**Comment by deekerno** [comment]
Are you still encountering this issue after upgrading to the newest version?

**Comment by deekerno** [comment]
Closing due to inactivity. If you are still encountering this problem after updating to the newest version, feel free to re-open this issue.
