### ISSUE TITLE
BigInt serialization in node.js

### ISSUE THREAD

**Issue by reshordling** [iron-fish/ironfish#588]
Multiple crashes when handling js-message in a wrong format (empty?) that will also kill the mining node
Graffiti reshire
Ubuntu 20.04

Dell VDS, CPU 32 cores, 128 GB ram
Threads -1 (use all)

```
ironfish          | 2021-12-04T13:00:42.882874044Z
ironfish          | 2021-12-04T13:00:42.882931784Z Version       0.1.8 @ 45df922
ironfish          | 2021-12-04T13:00:42.882963684Z Node Name     reshire
ironfish          | 2021-12-04T13:00:42.882969966Z Peer Identity +cfv78rqO4K1td3OJj6Js7/JpidVqiCA8xba70044mE=
ironfish          | 2021-12-04T13:00:42.882975697Z Peer Agent    if/cli/45df922
ironfish          | 2021-12-04T13:00:42.882980586Z Peer Port     9033
ironfish          | 2021-12-04T13:00:42.882985716Z Bootstrap     test.bn1.ironfish.network
ironfish          | 2021-12-04T13:00:42.882990655Z

....

ironfish          | 2021-12-05T03:18:04.842464640Z Added block seq: 9460, hash: 00000...4e30d, txs: 1, progress: 100.00%, time: 40.7ms
ironfish          | 2021-12-05T03:31:35.154379348Z /usr/src/app/node_modules/js-message/Message.js:38
ironfish          | 2021-12-05T03:31:35.154419714Z         return JSON.stringify(
ironfish          | 2021-12-05T03:31:35.154423341Z                     ^
ironfish          | 2021-12-05T03:31:35.154426327Z
ironfish          | 2021-12-05T03:31:35.154441265Z TypeError: Do not know how to serialize a BigInt
ironfish          | 2021-12-05T03:31:35.154444021Z     at JSON.stringify (<anonymous>)
ironfish          | 2021-12-05T03:31:35.154447227Z     at Message.getJSON [as JSON] (/usr/src/app/node_modules/js-message/Message.js:38:21)
ironfish          | 2021-12-05T03:31:35.154449912Z     at Parser.format (/usr/src/app/node_modules/node-ipc/entities/EventParser.js:21:21)
ironfish          | 2021-12-05T03:31:35.154452387Z     at Server.emit (/usr/src/app/node_modules/node-ipc/dao/socketServer.js:79:29)
ironfish          | 2021-12-05T03:31:35.154455022Z     at IpcAdapter.emitStream (/usr/src/app/node_modules/ironfish/build/src/rpc/adapters/ipcAdapter.js:206:21)
ironfish          | 2021-12-05T03:31:35.154457566Z     at Request.onStream (/usr/src/app/node_modules/ironfish/build/src/rpc/adapters/ipcAdapter.js:180:18)
ironfish          | 2021-12-05T03:31:35.154460322Z     at Request.stream (/usr/src/app/node_modules/ironfish/build/src/rpc/request.js:41:14)
ironfish          | 2021-12-05T03:31:35.154462816Z     at InterceptReporter.callback (/usr/src/app/node_modules/ironfish/build/src/rpc/routes/node/getLogStream.js:41:17)
ironfish          | 2021-12-05T03:31:35.154465501Z     at InterceptReporter.log (/usr/src/app/node_modules/ironfish/build/src/logger/reporters/intercept.js:12:14)
ironfish          | 2021-12-05T03:31:35.154468126Z     at _log (/usr/src/app/node_modules/consola/dist/consola.js:1:7915)
ironfish          | 2021-12-05T03:31:35.907525260Z
ironfish          | 2021-12-05T03:31:35.907560337Z WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
ironfish          | 2021-12-05T03:31:35.907563493Z
ironfish          | 2021-12-05T03:31:36.914362922Z
```

**Comment by dguenther** [comment]
Duplicates #507
