### ISSUE TITLE
M1 Mac brew installed ironfish breaks

### ISSUE THREAD

**Issue by jgkogan** [iron-fish/ironfish#621]
homebrew installs it on the M1 without error, but then when you run the command ironfish, it leads to this:

```
ironfish
/opt/homebrew/Cellar/ironfish/11/libexec/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: dlopen(/opt/homebrew/Cellar/ironfish/11/libexec/node_modules/segfault-handler/build/Release/segfault-handler.node, 0x0001): tried: '/opt/homebrew/Cellar/ironfish/11/libexec/node_modules/segfault-handler/build/Release/segfault-handler.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/segfault-handler.node' (no such file), '/usr/lib/segfault-handler.node' (no such file)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at bindings (/opt/homebrew/Cellar/ironfish/11/libexec/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/opt/homebrew/Cellar/ironfish/11/libexec/node_modules/segfault-handler/index.js:3:37)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by dguenther** [comment]
Duplicates #9. Our Getting Started docs indicate that M1 is not supported on Homebrew, but I made a change to the Homebrew tap so that it now displays an error when you try to install Ironfish via Homebrew on M1:

![image (1)](https://user-images.githubusercontent.com/767083/145329389-a183cd8f-7e12-4572-8a00-2cd84415da99.png)
