### ISSUE TITLE
RangeError [Error]: WebAssembly.Instance(): Out of memory: wasm memory

### ISSUE THREAD

**Issue by artasoftware** [iron-fish/ironfish#632]
Trying to run docker container at:
AMD Ryzen Threadripper 3990X 64-Core Processor x128 cores
256 GB RAM

After starting container always see this kind of log:

```
Version       0.1.8 @ 45df922
Node Name     NONE
Peer Identity tAWaJJ3zvBhA/Xy2iKd+JPaOZNVQ0pnq1loaqNMXXTM=
Peer Agent    if/cli/45df922
Peer Port     9033
Bootstrap     test.bn1.ironfish.network

WebSocket server started at :::9033
Connected to the Iron Fish network
Starting sync from SwcJnM2. work: +704895554963858, ours: 137, theirs: 12317
Finding ancestor using linear search on last 3 blocks starting at 00002...7034c (137) from peer SwcJnM2 at 12317
Found peer SwcJnM2 ancestor 00002...7034c, syncing from 137 -> 12317 (12180) after 1 requests
Requesting 20 blocks starting at 00002...7034c (137) from SwcJnM2

node:internal/event_target:777
  process.nextTick(() => { throw err; });
                           ^
RangeError [Error]: WebAssembly.Instance(): Out of memory: wasm memory
    at Object.<anonymous> (/usr/src/app/node_modules/blake3-wasm/dist/wasm/nodejs/blake3_js.js:193:22)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/src/app/node_modules/blake3-wasm/dist/node/hash-fn.js:4:21)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (node:internal/worker:289:10)
    at Worker.[kOnMessage] (node:internal/worker:300:37)
    at MessagePort.<anonymous> (node:internal/worker:201:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:562:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)

```

**Comment by NullSoldier** [comment]
Great find, we'll look into it. We just deployed a fix related to this in v0.1.9 so I'll look and very if the fix we did is related to this.

**Comment by artasoftware** [comment]
Unfortunately no:

```
Version       0.1.9 @ cca3c88
Node Name     NONE
Peer Identity tAWaJJ3zvBhA/Xy2iKd+JPaOZNVQ0pnq1loaqNMXXTM=
Peer Agent    if/cli/cca3c88
Peer Port     9033
Bootstrap     test.bn1.ironfish.network

WebSocket server started at :::9033

node:internal/event_target:777
  process.nextTick(() => { throw err; });
                           ^
RangeError [Error]: WebAssembly.Instance(): Out of memory: wasm memory
    at Object.<anonymous> (/usr/src/app/node_modules/blake3-wasm/dist/wasm/nodejs/blake3_js.js:193:22)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/src/app/node_modules/blake3-wasm/dist/node/hash-fn.js:4:21)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (node:internal/worker:289:10)
    at Worker.[kOnMessage] (node:internal/worker:300:37)
    at MessagePort.<anonymous> (node:internal/worker:201:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:562:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
```

By the way OS is: Ubuntu 20.04.3 LTS
Docker: docker-ce  5:20.10.11~3-0~ubuntu-focal

**Comment by dguenther** [comment]
Can you try setting `nodeWorkers` in your config to a smaller value, like 8, and restart your node? You can also pass --workers to the node's start command, like `ironfish start --workers 8`

The node, by default, creates a process for every core on your machine for handling long-running work like verifying transactions. However, each of these processes takes up some memory. I don't expect the node to need more than 8 of these processes on a powerful CPU, so limiting these may free up enough memory for the node to at least start up.

**Comment by artasoftware** [comment]
> Can you try setting `nodeWorkers` in your config to a smaller value, like 8, and restart your node? You can also pass --workers to the node's start command, like `ironfish start --workers 8`
> 
> The node, by default, creates a process for every core on your machine for handling long-running work like verifying transactions. However, each of these processes takes up some memory. I don't expect the node to need more than 8 of these processes on a powerful CPU, so limiting these may free up enough memory for the node to at least start up.

It worked! So I don't need to raise this parameter to have more threads and faster mining? Or how can I calculate the value?

**Comment by dguenther** [comment]
Nice! Mining threads are actually affected by a different value passed to `ironfish miners:start --threads 1` -- By default it's 1, but you can configure it to whatever you want, or pass -1 to use all available cores.

You can run `ironfish workers:status -f` to see all the tasks that need to be run using `nodeWorkers`. The optimal number for `nodeWorkers` is as low as possible, but just high enough where you never see any numbers in the `QUEUE` column change from 0 -- If you see the queue numbers move above 0, then you'd benefit from increasing `nodeWorkers`.
