### ISSUE TITLE
Miner getting killed repeatedly

### ISSUE THREAD

**Issue by aditya-manit** [iron-fish/ironfish#644]
I got my miner getting killed twice with the below log line

```
/usr/src/app/bin/ironfish: line 45:  6282 Killed                  "$NODE" "$DIR/run" "$@"
```

I guess its due to the these two sudden spikes in cpu memory and load, not sure what causing these huge spikes
<img width="987" alt="Screenshot 2021-12-07 at 9 11 29 PM" src="https://user-images.githubusercontent.com/40714633/145060132-d974e793-b7ed-4308-916e-f5185b76aa84.png">

PS: Had posted on testnet website earlier: https://github.com/iron-fish/website-testnet/issues/128

**Comment by aditya-manit** [comment]
Just happened again

<img width="1033" alt="Screenshot 2021-12-08 at 8 19 00 AM" src="https://user-images.githubusercontent.com/40714633/145139642-3d8118eb-6a9d-4857-8b93-8f3c2bf8de4f.png">

**Comment by aditya-manit** [comment]
Earlier my miner went down but the node was up - this time around the node crashed itself - here are the logs

```
Reorganized chain. blocks: 1, old: 00000...2d21f (12615), new: 00000...883d3 (12614), fork: 00000...883d3 (12614)
Added block seq: 12620, hash: 00000...a6e6c, txs: 1, progress: 100.00%, time: 84.4ms
Added block to fork seq: 12635, head-seq: 12635, hash: 00000...5ab9e, head-hash: 00000...0cd53, work: 733000780794844, head-work: 733000780794844, work-diff: 0
Added block seq: 12640, hash: 00000...0320d, txs: 2, progress: 100.00%, time: 5221.1ms
Added block to fork seq: 12643, head-seq: 12643, hash: 00000...3b5da, head-hash: 00000...dc1f2, work: 733653770215232, head-work: 733653770215232, work-diff: 0
Added block seq: 12660, hash: 00000...69511, txs: 2, progress: 100.00%, time: 5139.4ms
Added block seq: 12680, hash: 00000...79a75, txs: 2, progress: 100.00%, time: 5219.4ms
Reorganizing chain from 00000...79a75 (12680) for 00000...631bb (12680) on prev 00000...550db (12679)
Reorganized chain. blocks: 1, old: 00000...79a75 (12680), new: 00000...550db (12679), fork: 00000...550db (12679)
Added block seq: 12680, hash: 00000...631bb, txs: 2, progress: 100.00%, time: 5078.6ms
Added block to fork seq: 12688, head-seq: 12688, hash: 00000...55a48, head-hash: 00000...fe752, work: 737263425547448, head-work: 737263542119204, work-diff: 116571756
Reorganizing chain from 00000...69ad4 (12689) for 00000...a44ca (12689) on prev 00000...fe752 (12688)
Reorganized chain. blocks: 1, old: 00000...69ad4 (12689), new: 00000...fe752 (12688), fork: 00000...fe752 (12688)
Added block seq: 12700, hash: 00000...87b48, txs: 1, progress: 100.00%, time: 74.2ms
Added block seq: 12720, hash: 00000...d25d4, txs: 2, progress: 100.00%, time: 4949.5ms
Added block seq: 12740, hash: 00000...d5b5b, txs: 2, progress: 100.00%, time: 5109.7ms
Added block to fork seq: 12744, head-seq: 12744, hash: 00000...f0c41, head-hash: 00000...25b0c, work: 741769492005294, head-work: 741769530722894, work-diff: 38717600
Added block seq: 12760, hash: 00000...ad2a2, txs: 1, progress: 100.00%, time: 86.6ms
/usr/src/app/node_modules/ironfish/build/src/blockchain/blockchain.js:569
                    throw new Error(verification.reason);
                          ^

Error: Transaction expired
    at /usr/src/app/node_modules/ironfish/build/src/blockchain/blockchain.js:569:27
    at async LevelupDatabase.withTransaction (/usr/src/app/node_modules/ironfish/build/src/storage/database/database.js:39:28)
    at async Blockchain.newBlock (/usr/src/app/node_modules/ironfish/build/src/blockchain/blockchain.js:519:16)
    at async MiningDirector.constructAndMineBlock (/usr/src/app/node_modules/ironfish/build/src/mining/director.js:257:26)
    at async MiningDirector.constructAndMineBlockWithRetry (/usr/src/app/node_modules/ironfish/build/src/mining/director.js:200:26)
    ```

**Comment by dguenther** [comment]
The `Transaction expired` is a separate issue, let's discuss that in #652 . Do you have any more information on the `Killed` error? Could you check if it's still happening on 0.1.9?

**Comment by deekerno** [comment]
Closing due to inactivity. If you are still encountering this problem after updating to the new version, feel free to re-open this issue.
