### ISSUE TITLE
Miner doesn't work with more that 100 threads.

### ISSUE THREAD

**Issue by g1ebas** [iron-fish/ironfish#697]
miners:start -t 255
gives 

$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run miners:start -t 255
Starting to mine with 255 threads
Mining block 16372 on request 224... done

node:internal/event_target:777
  process.nextTick(() => { throw err; });
                           ^
RangeError [Error]: WebAssembly.Instance(): Out of memory: wasm memory
    at Object.<anonymous> (/root/ironfish/node_modules/blake3-wasm/dist/wasm/nodejs/blake3_js.js:193:22)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/ironfish/node_modules/blake3-wasm/dist/node/hash-fn.js:4:21)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (node:internal/worker:289:10)
    at Worker.[kOnMessage] (node:internal/worker:300:37)
    at MessagePort.<anonymous> (node:internal/worker:201:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:562:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)

But 2x100threads + 1x55 threads works good.

**Comment by g1ebas** [comment]
Version       0.1.9 @ src

**Comment by lwisne** [comment]
This is a nofix for now.
