### ISSUE TITLE
node crash with error:  [Out of memory: wasm memory]

### ISSUE THREAD

**Issue by alar0n** [iron-fish/ironfish#705]
Playback Steps:
1. **ironfish start** on node with more than 101vCPU (>=). After 5-10 seconds node will crash with next error:

Version       0.1.9 @ cca3c88
Node Name     NONE
Peer Identity iVt93gJsjuPI7WDe31b9EhosE1wccPmcccrhzgvHjS0=
Peer Agent    if/cli/cca3c88
Peer Port     9033
Bootstrap     test.bn1.ironfish.network

WebSocket server started at :::9033
Connected to the Iron Fish network

node:internal/event_target:777
  process.nextTick(() => { throw err; });
                           ^
RangeError [Error]: WebAssembly.Instance(): Out of memory: wasm memory
    at Object.<anonymous> (/usr/src/app/node_modules/blake3-wasm/dist/wasm/nodejs/blake3_js.js:193:22)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/src/app/node_modules/blake3-wasm/dist/node/hash-fn.js:4:21)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (node:internal/worker:289:10)
    at Worker.[kOnMessage] (node:internal/worker:300:37)
    at MessagePort.<anonymous> (node:internal/worker:201:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:562:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)

2. If reduce CPU to 100 or small - node starting without affect and fine worked.

**Comment by deekerno** [comment]
Have you encountered this issue in our newest updates?

**Comment by alar0n** [comment]
hello. No. In v0.15 version work correctly, but H / S 4 times less than on v.14

**Comment by deekerno** [comment]
Noted. Regarding the hash rate, that is a separate issue that we are currently investigating. As such, I'm closing this ticket.
