### ISSUE TITLE
the node crashed because the newBlock Error not catched

### ISSUE THREAD

**Issue by shandongdacongge** [iron-fish/ironfish#710]
today, I find my node is crashed.
and by the log, I find it caused by a not catched Error, the error is throwed in the blockchain.ts
[https://github.com/iron-fish/ironfish/blob/cca3c88fe091ce1aa22d27ec985db8de3df0ea2c/ironfish/src/blockchain/blockchain.ts#L899](url)

and the log is here:
```/root/ironfish/ironfish/build/src/blockchain/blockchain.js:569
                    throw new Error(verification.reason);
                          ^

Error: Transaction expired
    at /root/ironfish/ironfish/build/src/blockchain/blockchain.js:569:27
    at async LevelupDatabase.withTransaction (/root/ironfish/ironfish/build/src/storage/database/database.js:39:28)
    at async Blockchain.newBlock (/root/ironfish/ironfish/build/src/blockchain/blockchain.js:519:16)
    at async MiningDirector.constructAndMineBlock (/root/ironfish/ironfish/build/src/mining/director.js:257:26)
    at async MiningDirector.constructAndMineBlockWithRetry (/root/ironfish/ironfish/build/src/mining/director.js:200:26)
error Command failed with exit code 1.```

**Comment by deekerno** [comment]
This should have been fixed in releases v0.1.11 and v0.1.12. If you are still encountering this issue, feel free to re-open.
