### ISSUE TITLE
Error: Expected value not to be null

### ISSUE THREAD

**Issue by Megavolv** [iron-fish/ironfish#712]
Hello! Ive got error:

```
Peer EHraEdr sent orphan 00000...4600a (17255), syncing orphan chain.
Error when adding new block 17255 from EHraEdr: Error: Expected value not to be null
    at Function.isNotNull (/home/peter/ironfish/ironfish/build/src/assert.js:23:19)
    at Syncer.startSync (/home/peter/ironfish/ironfish/build/src/syncer.js:104:25)
    at Syncer.addBlock (/home/peter/ironfish/ironfish/build/src/syncer.js:284:22)
    at async Syncer.addNewBlock (/home/peter/ironfish/ironfish/build/src/syncer.js:311:34)
    at async PeerNetwork.onNewBlock (/home/peter/ironfish/ironfish/build/src/network/peerNetwork.js:479:20)
    at async hdlr (/home/peter/ironfish/ironfish/build/src/network/peerNetwork.js:254:20)
    at async GossipRouter.handle (/home/peter/ironfish/ironfish/build/src/network/messageRouters/gossip.js:62:24)
    at async PeerNetwork.handleMessage (/home/peter/ironfish/ironfish/build/src/network/peerNetwork.js:371:17)
    at async Promise.all (index 0)
    at async Event.emitAsync (/home/peter/ironfish/ironfish/build/src/event.js:64:9)
```

**Comment by mat-if** [comment]
Going to close as I believe this is resolved
