### ISSUE TITLE
did not send GetBlockHashes in state DISCONNECTED

### ISSUE THREAD

**Issue by knight2008** [iron-fish/ironfish#760]
Added block seq: 22500, hash: 00000...0663e, txs: 1, progress: 97.60%, time: 6143.3ms
Peer 0eG+OCX (mortycat) sent orphan 00000...f7dd9 (18608), syncing orphan chain.
Starting sync from 0eG+OCX (mortycat). work: +-116568366207595, ours: 22506, theirs: 17696
Finding ancestor using linear search on last 3 blocks starting at 00000...6b704 (22506) from peer 0eG+OCX (mortycat) at 17696
Stopping sync from 0eG+OCX (mortycat) due to Error: 0eG+OCXqeUOoqGw5IVDG1k5UYe3W1/05EDjkA1LeNjk= did not send GetBlockHashes in state DISCONNECTED
    at /root/ironfish/ironfish/build/src/network/messageRouters/rpc.js:124:39
    at new Promise (<anonymous>)
    at RpcRouter.requestFrom (/root/ironfish/ironfish/build/src/network/messageRouters/rpc.js:70:16)
    at PeerNetwork.requestFrom (/root/ironfish/ironfish/build/src/network/peerNetwork.js:306:37)
    at PeerNetwork.getBlockHashes (/root/ironfish/ironfish/build/src/network/peerNetwork.js:330:37)
    at Syncer.findAncestor (/root/ironfish/ironfish/build/src/syncer.js:179:51)
    at Syncer.syncFrom (/root/ironfish/ironfish/build/src/syncer.js:139:61)
    at Syncer.startSync (/root/ironfish/ironfish/build/src/syncer.js:111:30)
    at Syncer.addBlock (/root/ironfish/ironfish/build/src/syncer.js:284:22)
    at async Syncer.addNewBlock (/root/ironfish/ironfish/build/src/syncer.js:311:34)
Peer 0eG+OCX (mortycat) disconnected (DISCONNECTED) while syncing.

**Comment by knight2008** [comment]
> bin/ironfish  version 
name       ironfish
version    0.1.9
git        src
runtime    node/16.13.1

**Comment by lwisne** [comment]
We think this is fixed now. Closing. Let me know if you believe otherwise.
