### ISSUE TITLE
Stack trace in the node after forked block.

### ISSUE THREAD

**Issue by RomanShcherbich** [iron-fish/ironfish#761]
Status of: STARTED - 2 miners, 1 mined ( appeared 1 mined)
...
Syncer               SYNCING ...
...
Checking Node LOG:
```
Dec 15 17:40:48 17674.example.ru yarn[2015]: Requesting 2 blocks starting at 00000...d9300 (18296) from RFLCDwz (Sukar)
Dec 15 17:40:50 17674.example.ru yarn[2015]: Requesting 2 blocks starting at 00000...e467b (18298) from RFLCDwz (Sukar)
Dec 15 17:40:51 17674.example.ru yarn[2015]: Requesting 2 blocks starting at 00000...95464 (18300) from RFLCDwz (Sukar)
Dec 15 17:40:51 17674.example.ru yarn[2015]: Requesting 2 blocks starting at 00000...70e84 (18302) from RFLCDwz (Sukar)
Dec 15 17:40:52 17674.example.ru yarn[2015]: Requesting 2 blocks starting at 00000...d8062 (18304) from RFLCDwz (Sukar)
Dec 15 17:40:53 17674.example.ru yarn[2015]: Requesting 2 blocks starting at 00000...4bb09 (18306) from RFLCDwz (Sukar)
Dec 15 17:40:54 17674.example.ru yarn[2015]: Requesting 2 blocks starting at 00000...5b4db (18308) from RFLCDwz (Sukar)
Dec 15 17:40:55 17674.example.ru yarn[2015]: Requesting 2 blocks starting at 00000...2ae0b (18310) from RFLCDwz (Sukar)
Dec 15 17:40:57 17674.example.ru yarn[2015]: Requesting 2 blocks starting at 00000...7da31 (18312) from RFLCDwz (Sukar)
Dec 15 17:40:58 17674.example.ru yarn[2015]: Requesting 2 blocks starting at 00000...20190 (18314) from RFLCDwz (Sukar)
Dec 15 17:40:59 17674.example.ru yarn[2015]: Requesting 2 blocks starting at 00000...88a08 (18316) from RFLCDwz (Sukar)
Dec 15 17:40:59 17674.example.ru yarn[2015]: Requesting 2 blocks starting at 00000...29186 (18318) from RFLCDwz (Sukar)
Dec 15 17:41:00 17674.example.ru yarn[2015]: Requesting 2 blocks starting at 00000...ef0d5 (18320) from RFLCDwz (Sukar)
Dec 15 17:41:01 17674.example.ru yarn[2015]: Requesting 2 blocks starting at 00000...93608 (18322) from RFLCDwz (Sukar)
Dec 15 17:41:02 17674.example.ru yarn[2015]: Requesting 2 blocks starting at 00000...82fcb (18324) from RFLCDwz (Sukar)
Dec 15 17:41:02 17674.example.ru yarn[2015]: Requesting 2 blocks starting at 00000...8c3c9 (18326) from RFLCDwz (Sukar)
Dec 15 17:41:02 17674.example.ru yarn[2015]: Requesting 2 blocks starting at 00000...6bc5b (18328) from RFLCDwz (Sukar)
Dec 15 17:41:03 17674.example.ru yarn[2015]: Requesting 2 blocks starting at 00000...37189 (18330) from RFLCDwz (Sukar)
Dec 15 17:41:04 17674.example.ru yarn[2015]: Requesting 2 blocks starting at 00000...17c53 (18332) from RFLCDwz (Sukar)
Dec 15 17:41:14 17674.example.ru yarn[2015]: Reorganizing chain from 00000...1d217 (23216) for 00000...800ca (23216) on prev 00000...c2359 (23215)
Dec 15 17:41:14 17674.example.ru yarn[2015]: Reorganized chain. blocks: 1, old: 00000...1d217 (23216), new: 00000...c2359 (23215), fork: 00000...c2359 (23215)
Dec 15 17:41:23 17674.example.ru yarn[2015]: Added block to fork seq: 23216, head-seq: 23216, hash: 00000...c8b59, head-hash: 00000...800ca, work: 1418422357047217, head-work: 1418422376558282, work-diff: 19511065
Dec 15 17:41:24 17674.example.ru yarn[2015]: Invalid block adding to fork 00000...153a4 (18374): Transaction expired
Dec 15 17:41:24 17674.example.ru yarn[2015]: Peer RFLCDwz (Sukar) sent an invalid block. score: 10, hash: 00000...153a4 (
Dec 15 17:41:24 17674.example.ru yarn[2015]:           18374
Dec 15 17:41:24 17674.example.ru yarn[2015]:         ), reason: Transaction expired
Dec 15 17:41:24 17674.example.ru yarn[2015]: Peer RFLCDwz (Sukar) has been banned: Transaction expired
Dec 15 17:41:24 17674.example.ru yarn[2015]: Peer RFLCDwz (Sukar) disconnected (DISCONNECTED) while syncing.
Dec 15 17:42:32 17674.example.ru yarn[2015]: Added block seq: 23220, hash: 00000...69072, txs: 1, progress: 100.00%, time: 162.5ms
Dec 15 17:42:52 17674.example.ru yarn[2015]: /root/ironfish/ironfish/build/src/blockchain/blockchain.js:569
Dec 15 17:42:52 17674.example.ru yarn[2015]:                     throw new Error(verification.reason);
Dec 15 17:42:52 17674.example.ru yarn[2015]:                           ^
Dec 15 17:42:52 17674.example.ru yarn[2015]: Error: Transaction expired
Dec 15 17:42:52 17674.example.ru yarn[2015]:     at /root/ironfish/ironfish/build/src/blockchain/blockchain.js:569:27
Dec 15 17:42:52 17674.example.ru yarn[2015]:     at async LevelupDatabase.withTransaction (/root/ironfish/ironfish/build/src/storage/database/database.js:39:28)
Dec 15 17:42:52 17674.example.ru yarn[2015]:     at async Blockchain.newBlock (/root/ironfish/ironfish/build/src/blockchain/blockchain.js:519:16)
Dec 15 17:42:52 17674.example.ru yarn[2015]:     at async MiningDirector.constructAndMineBlock (/root/ironfish/ironfish/build/src/mining/director.js:257:26)
Dec 15 17:42:52 17674.example.ru yarn[2015]:     at async MiningDirector.constructAndMineBlockWithRetry (/root/ironfish/ironfish/build/src/mining/director.js:200:26)
Dec 15 17:42:52 17674.example.ru yarn[1822]: error Command failed with exit code 1.
Dec 15 17:42:52 17674.example.ru yarn[1822]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Saw stack trace and status miner become:

...
Mining               STARTED - 2 miners, 0 mined
...
Syncer               IDLE @ 0.03 blocks per seconds ...
...

**Comment by dguenther** [comment]
This should be fixed as of 0.1.12, please open a new issue if you're still seeing this bug on that version.
