### ISSUE TITLE
Node Force Close version 0.1.12

### ISSUE THREAD

**Issue by ilhamm02** [iron-fish/ironfish#789]
Updated to new version (0.1.12) and in a few moments node force close and can't start again

![image](https://user-images.githubusercontent.com/24799581/146632668-eb32bef7-c25e-4d9e-a899-958c18e7a475.png)

```
/root/ironfish/ironfish/build/src/account/accounts.js:363
                        throw new Error('nullifierToNote mappings must have a corresponding noteToNullifier map');
                              ^

Error: nullifierToNote mappings must have a corresponding noteToNullifier map
    at /root/ironfish/ironfish/build/src/account/accounts.js:363:31
    at async LevelupDatabase.withTransaction (/root/ironfish/ironfish/build/src/storage/database/database.js:39:28)
    at async Accounts.removeTransaction (/root/ironfish/ironfish/build/src/account/accounts.js:345:9)
    at async Accounts.expireTransactions (/root/ironfish/ironfish/build/src/account/accounts.js:593:17)
    at async Accounts.eventLoop (/root/ironfish/ironfish/build/src/account/accounts.js:169:9)```

**Comment by ilhamm02** [comment]
Trying to downgrade and still has same issue.

**Comment by deekerno** [comment]
Does this issue still persist after the latest update?

**Comment by deekerno** [comment]
Closing due to inactivity. If you are still encountering this problem after updating to the newest version, feel free to re-open this issue.
