### ISSUE TITLE
Error while sync

### ISSUE THREAD

**Issue by ilhamm02** [iron-fish/ironfish#790]
Error message on log
```
Starting sync from 9x4E8me. work: +101301601309061, ours: 16446, theirs: 20958
Finding ancestor using linear search on last 3 blocks starting at 00000...fd66e (16446) from peer 9x4E8me at 20958
Found peer 9x4E8me ancestor 00000...fd66e, syncing from 16446 -> 20958 (4512) after 1 requests
Requesting 20 blocks starting at 00000...fd66e (16446) from 9x4E8me
Stopping sync from 9x4E8me due to Error: Connection closed while waiting for request GetBlocks: 8
    at onConnectionStateChanged (/root/ironfish/ironfish/build/src/network/messageRouters/rpc.js:80:36)
    at Event.emitAsync (/root/ironfish/ironfish/build/src/event.js:61:39)
    at Event.emit (/root/ironfish/ironfish/build/src/event.js:52:19)
    at WebSocketConnection.setState (/root/ironfish/ironfish/build/src/network/peers/connections/connection.js:99:29)
    at WebSocketConnection.close (/root/ironfish/ironfish/build/src/network/peers/connections/webSocketConnection.js:49:18)
    at PeerConnectionManager.maintainOneConnectionPerPeer (/root/ironfish/ironfish/build/src/network/peers/peerConnectionManager.js:92:46)
    at PeerConnectionManager.eventLoop (/root/ironfish/ironfish/build/src/network/peers/peerConnectionManager.js:52:18)
    at Timeout._onTimeout (/root/ironfish/ironfish/build/src/network/peers/peerConnectionManager.js:66:53)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
Not connected to the Iron Fish network
```

**Comment by leanthebean** [comment]
I believe this is fixed, but also this issue is missing a lot of details that would help us debug.
