### ISSUE TITLE
Failed test after v1.22.17 update 

### ISSUE THREAD

**Issue by mettler** [iron-fish/ironfish#821]
Pulled in the most recent repo. Ran `yarn install` from root: 
```
$ yarn install    
yarn install v1.22.17
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.22s.
```
Then ran `yarn test` in `ironfish-cli` directory: 
```
 $ yarn test
yarn run v1.22.17
$ yarn clean && tsc -b && tsc -b tsconfig.test.json && jest
$ rimraf build
 FAIL   ironfish-cli  src/commands/accounts/pay.test.ts
  ● Test suite failed to run

    Cannot find module '../build/Release/node_datachannel.node' from '../node_modules/node-datachannel/lib/index.js'

    Require stack:
      /Users/mm/GitHub/ironfish/node_modules/node-datachannel/lib/index.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/connections/webRtcConnection.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/connections/index.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/peer.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/blockchain/blockchain.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/blockchain/index.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/index.js
      src/commands/accounts/pay.test.ts

      at Resolver.resolveModule (../node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (../node_modules/node-datachannel/lib/index.js:1:114)

 FAIL   ironfish-cli  src/commands/accounts/remove.test.ts
  ● Test suite failed to run

    Cannot find module '../build/Release/node_datachannel.node' from '../node_modules/node-datachannel/lib/index.js'

    Require stack:
      /Users/mm/GitHub/ironfish/node_modules/node-datachannel/lib/index.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/connections/webRtcConnection.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/connections/index.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/peer.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/blockchain/blockchain.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/blockchain/index.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/index.js
      src/commands/accounts/remove.test.ts

      at Resolver.resolveModule (../node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (../node_modules/node-datachannel/lib/index.js:1:114)

 FAIL   ironfish-cli  src/commands/accounts/which.test.ts
  ● Test suite failed to run

    Cannot find module '../build/Release/node_datachannel.node' from '../node_modules/node-datachannel/lib/index.js'

    Require stack:
      /Users/mm/GitHub/ironfish/node_modules/node-datachannel/lib/index.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/connections/webRtcConnection.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/connections/index.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/peer.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/blockchain/blockchain.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/blockchain/index.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/index.js
      src/commands/accounts/which.test.ts

      at Resolver.resolveModule (../node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (../node_modules/node-datachannel/lib/index.js:1:114)

 FAIL   ironfish-cli  src/commands/faucet.test.ts
  ● Test suite failed to run

    Cannot find module '../build/Release/node_datachannel.node' from '../node_modules/node-datachannel/lib/index.js'

    Require stack:
      /Users/mm/GitHub/ironfish/node_modules/node-datachannel/lib/index.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/connections/webRtcConnection.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/connections/index.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/peer.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/blockchain/blockchain.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/blockchain/index.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/index.js
      src/commands/faucet.test.ts

      at Resolver.resolveModule (../node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (../node_modules/node-datachannel/lib/index.js:1:114)

 FAIL   ironfish-cli  src/commands/start.test.ts
  ● Test suite failed to run

    Cannot find module '../build/Release/node_datachannel.node' from '../node_modules/node-datachannel/lib/index.js'

    Require stack:
      /Users/mm/GitHub/ironfish/node_modules/node-datachannel/lib/index.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/connections/webRtcConnection.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/connections/index.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/peer.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/blockchain/blockchain.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/blockchain/index.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/index.js
      src/commands/start.test.ts

      at Resolver.resolveModule (../node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (../node_modules/node-datachannel/lib/index.js:1:114)

 FAIL   ironfish-cli  src/commands/accounts/create.test.ts
  ● Test suite failed to run

    Cannot find module '../build/Release/node_datachannel.node' from '../node_modules/node-datachannel/lib/index.js'

    Require stack:
      /Users/mm/GitHub/ironfish/node_modules/node-datachannel/lib/index.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/connections/webRtcConnection.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/connections/index.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/peer.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/blockchain/blockchain.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/blockchain/index.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/index.js
      src/commands/accounts/create.test.ts

      at Resolver.resolveModule (../node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (../node_modules/node-datachannel/lib/index.js:1:114)

 FAIL   ironfish-cli  src/commands/accounts/balance.test.ts
  ● Test suite failed to run

    Cannot find module '../build/Release/node_datachannel.node' from '../node_modules/node-datachannel/lib/index.js'

    Require stack:
      /Users/mm/GitHub/ironfish/node_modules/node-datachannel/lib/index.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/connections/webRtcConnection.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/connections/index.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/peer.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/blockchain/blockchain.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/blockchain/index.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/index.js
      src/commands/accounts/balance.test.ts

      at Resolver.resolveModule (../node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (../node_modules/node-datachannel/lib/index.js:1:114)

 FAIL   ironfish-cli  src/commands/accounts/use.test.ts
  ● Test suite failed to run

    Cannot find module '../build/Release/node_datachannel.node' from '../node_modules/node-datachannel/lib/index.js'

    Require stack:
      /Users/mm/GitHub/ironfish/node_modules/node-datachannel/lib/index.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/connections/webRtcConnection.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/connections/index.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/peer.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/blockchain/blockchain.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/blockchain/index.js
      /Users/mm/GitHub/ironfish/ironfish/build/src/index.js
      src/commands/accounts/use.test.ts

      at Resolver.resolveModule (../node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (../node_modules/node-datachannel/lib/index.js:1:114)

(node:15205) [MODULE_NOT_FOUND] Error Plugin: ironfish-cli: Cannot find module '../build/Release/node_datachannel.node' from '../node_modules/node-datachannel/lib/index.js'

Require stack:
  /Users/mm/GitHub/ironfish/node_modules/node-datachannel/lib/index.js
  /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/connections/webRtcConnection.js
  /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/connections/index.js
  /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/peer.js
  /Users/mm/GitHub/ironfish/ironfish/build/src/blockchain/blockchain.js
  /Users/mm/GitHub/ironfish/ironfish/build/src/blockchain/index.js
  /Users/mm/GitHub/ironfish/ironfish/build/src/index.js
  src/commands/accounts/rescan.test.ts

module: @oclif/config@1.17.0
task: toCached
plugin: ironfish-cli
root: /Users/mm/GitHub/ironfish/ironfish-cli
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15204) [MODULE_NOT_FOUND] Error Plugin: ironfish-cli: Cannot find module '../build/Release/node_datachannel.node' from '../node_modules/node-datachannel/lib/index.js'

Require stack:
  /Users/mm/GitHub/ironfish/node_modules/node-datachannel/lib/index.js
  /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/connections/webRtcConnection.js
  /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/connections/index.js
  /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/peer.js
  /Users/mm/GitHub/ironfish/ironfish/build/src/blockchain/blockchain.js
  /Users/mm/GitHub/ironfish/ironfish/build/src/blockchain/index.js
  /Users/mm/GitHub/ironfish/ironfish/build/src/index.js
  src/commands/accounts/list.test.ts

module: @oclif/config@1.17.0
task: toCached
plugin: ironfish-cli
root: /Users/mm/GitHub/ironfish/ironfish-cli
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15203) [MODULE_NOT_FOUND] Error Plugin: ironfish-cli: Cannot find module '../build/Release/node_datachannel.node' from '../node_modules/node-datachannel/lib/index.js'

Require stack:
  /Users/mm/GitHub/ironfish/node_modules/node-datachannel/lib/index.js
  /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/connections/webRtcConnection.js
  /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/connections/index.js
  /Users/mm/GitHub/ironfish/ironfish/build/src/network/peers/peer.js
  /Users/mm/GitHub/ironfish/ironfish/build/src/blockchain/blockchain.js
  /Users/mm/GitHub/ironfish/ironfish/build/src/blockchain/index.js
  /Users/mm/GitHub/ironfish/ironfish/build/src/index.js
  src/commands/accounts/export.test.ts

module: @oclif/config@1.17.0
task: toCached
plugin: ironfish-cli
root: /Users/mm/GitHub/ironfish/ironfish-cli
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
 FAIL   ironfish-cli  src/commands/accounts/list.test.ts
  ● accounts:list › fetching all accounts › logs all account names

    TypeError: ironfish_1.createRootLogger is not a function

      48 |   constructor(argv: string[], config: IConfig) {
      49 |     super(argv, config)
    > 50 |     this.logger = createRootLogger().withTag(this.ctor.id)
         |                   ^
      51 |   }
      52 |
      53 |   abstract start(): Promise<void> | void

      at new IronfishCommand (src/command.ts:50:19)
      at new ListCommand (src/commands/accounts/list.ts:7:1)
      at Function.Object.<anonymous>.Command.run (../node_modules/@oclif/command/lib/command.js:161:17)
      at Config.runCommand (../node_modules/@oclif/config/lib/config.js:173:24)
      at Object.run (../node_modules/@oclif/test/lib/command.js:20:13)
      at Object.run (../node_modules/fancy-test/lib/base.js:68:25)

 FAIL   ironfish-cli  src/commands/accounts/export.test.ts (6.441 s)
  ● accounts:export › with no flags › logs the account to stdout

    TypeError: ironfish_1.createRootLogger is not a function

      48 |   constructor(argv: string[], config: IConfig) {
      49 |     super(argv, config)
    > 50 |     this.logger = createRootLogger().withTag(this.ctor.id)
         |                   ^
      51 |   }
      52 |
      53 |   abstract start(): Promise<void> | void

      at new IronfishCommand (src/command.ts:50:19)
      at new ExportCommand (src/commands/accounts/export.ts:13:1)
      at Function.Object.<anonymous>.Command.run (../node_modules/@oclif/command/lib/command.js:161:17)
      at Config.runCommand (../node_modules/@oclif/config/lib/config.js:173:24)
      at Object.run (../node_modules/@oclif/test/lib/command.js:20:13)
      at Object.run (../node_modules/fancy-test/lib/base.js:68:25)

  ● accounts:export › with the local flag › logs the account to stdout

    TypeError: The "warning" argument must be of type string or an instance of Error. Received an instance of CLIError

      at Plugin.warn (../node_modules/@oclif/config/lib/plugin.js:248:17)
      at ../node_modules/@oclif/config/lib/plugin.js:231:30
          at Array.map (<anonymous>)
      at Plugin._manifest (../node_modules/@oclif/config/lib/plugin.js:224:39)
      at Plugin.load (../node_modules/@oclif/config/lib/plugin.js:112:25)
      at Config.load (../node_modules/@oclif/config/lib/config.js:41:9)
      at Object.load (../node_modules/@oclif/config/lib/config.js:374:5)
      at Object.run (../node_modules/@oclif/test/lib/load-config.js:12:26)

 FAIL   ironfish-cli  src/commands/accounts/rescan.test.ts (6.404 s)
  ● accounts:rescan › with no flags › fetches sequences from the client and scans successfully

    TypeError: ironfish_1.createRootLogger is not a function

      48 |   constructor(argv: string[], config: IConfig) {
      49 |     super(argv, config)
    > 50 |     this.logger = createRootLogger().withTag(this.ctor.id)
         |                   ^
      51 |   }
      52 |
      53 |   abstract start(): Promise<void> | void

      at new IronfishCommand (src/command.ts:50:19)
      at new RescanCommand (src/commands/accounts/rescan.ts:10:1)
      at Function.Object.<anonymous>.Command.run (../node_modules/@oclif/command/lib/command.js:161:17)
      at Config.runCommand (../node_modules/@oclif/config/lib/config.js:173:24)
      at Object.run (../node_modules/@oclif/test/lib/command.js:20:13)
      at Object.run (../node_modules/fancy-test/lib/base.js:68:25)

  ● accounts:rescan › with the local flag › fetches sequences from the node and scans successfully

    TypeError: The "warning" argument must be of type string or an instance of Error. Received an instance of CLIError

      at Plugin.warn (../node_modules/@oclif/config/lib/plugin.js:248:17)
      at ../node_modules/@oclif/config/lib/plugin.js:231:30
          at Array.map (<anonymous>)
      at Plugin._manifest (../node_modules/@oclif/config/lib/plugin.js:224:39)
      at Plugin.load (../node_modules/@oclif/config/lib/plugin.js:112:25)
      at Config.load (../node_modules/@oclif/config/lib/config.js:41:9)
      at Object.load (../node_modules/@oclif/config/lib/config.js:374:5)
      at Object.run (../node_modules/@oclif/test/lib/load-config.js:12:26)

Test Suites: 11 failed, 11 total
Tests:       5 failed, 5 total
Snapshots:   0 total
Time:        6.66 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by dguenther** [comment]
Try deleting your `node_modules` folders and running `yarn install` again.

**Comment by mettler** [comment]
That solved it!
