### ISSUE TITLE
Crash: do not know how to serialize a bigint

### ISSUE THREAD

**Issue by zmeyc** [iron-fish/ironfish#841]
```
Peer aGPLoPh (mihail4) sent orphan 00000...d164a (34128), syncing orphan chain.
Starting sync from aGPLoPh (mihail4). work: +-6046322351409853, ours: 43632, theirs: 37399
Finding ancestor using linear search on last 3 blocks starting at 00000...6c802 (43632) from peer aGPLoPh (mihail4) at 37399
Peer aGPLoPh (mihail4) disconnected (DISCONNECTED) while syncing.
Added block to fork seq: 31287, head-seq: 43635, hash: 00000...9cc40, head-hash: 00000...24595, work: 2382549065062680, head-work: 7587222499539138, work-diff: 5204673434476458
Added block seq: 43640, hash: 00000...44114, txs: 1, progress: 100.00%, time: 77.1ms
Added block seq: 43660, hash: 00000...a10ae, txs: 1, progress: 100.00%, time: 78.7ms
Reorganizing chain from 00000...6a141 (43670) for 00000...ab38e (43670) on prev 00000...f2637 (43669)
Reorganized chain. blocks: 1, old: 00000...6a141 (43670), new: 00000...f2637 (43669), fork: 00000...f2637 (43669)
Added block seq: 43680, hash: 00000...d3c62, txs: 1, progress: 100.00%, time: 76.6ms
/usr/src/app/node_modules/js-message/Message.js:38
        return JSON.stringify(
                    ^

TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at Message.getJSON [as JSON] (/usr/src/app/node_modules/js-message/Message.js:38:21)
    at Parser.format (/usr/src/app/node_modules/node-ipc/entities/EventParser.js:21:21)
    at Server.emit (/usr/src/app/node_modules/node-ipc/dao/socketServer.js:79:29)
    at IpcAdapter.emitStream (/usr/src/app/node_modules/ironfish/build/src/rpc/adapters/ipcAdapter.js:206:21)
    at Request.onStream (/usr/src/app/node_modules/ironfish/build/src/rpc/adapters/ipcAdapter.js:180:18)
    at Request.stream (/usr/src/app/node_modules/ironfish/build/src/rpc/request.js:41:14)
    at InterceptReporter.callback (/usr/src/app/node_modules/ironfish/build/src/rpc/routes/node/getLogStream.js:41:17)
    at InterceptReporter.log (/usr/src/app/node_modules/ironfish/build/src/logger/reporters/intercept.js:12:14)
    at _log (/usr/src/app/node_modules/consola/dist/consola.js:1:7915)
```

**Comment by dguenther** [comment]
Duplicates #507
