### ISSUE TITLE
Error: Parsing internal.json Failed

### ISSUE THREAD

**Issue by QustomQure** [iron-fish/ironfish#866]
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run start --workers=6
Error: Parsing internal.json Failed
Unexpected token "\u0000" (0x00) in JSON at position 0 while parsing near "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000..." in internal.json

> 1 |
    | ^

    at tryParse (C:\Users\fr0ze\ironfish-master\ironfish\build\src\utils\json.js:39:27)
    at Object.parse (C:\Users\fr0ze\ironfish-master\ironfish\build\src\utils\json.js:25:29)
    at FileStore.load (C:\Users\fr0ze\ironfish-master\ironfish\build\src\fileStores\fileStore.js:29:40)
    at async InternalStore.load (C:\Users\fr0ze\ironfish-master\ironfish\build\src\fileStores\keyStore.js:25:22)
    at async Function.init (C:\Users\fr0ze\ironfish-master\ironfish\build\src\sdk.js:40:9)
    at async Start.init (C:\Users\fr0ze\ironfish-master\ironfish-cli\build\command.js:69:20)
    at async Start._run (C:\Users\fr0ze\ironfish-master\ironfish-cli\node_modules\@oclif\command\lib\command.js:42:13)
    at async Config.runCommand (C:\Users\fr0ze\ironfish-master\ironfish-cli\node_modules\@oclif\config\lib\config.js:173:24)
    at async Main.run (C:\Users\fr0ze\ironfish-master\ironfish-cli\node_modules\@oclif\command\lib\main.js:27:9)
    at async Main._run (C:\Users\fr0ze\ironfish-master\ironfish-cli\node_modules\@oclif\command\lib\command.js:43:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

My internal.json file occasionally have blank content

**Comment by QustomQure** [comment]
Graffiti Qualia

**Comment by QustomQure** [comment]
resolved after deleting file internal.json

**Comment by deekerno** [comment]
This should be fixed as a result of [v0.1.29](https://github.com/iron-fish/ironfish/tree/v0.1.29). If you're still encountering this problem, feel free to re-open this issue.
