### ISSUE TITLE
error in log: undefined is not a 64-character hex string

### ISSUE THREAD

**Issue by reb0rn21** [iron-fish/ironfish#873]
Latest node compiled 1.16, ubuntu 20.04:
`Error when adding new block 62249 from 6W4+O5I (khunchan): Error: undefined is not a 64-character hex string
    at Uint8ArraySerde.deserialize (/root/ironfish/ironfish/build/src/serde/Uint8ArraySerde.js:40:19)
    at BufferSerde.deserialize (/root/ironfish/ironfish/build/src/serde/BufferSerde.js:26:39)
    at BlockHeaderSerde.deserialize (/root/ironfish/ironfish/build/src/primitives/blockheader.js:156:270)
    at BlockSerde.deserialize (/root/ironfish/ironfish/build/src/primitives/block.js:113:50)
    at Syncer.addBlock (/root/ironfish/ironfish/build/src/syncer.js:278:54)
    at Syncer.addNewBlock (/root/ironfish/ironfish/build/src/syncer.js:309:45)
    at PeerNetwork.onNewBlock (/root/ironfish/ironfish/build/src/network/peerNetwork.js:479:43)
    at /root/ironfish/ironfish/build/src/network/peerNetwork.js:87:34
    at hdlr (/root/ironfish/ironfish/build/src/network/peerNetwork.js:254:26)
    at async GossipRouter.handle (/root/ironfish/ironfish/build/src/network/messageRouters/gossip.js:62:24)`

**Comment by QustomQure** [comment]
Have the same issue on windows

**Comment by reb0rn21** [comment]
Updated to 1.17 now no more issue....

**Comment by lifeofzero** [comment]
Upgraded: 0.1.18 on Ubuntu, syncing/mining now.

**Comment by deekerno** [comment]
This issue has been resolved as of v0.1.18.
