### ISSUE TITLE
yarn start strips quotation marks from commands?

### ISSUE THREAD

**Issue by AmberKiso** [iron-fish/ironfish#954]
### What happened?

I noticed that `yarn start` seems to strip the quotations from string parameters passed in. If there are spaces in that string, like for graffiti, the command will attempt to process those newly-generated substrings and fail.
`yarn start:once` doesn't have this symptom.

I'm not sure if this is a bug or an inherent behavior of yarn or a package.

### Version

0.1.20

### Relevant log output

```shell
yarn start config:set blockGraffiti "Yabba dabba doo"
(ran first)
-----


8:00:29 PM - Starting compilation in watch mode...


8:00:29 PM - Found 0 errors. Watching for file changes.
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run config:set blockGraffiti Yabba dabba doo
Error: Unexpected arguments: dabba, doo
See more help with --help
    at validateArgs (C:\Users\mjolnir\Documents\GitHub\ironfish\node_modules\@oclif\parser\lib\validate.js:10:19)
    at Object.validate (C:\Users\mjolnir\Documents\GitHub\ironfish\node_modules\@oclif\parser\lib\validate.js:55:5)
    at Object.parse (C:\Users\mjolnir\Documents\GitHub\ironfish\node_modules\@oclif\parser\lib\index.js:28:7)
    at SetCommand.parse (C:\Users\mjolnir\Documents\GitHub\ironfish\node_modules\@oclif\command\lib\command.js:86:41)
    at SetCommand.init (C:\Users\mjolnir\Documents\GitHub\ironfish\ironfish-cli\build\src\command.js:41:32)
    at SetCommand._run (C:\Users\mjolnir\Documents\GitHub\ironfish\node_modules\@oclif\command\lib\command.js:42:24)
    at Function.Command.run (C:\Users\mjolnir\Documents\GitHub\ironfish\node_modules\@oclif\command\lib\command.js:162:16)
    at async Config.runCommand (C:\Users\mjolnir\Documents\GitHub\ironfish\node_modules\@oclif\config\lib\config.js:173:24)
    at async Main.run (C:\Users\mjolnir\Documents\GitHub\ironfish\node_modules\@oclif\command\lib\main.js:27:9)
    at async Main._run (C:\Users\mjolnir\Documents\GitHub\ironfish\node_modules\@oclif\command\lib\command.js:43:20)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

C:\Users\mjolnir\Documents\GitHub\ironfish\ironfish-cli>yarn start:once config:set blockGraffiti "Yabba dabba doo"
yarn run v1.22.17
$ yarn build && yarn start:js config:set blockGraffiti "Yabba dabba doo"
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run config:set blockGraffiti "Yabba dabba doo"
Done in 2.00s.
```

**Comment by lwisne** [comment]
We believe this is now fixed. Let us know if you don't agree!
