### ISSUE TITLE
editor param in config set but does not recognized

### ISSUE THREAD

**Issue by GreenUkr** [iron-fish/ironfish#964]
### What happened?
I noticed than ` yarn start:once config:edit` finished with error, despite `editor` is set in config
### Version
 1.21 (1.18 worked normal)

My Graffiti is "GreenUkr"

### Relevant log output
`
greenukr@ironfish:~/ironfish/ironfish-cli$ yarn start:once config:edit`
`yarn run v1.22.17
$ yarn build && yarn start:js config:edit
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run config:edit
Editing /home/greenukr/.ironfish/config.json
Error: you must set the EDITOR environment variable or 'editor' in the ironfish config
    at Object.launchEditor (/home/greenukr/ironfish/ironfish-cli/build/src/utils/editor.js:15:15)
    at EditCommand.start (/home/greenukr/ironfish/ironfish-cli/build/src/commands/config/edit.js:28:40)
    at EditCommand.run (/home/greenukr/ironfish/ironfish-cli/build/src/command.js:23:24)
    at EditCommand._run (/home/greenukr/ironfish/node_modules/@oclif/command/lib/command.js:43:31)
    at async Config.runCommand (/home/greenukr/ironfish/node_modules/@oclif/config/lib/config.js:173:24)
    at async Main.run (/home/greenukr/ironfish/node_modules/@oclif/command/lib/main.js:27:9)
    at async Main._run (/home/greenukr/ironfish/node_modules/@oclif/command/lib/command.js:43:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

`
greenukr@ironfish:~/ironfish/ironfish-cli$ yarn start:once config:show |grep editor
`
`   "editor": "/bin/nano",`

`greenukr@ironfish:~/ironfish/ironfish-cli$ yarn start:once config:get editor`
`yarn run v1.22.17
$ yarn build && yarn start:js config:get editor
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run config:get editor
"/bin/nano"
Done in 1.25s.`

**Comment by mat-if** [comment]
This should be fixed now in 0.1.24 with #1039, let me know if that isn't the case by re-opening this issue. Thanks!
