### ISSUE TITLE
chain:block is not an ironfish command

### ISSUE THREAD

**Issue by AmberKiso** [iron-fish/ironfish#976]
### What happened?

The web CLI shows chain:block as a command, but it is rejected.

### Version

0.1.21

### Relevant log output

```shell
yarn start:once chain:block 80000
yarn run v1.22.17
$ yarn build && yarn start:js chain:block 80000
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run chain:block 80000
Warning: chain:block is not a ironfish command.
    at Object.warn (C:\Users\mjolnir\Documents\GitHub\ironfish\node_modules\@oclif\errors\lib\index.js:49:15)
    at Object.warn (C:\Users\mjolnir\Documents\GitHub\ironfish\node_modules\@oclif\config\lib\config.js:136:30)
    at Object.hook (C:\Users\mjolnir\Documents\GitHub\ironfish\node_modules\@oclif\plugin-not-found\lib\index.js:25:10)
    at async C:\Users\mjolnir\Documents\GitHub\ironfish\node_modules\@oclif\config\lib\config.js:151:21
    at async Promise.all (index 0)
    at async Promise.all (index 2)
    at async Config.runHook (C:\Users\mjolnir\Documents\GitHub\ironfish\node_modules\@oclif\config\lib\config.js:161:9)
    at async Config.runCommand (C:\Users\mjolnir\Documents\GitHub\ironfish\node_modules\@oclif\config\lib\config.js:168:13)
    at async Main.run (C:\Users\mjolnir\Documents\GitHub\ironfish\node_modules\@oclif\command\lib\main.js:27:9)
    at async Main._run (C:\Users\mjolnir\Documents\GitHub\ironfish\node_modules\@oclif\command\lib\command.js:43:20)
Did you mean chain:forks? [y/n]: n
```

**Comment by AmberKiso** [comment]
https://github.com/iron-fish/website/pull/147 fixes this

**Comment by AmberKiso** [comment]
147 committed, so 🚢 ❗ 
(Relocated to blocks:show)
