### ISSUE TITLE
yarn install fails on macosx 'node-gyp' issue

### ISSUE THREAD

**Issue by wd021** [iron-fish/ironfish#983]
### What happened?

Tried installing ironfish on an old macbook air and ran into the following issue when executing `yarn install`

### Relevant log output

```shell
error /Users/simonbob/Documents/ironfish/ironfish/node_modules/mrmr: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/simonbob/Documents/ironfish/ironfish/node_modules/mrmr
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.14.0 | darwin | x64
gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - executable path is "/usr/bin/python"
gyp ERR! find Python - version is "2.7.10"
gyp ERR! find Python - version is 2.7.10 - should be >=3.6.0
gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
gyp ERR! find Python 
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/Users/simonbob/Documents/ironfish/ironfish/node_modules/node-gyp/lib/find-python.js:330:47)
gyp ERR! stack     at PythonFinder.runChecks (/Users/simonbob/Documents/ironfish/ironfish/node_modules/node-gyp/lib/find-python.js:159:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/Users/simonbob/Documents/ironfish/ironfish/node_modules/node-gyp/lib/find-python.js:266:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/Users/simonbob/Documents/ironfish/ironfish/node_modules/node-gyp/lib/find-python.js:297:7)
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:390:7)
gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
gyp ERR! stack     at Socket.<anonymous> (node:internal/child_process:451:11)
gyp ERR! stack     at Socket.emit (node:events:520:28)
gyp ERR! stack     at Pipe.<anonymous> (node:net:687:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/Users/simonbob/Documents/ironfish/ironfish/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/simonbob/Documents/ironfish/ironfish/node_modules/mrmr
```

**Comment by wd021** [comment]
`brew install python` works. node-gyp v8.4.1 requires python 3.7+. 

PR https://github.com/iron-fish/ironfish/pull/985 to update the readme for this.

**Comment by Lifehack-crypto** [comment]
ubuntu 20.04,
Even with node V16.15.0, npm install fails due to  ”node-pre-gyp".
![image](https://user-images.githubusercontent.com/24289365/169245452-208ab940-7268-4e77-9a1e-ef36c12fc432.png)

**Comment by lwisne** [comment]
Are you still having issues here?
