### ISSUE TITLE
director.test.slow and merkletree failures in yarn test:coverage:html

### ISSUE THREAD

**Issue by AmberKiso** [iron-fish/ironfish#990]
### What happened?

ran `ironfish\ironfish\src\yarn test:coverage:html` from 0.1.21 base code

Got a couple failures in the logs.

### Version

0.1.21

### Relevant log output

```shell
Summary of all failing tests
 FAIL  src/mining/director.test.slow.ts (52.212 s)
  ● Mining director › After mining › discards block if chain changed

    Expected timestamp is in future to be undefined

      10 |   static isUndefined<T>(x: undefined | T, message?: string): asserts x is undefined {
      11 |     if (x !== undefined) {
    > 12 |       throw new Error(message || `Expected ${String(x)} to be undefined`)
         |             ^
      13 |     }
      14 |   }
      15 |

      at Function.isUndefined (src/assert.ts:12:13)
      at Object.makeBlockAfter (src/testUtilities/helpers/blockchain.ts:49:10)
      at Object.<anonymous> (src/mining/director.test.slow.ts:255:23)

  ● Mining director › After mining › discards block if not valid

    Expected timestamp is in future to be undefined

      10 |   static isUndefined<T>(x: undefined | T, message?: string): asserts x is undefined {
      11 |     if (x !== undefined) {
    > 12 |       throw new Error(message || `Expected ${String(x)} to be undefined`)
         |             ^
      13 |     }
      14 |   }
      15 |

      at Function.isUndefined (src/assert.ts:12:13)
      at Object.makeBlockAfter (src/testUtilities/helpers/blockchain.ts:49:10)
      at Object.<anonymous> (src/mining/director.test.slow.ts:272:21)

  ● Mining director › After mining › discard block if cannot add to chain

    Expected timestamp is in future to be undefined

      10 |   static isUndefined<T>(x: undefined | T, message?: string): asserts x is undefined {
      11 |     if (x !== undefined) {
    > 12 |       throw new Error(message || `Expected ${String(x)} to be undefined`)
         |             ^
      13 |     }
      14 |   }
      15 |

      at Function.isUndefined (src/assert.ts:12:13)
      at Object.makeBlockAfter (src/testUtilities/helpers/blockchain.ts:49:10)
      at Object.<anonymous> (src/mining/director.test.slow.ts:288:21)

 FAIL  src/merkletree/merkletree.test.ts (11.343 s)
  ● Merkle tree › does not find value after truncating tree

    : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:

      326 |   })
      327 |
    > 328 |   it('does not find value after truncating tree', async () => {
          |   ^
      329 |     const tree = await makeTree()
      330 |     const elementSize = 32
      331 |

      at new Spec (../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (src/merkletree/merkletree.test.ts:328:3)


Test Suites: 2 failed, 63 passed, 65 total
Tests:       4 failed, 468 passed, 472 total
Snapshots:   28 passed, 28 total
Time:        385.183 s, estimated 387 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by AmberKiso** [comment]
This is another issue with DB locking discovered in #934.
For my Windows laptop, adding `-w 4` to the Jest options in the test and test:coverage:html script rows in the package.json files fixes this on my laptop.

Closing as there is a workaround.
